//! Reference documentation generation (FR-7.7).
//!
//! Per-manager Markdown plus the auth / pagination / errors cross-cutting
//! guides, generated from the same IR the code is (so the docs describe
//! the real Go surface — method names, types, paged variants — and can't
//! drift from it). Deterministic, like all output (FR-6.2).

use std::collections::HashMap;
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::pascal;
use gantry_sema::Analysis;
use gantry_synth::PagedOperation;

use crate::managers::method_name;
use crate::models::GeneratedFile;

/// Generate `docs/` — an index, one page per manager, and the guides.
pub fn generate_docs(analysis: &Analysis<'_>, paged: &[PagedOperation]) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let paged_by_op: HashMap<usize, &PagedOperation> =
        paged.iter().map(|p| (p.operation, p)).collect();

    let mut files = Vec::new();
    files.push(index_page(analysis));
    for (manager, op_indices) in &analysis.managers {
        files.push(manager_page(program, &paged_by_op, manager, op_indices));
    }
    files.push(guide("auth", AUTH_GUIDE));
    files.push(guide("pagination", PAGINATION_GUIDE));
    files.push(guide("errors", ERRORS_GUIDE));
    files
}

fn index_page(analysis: &Analysis<'_>) -> GeneratedFile {
    let mut body = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# Box SDK reference\n\n\
         One resource manager per Box API tag, reached through the single\n\
         `client.Client` entry point.\n\n## Guides\n\n\
         - [Authentication](auth.md)\n- [Pagination](pagination.md)\n- [Errors](errors.md)\n\n\
         ## Managers\n\n| Manager | Operations |\n|---|---|\n",
    );
    for (manager, ops) in &analysis.managers {
        let _ = writeln!(
            body,
            "| [{name}](managers/{manager}.md) | {count} |",
            name = pascal(manager),
            count = ops.len(),
        );
    }
    GeneratedFile {
        path: "docs/README.md".to_string(),
        content: body,
    }
}

fn manager_page(
    program: &ir::Program,
    paged: &HashMap<usize, &PagedOperation>,
    manager: &str,
    op_indices: &[usize],
) -> GeneratedFile {
    let mut body = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# {}Manager\n\n\
         Access via `client.NewClient().{}`.\n\n",
        pascal(manager),
        pascal(manager),
    );
    for &index in op_indices {
        let op = &program.operations[index];
        let method = method_name(op);
        let _ = writeln!(body, "## {method}\n");
        if op.deprecated {
            body.push_str("> **Deprecated.**\n\n");
        }
        let _ = writeln!(
            body,
            "`{http} {path}`\n",
            http = http_method(op.method),
            path = render_path(op),
        );

        let params: Vec<&ir::Param> = op.params.iter().collect();
        if !params.is_empty() {
            body.push_str("| Parameter | In | Type | Required |\n|---|---|---|---|\n");
            for param in &params {
                let required = !matches!(param.ty, ir::Type::Optional(_));
                let _ = writeln!(
                    body,
                    "| `{name}` | {loc} | `{ty}` | {req} |",
                    name = param.wire_name,
                    loc = param_location(param.location),
                    ty = describe(program, unwrap(&param.ty)),
                    req = if required { "yes" } else { "no" },
                );
            }
            body.push('\n');
        }
        if let Some(req) = &op.request {
            let _ = writeln!(
                body,
                "**Request body** (`{media}`): `{ty}`\n",
                media = request_media(req.media),
                ty = describe(program, unwrap(&req.ty)),
            );
        }
        let _ = writeln!(
            body,
            "**Returns:** {}\n",
            describe_response(program, &op.response)
        );
        if paged.contains_key(&index) {
            let _ = writeln!(
                body,
                "Paginated — `{method}(...)` returns `iter.Seq2[*T, error]`, \
                 threading the cursor for you. See the [pagination guide](../pagination.md).\n"
            );
        }
    }
    GeneratedFile {
        path: format!("docs/managers/{manager}.md"),
        content: body,
    }
}

fn guide(name: &str, content: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("docs/{name}.md"),
        content: format!("<!-- Generated by box-gantry. DO NOT EDIT. -->\n{content}"),
    }
}

/// A readable (Go-flavored) name for a type, for docs only.
fn describe(program: &ir::Program, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Bool => "bool".into(),
        ir::Type::Int64 => "int64".into(),
        ir::Type::Float64 => "float64".into(),
        ir::Type::String => "string".into(),
        ir::Type::Date => "Date".into(),
        ir::Type::DateTime => "time.Time".into(),
        ir::Type::Binary => "io.Reader".into(),
        ir::Type::JsonValue => "any".into(),
        ir::Type::List(inner) => format!("[]{}", describe(program, inner)),
        ir::Type::Map(inner) => format!("map[string]{}", describe(program, inner)),
        ir::Type::Decl(id) => program.decl(*id).name.as_str().to_string(),
        ir::Type::Optional(inner) => format!("Optional<{}>", describe(program, inner)),
        ir::Type::Nullable(inner) => format!("Nullable<{}>", describe(program, inner)),
    }
}

fn describe_response(program: &ir::Program, response: &ir::ResponseShape) -> String {
    match response {
        ir::ResponseShape::None => "no content".into(),
        ir::ResponseShape::Json(ty) => format!("`{}`", describe(program, unwrap(ty))),
        ir::ResponseShape::Binary => "a binary stream (`io.Reader`)".into(),
        ir::ResponseShape::Text => "text (`string`)".into(),
        ir::ResponseShape::Redirect => "a redirect URL (`string`)".into(),
    }
}

fn unwrap(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}

fn render_path(op: &ir::Operation) -> String {
    let mut out = String::new();
    for segment in &op.path {
        out.push('/');
        match segment {
            ir::PathSegment::Literal(text) => out.push_str(text),
            ir::PathSegment::Parameter(name) => {
                let _ = write!(out, "{{{}}}", name.as_str());
            }
            ir::PathSegment::Composite(parts) => {
                for part in parts {
                    match part {
                        ir::PathPart::Literal(text) => out.push_str(text),
                        ir::PathPart::Parameter(name) => {
                            let _ = write!(out, "{{{}}}", name.as_str());
                        }
                    }
                }
            }
        }
    }
    out
}

fn http_method(method: ir::HttpMethod) -> &'static str {
    match method {
        ir::HttpMethod::Get => "GET",
        ir::HttpMethod::Put => "PUT",
        ir::HttpMethod::Post => "POST",
        ir::HttpMethod::Delete => "DELETE",
        ir::HttpMethod::Options => "OPTIONS",
        ir::HttpMethod::Head => "HEAD",
        ir::HttpMethod::Patch => "PATCH",
        ir::HttpMethod::Trace => "TRACE",
    }
}

fn param_location(location: ir::ParamLocation) -> &'static str {
    match location {
        ir::ParamLocation::Path => "path",
        ir::ParamLocation::Query => "query",
        ir::ParamLocation::Header => "header",
    }
}

fn request_media(media: ir::RequestMedia) -> &'static str {
    match media {
        ir::RequestMedia::Json => "application/json",
        ir::RequestMedia::JsonPatch => "application/json-patch+json",
        ir::RequestMedia::UrlEncoded => "application/x-www-form-urlencoded",
        ir::RequestMedia::Multipart => "multipart/form-data",
        ir::RequestMedia::OctetStream => "application/octet-stream",
    }
}

const AUTH_GUIDE: &str = "# Authentication\n\n\
Every request is authorized through the runtime's token source: the\n\
generated code calls `AccessToken(ctx)` and attaches the bearer token,\n\
and the network layer refreshes on a `401` and retries once. Pass one of\n\
the four Box auth flows — from the `auth` package — to `client.NewClient`\n\
at construction; each is a `gantryruntime.TokenSource` that caches its\n\
access token until shortly before it expires.\n\n\
## Developer Token\n\n\
```go\n\
c := client.NewClient(auth.DeveloperToken(\"DEVELOPER_TOKEN\"))\n\
```\n\n\
## Client Credentials Grant (server auth, no key)\n\n\
```go\n\
c := client.NewClient(auth.ClientCredentials(auth.CCGConfig{\n\
\tClientID:     \"CLIENT_ID\",\n\
\tClientSecret: \"CLIENT_SECRET\",\n\
\tEnterpriseID: \"ENTERPRISE_ID\", // or set UserID to act as a managed user\n\
}))\n\
```\n\n\
## JWT (server auth with a signing key)\n\n\
```go\n\
src, err := auth.JWTAuth(auth.JWTConfig{\n\
\tClientID:      \"CLIENT_ID\",\n\
\tClientSecret:  \"CLIENT_SECRET\",\n\
\tPublicKeyID:   \"PUBLIC_KEY_ID\",\n\
\tPrivateKeyPEM: privateKeyPEM, // optionally encrypted; set Passphrase\n\
\tEnterpriseID:  \"ENTERPRISE_ID\",\n\
})\n\
if err != nil {\n\t// bad key: fails loudly at construction\n}\n\
c := client.NewClient(src)\n\
```\n\n\
## OAuth 2.0 (authorization code)\n\n\
Redirect the user to `cfg.AuthorizeURL(redirectURI, state)`, exchange the\n\
returned code, then reuse the stored refresh token on later runs:\n\n\
```go\n\
cfg := auth.OAuthConfig{ClientID: \"CLIENT_ID\", ClientSecret: \"CLIENT_SECRET\"}\n\
src, err := cfg.ExchangeCode(ctx, code, redirectURI)\n\
// later: src := auth.OAuth(cfg, storedRefreshToken)\n\
c := client.NewClient(src)\n\
```\n";

const PAGINATION_GUIDE: &str = "# Pagination\n\n\
Marker- and offset-paginated list operations return an\n\
`iter.Seq2[*T, error]` — the list method *is* the paginator. Range over it\n\
to walk every page transparently:\n\n\
```go\n\
for item, err := range client.Folders.ListItems(ctx, folderID, nil) {\n\
\tif err != nil {\n\t\treturn err\n\t}\n\t// use item\n}\n\
```\n\n\
The iterator threads the cursor for you and stops when the last page is\n\
reached. It copies the options you pass, so your struct is never\n\
mutated.\n";

const ERRORS_GUIDE: &str = "# Errors\n\n\
Every I/O method returns `(T, error)` (Go's idiomatic error model). A\n\
non-nil error is either a transport failure or a non-2xx response after\n\
the network layer's retries (exponential backoff + jitter, `401`\n\
refresh, `Retry-After`). Response bodies for error statuses carry the\n\
Box error schema and can be inspected on the returned error.\n";
