//! The Go backend: lowering + printer (FR-6, TR-Go).
//!
//! Generates the SDK tree: `schemas/` model packages (D-110 tri-state
//! mapping, open enums, union variant structs with the only generated
//! serializers), `managers/` with one method per operation calling only
//! through the runtime contract (FR-5.2), the `client/` entry point
//! (FR-7.1), and the contract's compilable runtime stubs so the whole
//! output compile-verifies without a real runtime (FR-5.3). Output is
//! deterministic (FR-6.2) and gofmt-clean by construction (G-17),
//! verified by the real toolchain (VR-1.1 — the primary CI signal).

mod docs;
mod managers;
mod models;
mod tests;

pub use docs::generate_docs;
pub use managers::{BackendError, generate_managers};
pub use models::{GeneratedFile, generate_models};
pub use tests::generate_tests;

/// Generate the complete SDK tree for a verified program.
pub fn generate(analysis: &gantry_sema::Analysis<'_>) -> Result<Vec<GeneratedFile>, BackendError> {
    let paged = gantry_synth::detect_pagination(analysis);
    let mut files = generate_models(analysis);
    files.extend(generate_managers(analysis, &paged)?);
    files.extend(generate_docs(analysis, &paged));
    files.extend(generate_tests(analysis));
    // The runtime stubs are rendered from the contract data (FR-5.2):
    // generated managers compile against exactly the declared surface.
    files.push(GeneratedFile {
        path: "gantryruntime/runtime.go".to_string(),
        content: gantry_contract::go_stubs(&gantry_contract::V1, &gantry_manifest::go()),
    });
    files.push(GeneratedFile {
        path: "serialization/serialization.go".to_string(),
        content: SERIALIZATION.to_string(),
    });
    Ok(files)
}

/// The hand-authored serialization package the models depend on. Static
/// (not per-model — TR-Go.2), so it is content here rather than
/// synthesized. Carries the D-110 tri-state (`Nullable[T]`, resolving
/// BG-1) and the RFC 3339 full-date type (`Date`).
const SERIALIZATION: &str = r#"// Code generated by box-gantry. DO NOT EDIT.
package serialization

import (
	"bytes"
	"encoding/json"
	"time"
)

// Nullable models the D-110 tri-state at a field that may be absent,
// explicitly null, or a value. Use *Nullable[T] with `,omitempty`: a nil
// pointer is absent; a non-nil pointer is sent, as null or as the value.
type Nullable[T any] struct {
	// Valid is false for an explicit JSON null.
	Valid bool
	Value T
}

// Value builds a present, non-null Nullable.
func Value[T any](v T) *Nullable[T] { return &Nullable[T]{Valid: true, Value: v} }

// Null builds a present, explicitly-null Nullable.
func Null[T any]() *Nullable[T] { return &Nullable[T]{} }

func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.Value)
}

func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		var zero T
		n.Valid, n.Value = false, zero
		return nil
	}
	n.Valid = true
	return json.Unmarshal(data, &n.Value)
}

// Date is an RFC 3339 full-date (no time component).
type Date struct{ time.Time }

const dateLayout = "2006-01-02"

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Time.Format(dateLayout))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	t, err := time.Parse(dateLayout, s)
	if err != nil {
		return err
	}
	d.Time = t
	return nil
}

func (d Date) String() string { return d.Time.Format(dateLayout) }
"#;
