//! Manager + client generation (FR-7.1, TR-Go.3): one manager struct per
//! grouping key, one method per operation, calling only through the
//! runtime contract (FR-5.2). URLs are built from structured path
//! segments — never re-parsed from template strings (FR-2.2).

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::{camel, constant, pascal};
use gantry_sema::Analysis;
use gantry_synth::{PageStyle, PagedOperation};

use crate::models::GeneratedFile;

/// A shape the Go backend cannot express is an engine bug (the program
/// was verified; the backend is at fault) — loud, never a placeholder
/// (FR-3.2, NF-1).
#[derive(Debug)]
pub struct BackendError {
    pub context: String,
    pub detail: String,
}

impl std::fmt::Display for BackendError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "go backend cannot express {}: {} — engine bug",
            self.context, self.detail
        )
    }
}

impl std::error::Error for BackendError {}

/// Generate `managers/*.go` (one file per manager) and `client/client.go`.
///
/// `paged` carries the pagination decisions from feature synthesis
/// (FR-7.3); the Go backend lowers each to an `iter.Seq2` iterator
/// (TR-Go.4).
pub fn generate_managers(
    analysis: &Analysis<'_>,
    paged: &[PagedOperation],
) -> Result<Vec<GeneratedFile>, BackendError> {
    let base_version = analysis
        .program
        .operations
        .first()
        .and_then(|op| op.api_version.clone());
    let paged_by_op: HashMap<usize, &PagedOperation> =
        paged.iter().map(|p| (p.operation, p)).collect();
    let mut files = Vec::new();
    for (manager, op_indices) in &analysis.managers {
        let mut printer = ManagerPrinter {
            analysis,
            base_version: base_version.clone(),
            paged: &paged_by_op,
            body: String::new(),
            imports: BTreeSet::new(),
        };
        printer.manager(manager, op_indices)?;
        files.push(printer.finish(manager));
    }
    files.push(helpers_file());
    files.push(client_file(analysis));
    Ok(files)
}

/// The single client entry point aggregating every manager (FR-7.1).
fn client_file(analysis: &Analysis<'_>) -> GeneratedFile {
    let mut body = String::new();
    let _ = writeln!(
        body,
        "// Code generated by box-gantry {}. DO NOT EDIT.\n\
         package client\n\n\
         import \"boxgantry.invalid/boxsdk/managers\"\n\n\
         // Client is the single entry point: one field per resource manager.",
        env!("CARGO_PKG_VERSION"),
    );
    let rows: Vec<(String, String)> = analysis
        .managers
        .keys()
        .map(|manager| {
            (
                pascal(manager),
                format!("*managers.{}Manager", pascal(manager)),
            )
        })
        .collect();
    let width = rows.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
    body.push_str("type Client struct {\n");
    for (name, ty) in &rows {
        let _ = writeln!(body, "\t{name:<width$} {ty}");
    }
    body.push_str("}\n\nfunc NewClient() *Client {\n\tc := &Client{}\n");
    for (name, _) in &rows {
        let _ = writeln!(body, "\tc.{name} = &managers.{name}Manager{{}}");
    }
    body.push_str("\treturn c\n}\n");
    GeneratedFile {
        path: "client/client.go".to_string(),
        content: body,
    }
}

struct ManagerPrinter<'a> {
    analysis: &'a Analysis<'a>,
    base_version: Option<ir::ApiVersion>,
    paged: &'a HashMap<usize, &'a PagedOperation>,
    body: String,
    imports: BTreeSet<String>,
}

impl ManagerPrinter<'_> {
    fn finish(self, manager: &str) -> GeneratedFile {
        let mut content = String::new();
        let _ = writeln!(
            content,
            "// Code generated by box-gantry {}. DO NOT EDIT.\npackage managers\n",
            env!("CARGO_PKG_VERSION"),
        );
        if !self.imports.is_empty() {
            content.push_str("import (\n");
            for import in &self.imports {
                let _ = writeln!(content, "\t{import:?}");
            }
            content.push_str(")\n");
        }
        content.push('\n');
        content.push_str(self.body.trim_end());
        content.push('\n');
        GeneratedFile {
            path: format!("managers/{manager}.go"),
            content,
        }
    }

    fn manager(&mut self, manager: &str, op_indices: &[usize]) -> Result<(), BackendError> {
        let type_name = format!("{}Manager", pascal(manager));
        let _ = writeln!(
            self.body,
            "// {type_name} groups the {manager:?} operations.\ntype {type_name} struct{{}}\n"
        );
        for &index in op_indices {
            let op = self.analysis.program.operations[index].clone();
            self.operation(&type_name, &op)?;
            if let Some(paged) = self.paged.get(&index).copied() {
                self.paginator(&type_name, &op, paged)?;
            }
        }
        Ok(())
    }

    fn method_name(&self, op: &ir::Operation) -> String {
        let mut name = pascal(op.name.as_str());
        if let Some(variation) = &op.variation {
            name.push_str(&pascal(variation.as_str()));
        }
        // Operations from versioned documents carry the version in the
        // method name so base and versioned surfaces never collide
        // (FR-7.5).
        if op.api_version != self.base_version
            && let Some(version) = &op.api_version
        {
            name.push_str(&constant(&version.0));
        }
        name
    }

    fn operation(&mut self, manager_type: &str, op: &ir::Operation) -> Result<(), BackendError> {
        let context = format!("operation {}/{}", op.manager.as_str(), op.name.as_str());
        let method = self.method_name(op);
        self.imports.insert("context".to_string());
        self.imports
            .insert("boxgantry.invalid/boxsdk/gantryruntime".to_string());

        // Signature: ctx, path params, required query/header params,
        // body, then an options struct for the optional params.
        let mut args = vec!["ctx context.Context".to_string()];
        let mut optional: Vec<&ir::Param> = Vec::new();
        let mut required: Vec<&ir::Param> = Vec::new();
        for param in &op.params {
            if matches!(param.ty, ir::Type::Optional(_)) {
                optional.push(param);
            } else {
                required.push(param);
            }
        }
        for param in &required {
            let ty = self.go_type(&param.ty)?;
            args.push(format!("{} {ty}", arg_name(param)));
        }
        if let Some(body) = &op.request {
            let inner = unwrap_optionality(&body.ty);
            let ty = self.go_type(inner)?;
            let expr = if nilable(&ty) { ty } else { format!("*{ty}") };
            args.push(format!("body {expr}"));
        }
        let options_type = format!("{method}Options");
        if !optional.is_empty() {
            args.push(format!("opts *{options_type}"));
        }

        let (return_ty, ok_expr) = match &op.response {
            ir::ResponseShape::None => (String::new(), None),
            ir::ResponseShape::Json(ty) => {
                let inner = unwrap_optionality(ty);
                let go = self.go_type(inner)?;
                if nilable(&go) {
                    (go.clone(), Some(go))
                } else {
                    (format!("*{go}"), Some(format!("*{go}")))
                }
            }
            ir::ResponseShape::Binary => {
                self.imports.insert("io".to_string());
                ("io.Reader".to_string(), None)
            }
            ir::ResponseShape::Text | ir::ResponseShape::Redirect => ("string".to_string(), None),
        };
        let signature_ret = if return_ty.is_empty() {
            "error".to_string()
        } else {
            format!("({return_ty}, error)")
        };

        // Options struct first (deterministically before the method).
        if !optional.is_empty() {
            let mut rows: Vec<(String, String)> = Vec::new();
            for param in &optional {
                let inner = unwrap_optionality(&param.ty);
                let go = self.go_type(inner)?;
                let expr = if nilable(&go) { go } else { format!("*{go}") };
                rows.push((pascal(param.name.as_str()), expr));
            }
            let width = rows.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
            let _ = writeln!(
                self.body,
                "// {options_type} carries the optional parameters.\ntype {options_type} struct {{"
            );
            for (name, ty) in rows {
                let _ = writeln!(self.body, "\t{name:<width$} {ty}");
            }
            self.body.push_str("}\n\n");
        }

        let _ = writeln!(
            self.body,
            "func (m *{manager_type}) {method}({}) {signature_ret} {{",
            args.join(", ")
        );
        self.url_and_request(op, &context)?;
        self.apply_params(&required, false, &context)?;
        if !optional.is_empty() {
            self.body.push_str("\tif opts != nil {\n");
            self.apply_params(&optional, true, &context)?;
            self.body.push_str("\t}\n");
        }
        self.request_body(op, &context)?;

        // Failure return matching the signature (D-003 (T, error)).
        let fail = if return_ty.is_empty() {
            "err".to_string()
        } else if return_ty.starts_with("io.Reader")
            || return_ty.starts_with("[]")
            || return_ty.starts_with("map[")
            || return_ty == "any"
            || return_ty.starts_with('*')
        {
            "nil, err".to_string()
        } else {
            "\"\", err".to_string()
        };
        let _ = writeln!(
            self.body,
            "\tresp, err := gantryruntime.Fetch(ctx, req)\n\tif err != nil {{\n\t\treturn {fail}\n\t}}"
        );

        match &op.response {
            ir::ResponseShape::None => {
                self.body.push_str("\t_ = resp\n\treturn nil\n}\n\n");
            }
            ir::ResponseShape::Json(_) => {
                self.imports.insert("encoding/json".to_string());
                let ok = ok_expr.expect("json responses carry a type");
                if ok.starts_with('*') {
                    let _ = writeln!(
                        self.body,
                        "\tdata, err := gantryruntime.ResponseBytes(resp)\n\tif err != nil {{\n\t\treturn nil, err\n\t}}\n\
                         \tout := new({})\n\tif err := json.Unmarshal(data, out); err != nil {{\n\t\treturn nil, err\n\t}}\n\
                         \treturn out, nil\n}}\n",
                        ok.trim_start_matches('*')
                    );
                } else {
                    let _ = writeln!(
                        self.body,
                        "\tdata, err := gantryruntime.ResponseBytes(resp)\n\tif err != nil {{\n\t\treturn nil, err\n\t}}\n\
                         \tvar out {ok}\n\tif err := json.Unmarshal(data, &out); err != nil {{\n\t\treturn nil, err\n\t}}\n\
                         \treturn out, nil\n}}\n"
                    );
                }
            }
            ir::ResponseShape::Binary => {
                self.body
                    .push_str("\treturn gantryruntime.ResponseStream(resp), nil\n}\n\n");
            }
            ir::ResponseShape::Text => {
                let _ = writeln!(
                    self.body,
                    "\tdata, err := gantryruntime.ResponseBytes(resp)\n\tif err != nil {{\n\t\treturn \"\", err\n\t}}\n\
                     \treturn string(data), nil\n}}\n"
                );
            }
            ir::ResponseShape::Redirect => {
                self.body.push_str(
                    "\treturn gantryruntime.ResponseHeader(resp, \"Location\"), nil\n}\n\n",
                );
            }
        }
        Ok(())
    }

    /// A `{Method}Paginate` iterator over a paged operation (TR-Go.4,
    /// FR-7.3). It wraps the plain method, threading the cursor and
    /// yielding one element at a time as `iter.Seq2[*Element, error]`
    /// (Go ≥ 1.23). The cursor lives in a *copy* of the caller's options
    /// so pagination never mutates the caller's struct.
    fn paginator(
        &mut self,
        manager_type: &str,
        op: &ir::Operation,
        paged: &PagedOperation,
    ) -> Result<(), BackendError> {
        let context = format!("paginate {}/{}", op.manager.as_str(), op.name.as_str());
        let method = self.method_name(op);
        self.imports.insert("iter".to_string());

        // Rebuild the plain method's signature prefix (ctx, required
        // args, body) and the matching forwarded call arguments.
        let mut sig = vec!["ctx context.Context".to_string()];
        let mut call = vec!["ctx".to_string()];
        for param in op
            .params
            .iter()
            .filter(|p| !matches!(p.ty, ir::Type::Optional(_)))
        {
            sig.push(format!("{} {}", arg_name(param), self.go_type(&param.ty)?));
            call.push(arg_name(param));
        }
        if let Some(body) = &op.request {
            let inner = unwrap_optionality(&body.ty);
            let ty = self.go_type(inner)?;
            let expr = if nilable(&ty) { ty } else { format!("*{ty}") };
            sig.push(format!("body {expr}"));
            call.push("body".to_string());
        }
        // Paged operations always have an options struct: the cursor
        // parameter is itself optional.
        let options_type = format!("{method}Options");
        sig.push(format!("opts *{options_type}"));
        call.push("&o".to_string());

        let element_go = self.go_type(&paged.element)?;
        let cursor_field = pascal(&paged.param_wire);
        let entries_field = self.field_go_name(op, &paged.entries_wire, &context)?;
        let response_cursor = self.field_go_name(op, &paged.cursor_wire, &context)?;

        // The request cursor param and the response cursor field may
        // disagree in type (e.g. DevicePinners: string marker param,
        // int64 next_marker). Convert explicitly rather than emit a
        // type-mismatched assignment.
        let param_ty = op
            .params
            .iter()
            .find(|p| p.location == ir::ParamLocation::Query && p.wire_name == paged.param_wire)
            .map(|p| unwrap_optionality(&p.ty).clone())
            .expect("detection required the cursor query parameter");
        let response_ty = self.field_ir_type(op, &paged.cursor_wire, &context)?;

        let _ = writeln!(
            self.body,
            "func (m *{manager_type}) {method}Paginate({sig}) iter.Seq2[*{element_go}, error] {{",
            sig = sig.join(", "),
        );
        let _ = writeln!(
            self.body,
            "\treturn func(yield func(*{element_go}, error) bool) {{"
        );
        let _ = writeln!(self.body, "\t\tvar o {options_type}");
        self.body
            .push_str("\t\tif opts != nil {\n\t\t\to = *opts\n\t\t}\n");

        match paged.style {
            PageStyle::Marker => {
                if !matches!(param_ty, ir::Type::String) {
                    return Err(BackendError {
                        context,
                        detail: format!("marker cursor parameter is {param_ty:?}, not a string"),
                    });
                }
                // Convert the response cursor to the string the request
                // parameter expects; terminate on an absent cursor.
                let (guard_extra, next_expr) = match response_ty {
                    ir::Type::String => (
                        format!(" || *page.{response_cursor} == \"\""),
                        format!("*page.{response_cursor}"),
                    ),
                    ir::Type::Int64 => {
                        self.imports.insert("strconv".to_string());
                        (
                            String::new(),
                            format!("strconv.FormatInt(*page.{response_cursor}, 10)"),
                        )
                    }
                    other @ (ir::Type::Bool
                    | ir::Type::Float64
                    | ir::Type::Date
                    | ir::Type::DateTime
                    | ir::Type::Binary
                    | ir::Type::JsonValue
                    | ir::Type::List(_)
                    | ir::Type::Map(_)
                    | ir::Type::Decl(_)
                    | ir::Type::Optional(_)
                    | ir::Type::Nullable(_)) => {
                        return Err(BackendError {
                            context,
                            detail: format!("marker cursor field is {other:?}"),
                        });
                    }
                };
                let _ = writeln!(
                    self.body,
                    "\t\tfor {{\n\
                     \t\t\tpage, err := m.{method}({call})\n\
                     \t\t\tif err != nil {{\n\t\t\t\tyield(nil, err)\n\t\t\t\treturn\n\t\t\t}}\n\
                     \t\t\tfor i := range page.{entries_field} {{\n\
                     \t\t\t\tif !yield(&page.{entries_field}[i], nil) {{\n\t\t\t\t\treturn\n\t\t\t\t}}\n\t\t\t}}\n\
                     \t\t\tif page.{response_cursor} == nil{guard_extra} {{\n\t\t\t\treturn\n\t\t\t}}\n\
                     \t\t\tnext := {next_expr}\n\t\t\to.{cursor_field} = &next\n\t\t}}",
                    call = call.join(", "),
                );
            }
            PageStyle::Offset => {
                if !matches!(param_ty, ir::Type::Int64) {
                    return Err(BackendError {
                        context,
                        detail: format!("offset cursor parameter is {param_ty:?}, not int64"),
                    });
                }
                let _ = writeln!(
                    self.body,
                    "\t\tvar offset int64\n\t\tif o.{cursor_field} != nil {{\n\t\t\toffset = *o.{cursor_field}\n\t\t}}\n\
                     \t\tfor {{\n\
                     \t\t\to.{cursor_field} = &offset\n\
                     \t\t\tpage, err := m.{method}({call})\n\
                     \t\t\tif err != nil {{\n\t\t\t\tyield(nil, err)\n\t\t\t\treturn\n\t\t\t}}\n\
                     \t\t\tfor i := range page.{entries_field} {{\n\
                     \t\t\t\tif !yield(&page.{entries_field}[i], nil) {{\n\t\t\t\t\treturn\n\t\t\t\t}}\n\t\t\t}}\n\
                     \t\t\tif len(page.{entries_field}) == 0 {{\n\t\t\t\treturn\n\t\t\t}}\n\
                     \t\t\toffset += int64(len(page.{entries_field}))\n\t\t}}",
                    call = call.join(", "),
                );
            }
        }
        self.body.push_str("\t}\n}\n\n");
        Ok(())
    }

    /// The Go field name for a response envelope's wire field, resolved
    /// through the operation's response declaration.
    fn field_go_name(
        &self,
        op: &ir::Operation,
        wire: &str,
        context: &str,
    ) -> Result<String, BackendError> {
        let ir::ResponseShape::Json(ty) = &op.response else {
            return Err(BackendError {
                context: context.to_string(),
                detail: "paged operation without a JSON response".into(),
            });
        };
        let mut current = ty;
        let decl_id = loop {
            match current {
                ir::Type::Optional(inner) | ir::Type::Nullable(inner) => current = inner,
                ir::Type::Decl(id) => break *id,
                ir::Type::Bool
                | ir::Type::Int64
                | ir::Type::Float64
                | ir::Type::String
                | ir::Type::Date
                | ir::Type::DateTime
                | ir::Type::Binary
                | ir::Type::JsonValue
                | ir::Type::List(_)
                | ir::Type::Map(_) => {
                    return Err(BackendError {
                        context: context.to_string(),
                        detail: "paged response is not a declaration".into(),
                    });
                }
            }
        };
        let ir::DeclKind::Struct(s) = &self.analysis.program.decl(decl_id).kind else {
            return Err(BackendError {
                context: context.to_string(),
                detail: "paged response is not a struct".into(),
            });
        };
        s.fields
            .iter()
            .find(|f| f.wire_name == wire)
            .map(|f| pascal(f.name.as_str()))
            .ok_or_else(|| BackendError {
                context: context.to_string(),
                detail: format!("paged response has no {wire:?} field"),
            })
    }

    /// The unwrapped IR type of a response envelope's wire field.
    fn field_ir_type(
        &self,
        op: &ir::Operation,
        wire: &str,
        context: &str,
    ) -> Result<ir::Type, BackendError> {
        let ir::ResponseShape::Json(ty) = &op.response else {
            return Err(BackendError {
                context: context.to_string(),
                detail: "paged operation without a JSON response".into(),
            });
        };
        let mut current = ty;
        let decl_id = loop {
            match current {
                ir::Type::Optional(inner) | ir::Type::Nullable(inner) => current = inner,
                ir::Type::Decl(id) => break *id,
                ir::Type::Bool
                | ir::Type::Int64
                | ir::Type::Float64
                | ir::Type::String
                | ir::Type::Date
                | ir::Type::DateTime
                | ir::Type::Binary
                | ir::Type::JsonValue
                | ir::Type::List(_)
                | ir::Type::Map(_) => {
                    return Err(BackendError {
                        context: context.to_string(),
                        detail: "paged response is not a declaration".into(),
                    });
                }
            }
        };
        let ir::DeclKind::Struct(s) = &self.analysis.program.decl(decl_id).kind else {
            return Err(BackendError {
                context: context.to_string(),
                detail: "paged response is not a struct".into(),
            });
        };
        s.fields
            .iter()
            .find(|f| f.wire_name == wire)
            .map(|f| unwrap_optionality(&f.ty).clone())
            .ok_or_else(|| BackendError {
                context: context.to_string(),
                detail: format!("paged response has no {wire:?} field"),
            })
    }

    /// URL built from structured segments + the D-106 base-URL class.
    fn url_and_request(&mut self, op: &ir::Operation, context: &str) -> Result<(), BackendError> {
        let base = match op.base_url {
            ir::BaseUrl::Api => "api",
            ir::BaseUrl::ApiRoot => "api_root",
            ir::BaseUrl::Upload => "upload",
            ir::BaseUrl::UploadSession => "upload_session",
            ir::BaseUrl::OAuthAuthorize => "oauth_authorize",
            ir::BaseUrl::Download => "download",
        };
        let mut expr = format!("gantryruntime.BaseUrl({base:?})");
        for segment in &op.path {
            match segment {
                ir::PathSegment::Literal(text) => {
                    let _ = write!(expr, "+\"/{text}\"");
                }
                ir::PathSegment::Parameter(name) => {
                    self.imports.insert("net/url".to_string());
                    let value = self.path_value(op, name, context)?;
                    let _ = write!(expr, "+\"/\"+url.PathEscape({value})");
                }
                ir::PathSegment::Composite(parts) => {
                    let _ = write!(expr, "+\"/\"");
                    for part in parts {
                        match part {
                            ir::PathPart::Literal(text) => {
                                let _ = write!(expr, "+{text:?}");
                            }
                            ir::PathPart::Parameter(name) => {
                                self.imports.insert("net/url".to_string());
                                let value = self.path_value(op, name, context)?;
                                let _ = write!(expr, "+url.PathEscape({value})");
                            }
                        }
                    }
                }
            }
        }
        let method = match op.method {
            ir::HttpMethod::Get => "GET",
            ir::HttpMethod::Put => "PUT",
            ir::HttpMethod::Post => "POST",
            ir::HttpMethod::Delete => "DELETE",
            ir::HttpMethod::Options => "OPTIONS",
            ir::HttpMethod::Head => "HEAD",
            ir::HttpMethod::Patch => "PATCH",
            ir::HttpMethod::Trace => "TRACE",
        };
        let _ = writeln!(
            self.body,
            "\treq := gantryruntime.NewRequest({method:?}, {expr})"
        );
        Ok(())
    }

    /// The Go expression converting a path parameter to its string value.
    fn path_value(
        &mut self,
        op: &ir::Operation,
        name: &ir::Identifier,
        context: &str,
    ) -> Result<String, BackendError> {
        let param = op
            .params
            .iter()
            .find(|p| p.location == ir::ParamLocation::Path && p.name == *name)
            .expect("ingestion validated every path placeholder");
        self.string_value(&arg_name(param), &param.ty, context)
    }

    /// Emit WithQuery/WithHeader calls. `deref` when values come from the
    /// options struct (pointers / nil-checked).
    fn apply_params(
        &mut self,
        params: &[&ir::Param],
        from_options: bool,
        context: &str,
    ) -> Result<(), BackendError> {
        for param in params {
            let call = match param.location {
                ir::ParamLocation::Query => "WithQuery",
                ir::ParamLocation::Header => "WithHeader",
                ir::ParamLocation::Path => continue,
            };
            let indent = if from_options { "\t\t" } else { "\t" };
            if from_options {
                let field = format!("opts.{}", pascal(param.name.as_str()));
                let inner = unwrap_optionality(&param.ty);
                let go = self.go_type(inner)?;
                let access = if nilable(&go) {
                    field.clone()
                } else {
                    format!("(*{field})")
                };
                let guard = format!("{field} != nil");
                let value = self.string_value(&access, inner, context)?;
                let _ = writeln!(
                    self.body,
                    "{indent}if {guard} {{\n{indent}\treq = gantryruntime.{call}(req, {wire:?}, {value})\n{indent}}}",
                    wire = param.wire_name,
                );
            } else {
                let value = self.string_value(&arg_name(param), &param.ty, context)?;
                let _ = writeln!(
                    self.body,
                    "{indent}req = gantryruntime.{call}(req, {wire:?}, {value})",
                    wire = param.wire_name,
                );
            }
        }
        Ok(())
    }

    fn request_body(&mut self, op: &ir::Operation, context: &str) -> Result<(), BackendError> {
        let Some(body) = &op.request else {
            return Ok(());
        };
        match body.media {
            ir::RequestMedia::Json | ir::RequestMedia::JsonPatch => {
                self.imports.insert("encoding/json".to_string());
                let _ = writeln!(
                    self.body,
                    "\tpayload, err := json.Marshal(body)\n\tif err != nil {{\n\t\treturn {}\n\t}}\n\
                     \treq = gantryruntime.WithJsonBody(req, payload)",
                    self.zero_and_err(op)
                );
            }
            ir::RequestMedia::OctetStream => {
                self.body
                    .push_str("\treq = gantryruntime.WithStreamBody(req, body, \"application/octet-stream\")\n");
            }
            ir::RequestMedia::Multipart => {
                // The Box multipart shape: an `attributes` JSON part plus
                // a binary `file` part (G-7); the contract owns assembly.
                self.imports.insert("encoding/json".to_string());
                let _ = writeln!(
                    self.body,
                    "\tattributes, err := json.Marshal(body)\n\tif err != nil {{\n\t\treturn {}\n\t}}\n\
                     \treq = gantryruntime.WithMultipartBody(req, attributes, \"file\", nil)",
                    self.zero_and_err(op)
                );
            }
            ir::RequestMedia::UrlEncoded => {
                let ir::Type::Decl(id) = unwrap_optionality(&body.ty) else {
                    return Err(BackendError {
                        context: context.to_string(),
                        detail: "url-encoded body is not a declared struct".into(),
                    });
                };
                let decl = self.analysis.program.decl(*id);
                let ir::DeclKind::Struct(s) = &decl.kind else {
                    return Err(BackendError {
                        context: context.to_string(),
                        detail: "url-encoded body declaration is not a struct".into(),
                    });
                };
                self.imports.insert("net/url".to_string());
                self.body.push_str("\tform := url.Values{}\n");
                for form_field in &s.fields {
                    let field = format!("body.{}", pascal(form_field.name.as_str()));
                    let inner = unwrap_optionality(&form_field.ty);
                    let go = self.go_type(inner)?;
                    let nilable = go.starts_with("[]") || go.starts_with("map[") || go == "any";
                    let optionalish =
                        matches!(form_field.ty, ir::Type::Optional(_) | ir::Type::Nullable(_));
                    if optionalish && !nilable {
                        let value = self.string_value(&format!("(*{field})"), inner, context)?;
                        let _ = writeln!(
                            self.body,
                            "\tif {field} != nil {{\n\t\tform.Set({wire:?}, {value})\n\t}}",
                            wire = form_field.wire_name,
                        );
                    } else if optionalish {
                        let value = self.string_value(&field, inner, context)?;
                        let _ = writeln!(
                            self.body,
                            "\tif {field} != nil {{\n\t\tform.Set({wire:?}, {value})\n\t}}",
                            wire = form_field.wire_name,
                        );
                    } else {
                        let value = self.string_value(&field, inner, context)?;
                        let _ = writeln!(
                            self.body,
                            "\tform.Set({wire:?}, {value})",
                            wire = form_field.wire_name,
                        );
                    }
                }
                self.body
                    .push_str("\treq = gantryruntime.WithFormBody(req, []byte(form.Encode()))\n");
            }
        }
        Ok(())
    }

    /// The zero-value + err return matching the method signature.
    fn zero_and_err(&self, op: &ir::Operation) -> &'static str {
        match &op.response {
            ir::ResponseShape::None => "err",
            ir::ResponseShape::Json(_) | ir::ResponseShape::Binary => "nil, err",
            ir::ResponseShape::Text | ir::ResponseShape::Redirect => "\"\", err",
        }
    }

    /// A Go expression turning `expr` (already non-optional) into the
    /// string a query/header/path slot needs.
    fn string_value(
        &mut self,
        expr: &str,
        ty: &ir::Type,
        context: &str,
    ) -> Result<String, BackendError> {
        match ty {
            ir::Type::String => Ok(expr.to_string()),
            ir::Type::Bool => {
                self.imports.insert("strconv".to_string());
                Ok(format!("strconv.FormatBool({expr})"))
            }
            ir::Type::Int64 => {
                self.imports.insert("strconv".to_string());
                Ok(format!("strconv.FormatInt({expr}, 10)"))
            }
            ir::Type::Float64 => {
                self.imports.insert("strconv".to_string());
                Ok(format!("strconv.FormatFloat({expr}, 'f', -1, 64)"))
            }
            ir::Type::DateTime => {
                self.imports.insert("time".to_string());
                Ok(format!("{expr}.Format(time.RFC3339)"))
            }
            ir::Type::Date => Ok(expr.to_string()),
            ir::Type::List(inner) if self.is_scalar(inner) => {
                // Comma-joined per Box convention, via the generated
                // helpers in managers/helpers.go.
                if matches!(**inner, ir::Type::String) {
                    self.imports.insert("strings".to_string());
                    return Ok(format!("strings.Join({expr}, \",\")"));
                }
                match unwrap_alias(self.analysis.program, inner) {
                    ir::Type::Int64 => Ok(format!("joinInt64({expr})")),
                    ir::Type::Decl(_) => Ok(format!("joinStringLike({expr})")),
                    other @ (ir::Type::Bool
                    | ir::Type::Float64
                    | ir::Type::String
                    | ir::Type::Date
                    | ir::Type::DateTime
                    | ir::Type::Binary
                    | ir::Type::Optional(_)
                    | ir::Type::Nullable(_)
                    | ir::Type::List(_)
                    | ir::Type::Map(_)
                    | ir::Type::JsonValue) => Err(BackendError {
                        context: context.to_string(),
                        detail: format!("no join helper for list of {other:?}"),
                    }),
                }
            }
            ir::Type::Decl(id) => {
                let decl = self.analysis.program.decl(*id);
                match &decl.kind {
                    ir::DeclKind::Enum(_) => Ok(format!("string({expr})")),
                    ir::DeclKind::Alias(inner) => {
                        let inner = inner.clone();
                        self.string_value(expr, &inner, context)
                    }
                    // Complex query values serialize as JSON strings (the
                    // Box `mdfilters` convention).
                    ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) => Ok(self.json_string(expr)),
                }
            }
            ir::Type::List(_) | ir::Type::Map(_) | ir::Type::JsonValue => {
                Ok(self.json_string(expr))
            }
            ir::Type::Optional(_) | ir::Type::Nullable(_) => Err(BackendError {
                context: context.to_string(),
                detail: "optionality must be unwrapped before string conversion".into(),
            }),
            ir::Type::Binary => Err(BackendError {
                context: context.to_string(),
                detail: "binary parameter has no string form".into(),
            }),
        }
    }

    /// JSON-encode a value into a query/header string. `json.Marshal`
    /// cannot fail on generated models (only JSON-representable types),
    /// so the error is structurally ignorable here.
    fn json_string(&mut self, expr: &str) -> String {
        self.imports.insert("encoding/json".to_string());
        format!("func() string {{ data, _ := json.Marshal({expr}); return string(data) }}()")
    }

    /// Scalars convert to query strings directly; everything else is the
    /// JSON-in-query convention.
    fn is_scalar(&self, ty: &ir::Type) -> bool {
        match ty {
            ir::Type::String
            | ir::Type::Bool
            | ir::Type::Int64
            | ir::Type::Float64
            | ir::Type::Date
            | ir::Type::DateTime => true,
            ir::Type::Decl(id) => match &self.analysis.program.decl(*id).kind {
                ir::DeclKind::Enum(_) => true,
                ir::DeclKind::Alias(inner) => self.is_scalar(inner),
                ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) => false,
            },
            ir::Type::Binary
            | ir::Type::JsonValue
            | ir::Type::List(_)
            | ir::Type::Map(_)
            | ir::Type::Optional(_)
            | ir::Type::Nullable(_) => false,
        }
    }

    /// The package-qualified Go type for use in the `managers` package.
    fn go_type(&mut self, ty: &ir::Type) -> Result<String, BackendError> {
        match ty {
            ir::Type::Bool => Ok("bool".into()),
            ir::Type::Int64 => Ok("int64".into()),
            ir::Type::Float64 => Ok("float64".into()),
            ir::Type::String | ir::Type::Date => Ok("string".into()),
            ir::Type::DateTime => {
                self.imports.insert("time".to_string());
                Ok("time.Time".into())
            }
            ir::Type::Binary => {
                self.imports.insert("io".to_string());
                Ok("io.Reader".into())
            }
            ir::Type::JsonValue => Ok("any".into()),
            ir::Type::List(inner) => Ok(format!("[]{}", self.go_type(inner)?)),
            ir::Type::Map(inner) => Ok(format!("map[string]{}", self.go_type(inner)?)),
            ir::Type::Decl(id) => Ok(self.qualified_decl(*id)),
            ir::Type::Optional(inner) | ir::Type::Nullable(inner) => {
                let go = self.go_type(inner)?;
                if nilable(&go) {
                    Ok(go)
                } else {
                    Ok(format!("*{go}"))
                }
            }
        }
    }

    fn qualified_decl(&mut self, id: ir::DeclId) -> String {
        let decl = self.analysis.program.decl(id);
        let segments: Vec<String> = decl
            .module
            .0
            .iter()
            .map(|s| s.as_str().replace('_', "r").to_lowercase())
            .collect();
        let package = segments.last().cloned().unwrap_or_else(|| "schemas".into());
        self.imports
            .insert(format!("boxgantry.invalid/boxsdk/{}", segments.join("/")));
        format!("{package}.{}", decl.name.as_str())
    }
}

/// Go types that are already nilable: pointer-wrapping them is wrong
/// (pointer-to-interface, TR-Go.1 unwrapping).
fn nilable(go: &str) -> bool {
    go.starts_with("[]")
        || go.starts_with("map[")
        || go == "any"
        || go == "io.Reader"
        || go == "json.RawMessage"
}

fn arg_name(param: &ir::Param) -> String {
    let name = camel(param.name.as_str());
    // Go keywords that appear as Box parameter names.
    if matches!(name.as_str(), "type" | "range" | "func" | "map" | "select") {
        format!("{name}_")
    } else {
        name
    }
}

/// The generated helpers every manager file may call.
pub(crate) fn helpers_file() -> GeneratedFile {
    let content = format!(
        "// Code generated by box-gantry {}. DO NOT EDIT.\npackage managers\n\nimport (\n\t\"strconv\"\n\t\"strings\"\n)\n\nfunc joinStringLike[T ~string](values []T) string {{\n\tout := make([]string, len(values))\n\tfor i, v := range values {{\n\t\tout[i] = string(v)\n\t}}\n\treturn strings.Join(out, \",\")\n}}\n\nfunc joinInt64(values []int64) string {{\n\tout := make([]string, len(values))\n\tfor i, v := range values {{\n\t\tout[i] = strconv.FormatInt(v, 10)\n\t}}\n\treturn strings.Join(out, \",\")\n}}\n",
        env!("CARGO_PKG_VERSION"),
    );
    GeneratedFile {
        path: "managers/helpers.go".to_string(),
        content,
    }
}

/// Resolve through alias declarations to the underlying type.
fn unwrap_alias<'p>(program: &'p ir::Program, ty: &'p ir::Type) -> &'p ir::Type {
    if let ir::Type::Decl(id) = ty
        && let ir::DeclKind::Alias(inner) = &program.decl(*id).kind
    {
        return unwrap_alias(program, inner);
    }
    ty
}

fn unwrap_optionality(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap_optionality(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}
