//! Model generation: IR declarations → Go source files.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::{constant, pascal};
use gantry_sema::Analysis;

use crate::managers::dedupe;
use crate::{MODULE, RETRACTIONS, SERIALIZATION_IMPORT};

/// One generated file, path relative to the SDK root.
#[derive(Debug)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Generate the model packages for every module of the program:
/// `schemas/` for the base document, `schemas/vNrM/` for versioned ones
/// (TR-Go.5), plus the SDK `go.mod`.
pub fn generate_models(analysis: &Analysis<'_>, build: &crate::BuildInfo) -> Vec<GeneratedFile> {
    let program = analysis.program;

    // Group declaration indices by module, preserving program order.
    let mut modules: Vec<(ir::ModulePath, Vec<usize>)> = Vec::new();
    for (index, decl) in program.decls.iter().enumerate() {
        match modules.iter_mut().find(|(path, _)| *path == decl.module) {
            Some((_, indices)) => indices.push(index),
            None => modules.push((decl.module.clone(), vec![index])),
        }
    }

    let mut files = vec![GeneratedFile {
        path: "go.mod".to_string(),
        content: format!("module {MODULE}\n\ngo 1.23\n{RETRACTIONS}"),
    }];
    for (module, indices) in &modules {
        let (dir, package) = module_dir_and_package(module);
        // The module's API version, taken once from its first declaration and
        // shared by every file of the module, so a bucket file's header can
        // never disagree with the catch-all's.
        let api_version = indices
            .first()
            .and_then(|&i| program.decls[i].api_version.as_ref())
            .map_or("unversioned", |v| v.0.as_str());
        let (shared, buckets) = analysis.bucket_decls(indices);

        // The catch-all keeps this module's existing filename, and is
        // emitted even when empty so `schemas/schemas.go` never disappears
        // (a behavioral change every existing hardcoded test path assumes
        // does not happen). Bucket bases are allocated from a pool seeded
        // with it, so a manager tag equal to the package name can't collide.
        let mut used = vec![package.clone()];
        files.push(render_file(
            program,
            &dir,
            &package,
            &package,
            &shared,
            api_version,
            build,
        ));
        for (manager, bucket_indices) in &buckets {
            let base = dedupe(&mut used, manager.clone());
            files.push(render_file(
                program,
                &dir,
                &package,
                &base,
                bucket_indices,
                api_version,
                build,
            ));
        }
    }
    files
}

/// `schemas` → `schemas/schemas.go`; `schemas::v2025_0` →
/// `schemas/v2025r0/v2025r0.go` (the `vNrM` layout, TR-Go.5).
pub(crate) fn module_dir_and_package(module: &ir::ModulePath) -> (String, String) {
    let segments: Vec<String> = module
        .0
        .iter()
        .map(|segment| segment.as_str().replace('_', "r").to_lowercase())
        .collect();
    let package = segments.last().cloned().unwrap_or_else(|| "schemas".into());
    (segments.join("/"), package)
}

struct Printer<'p> {
    program: &'p ir::Program,
    body: String,
    imports: BTreeSet<&'static str>,
}

/// Render one file: `dir`/`package` place it in the module's Go package,
/// `file_base` names the file itself (the package name for the catch-all, a
/// manager base for a bucket — see [`generate_models`]).
fn render_file(
    program: &ir::Program,
    dir: &str,
    package: &str,
    file_base: &str,
    indices: &[usize],
    api_version: &str,
    build: &crate::BuildInfo,
) -> GeneratedFile {
    let mut printer = Printer {
        program,
        body: String::new(),
        imports: BTreeSet::new(),
    };
    for &index in indices {
        printer.decl(&program.decls[index]);
    }

    let mut content = String::new();
    // FR-6.3/NF-7: the generated-file header with engine + spec identity.
    let _ = writeln!(
        content,
        "// Code generated by box-gantry {} (spec {}) for Box API {api_version}. DO NOT EDIT.",
        build.engine, build.spec_fingerprint,
    );
    let _ = writeln!(content, "package {package}\n");
    match printer.imports.len() {
        0 => {}
        1 => {
            let import = printer.imports.iter().next().unwrap();
            let _ = writeln!(content, "import {import:?}\n");
        }
        _ => {
            content.push_str("import (\n");
            for import in &printer.imports {
                let _ = writeln!(content, "\t{import:?}");
            }
            content.push_str(")\n\n");
        }
    }
    content.push_str(printer.body.trim_end());
    // An empty-body file (a bucket-less catch-all) must not end in a stray
    // blank line, or gofmt -l flags it.
    content.truncate(content.trim_end().len());
    content.push('\n');

    GeneratedFile {
        path: format!("{dir}/{file_base}.go"),
        content,
    }
}

impl Printer<'_> {
    fn decl(&mut self, decl: &ir::Decl) {
        let name = decl.name.as_str();
        match &decl.kind {
            ir::DeclKind::Struct(s) => self.struct_decl(name, s),
            ir::DeclKind::Enum(e) => self.enum_decl(name, e),
            ir::DeclKind::Union(u) => self.union_decl(name, u),
            ir::DeclKind::Alias(ty) => {
                let target = self.bare_type(ty);
                let _ = writeln!(self.body, "type {name} = {target}\n");
            }
        }
    }

    fn struct_decl(&mut self, name: &str, s: &ir::StructDecl) {
        if s.fields.is_empty() && s.extra.is_none() {
            let _ = writeln!(self.body, "type {name} struct{{}}\n");
            return;
        }
        // Rows first, then pad: gofmt column-aligns names, types, and
        // tags within a field block (G-17: clean by construction).
        let mut used: Vec<String> = Vec::new();
        let mut rows: Vec<(String, String, String)> = Vec::new();
        for field in &s.fields {
            let (ty, omitempty) = self.field_type(&field.ty);
            let tag = if matches!(ty.as_str(), "io.Reader") {
                // Binary parts travel via multipart assembly, not JSON.
                "`json:\"-\"`".to_string()
            } else if omitempty {
                format!("`json:\"{},omitempty\"`", field.wire_name)
            } else {
                format!("`json:\"{}\"`", field.wire_name)
            };
            let field_name = dedupe(&mut used, pascal(field.name.as_str()));
            rows.push((field_name, ty, tag));
        }
        // D-196: named fields alongside a non-`false` `additionalProperties`.
        // `Extra` is excluded from the struct-tag marshal (`json:"-"`) —
        // `extra_json_methods` below merges it with the named fields by
        // hand instead, so a plain `json.Marshal`/`Unmarshal` on this type
        // would silently ignore it if that method weren't generated. Routed
        // through the same dedup allocator as the named fields: a real field
        // that also normalizes to `Extra` must not collide with it.
        let extra_go_type = s.extra.as_ref().map(|t| self.bare_type(t));
        let extra_field_name = extra_go_type.as_ref().map(|extra_ty| {
            let field_name = dedupe(&mut used, "Extra".to_string());
            rows.push((
                field_name.clone(),
                format!("map[string]{extra_ty}"),
                "`json:\"-\"`".to_string(),
            ));
            field_name
        });
        let name_width = rows.iter().map(|(n, _, _)| n.len()).max().unwrap_or(0);
        let type_width = rows.iter().map(|(_, t, _)| t.len()).max().unwrap_or(0);
        let _ = writeln!(self.body, "type {name} struct {{");
        for (field_name, ty, tag) in rows {
            let _ = writeln!(
                self.body,
                "\t{field_name:<name_width$} {ty:<type_width$} {tag}"
            );
        }
        self.body.push_str("}\n\n");
        if let Some(extra_ty) = extra_go_type {
            let extra_field = extra_field_name.expect("set alongside extra_go_type");
            self.extra_json_methods(name, s, &extra_ty, &extra_field);
        }
    }

    /// `MarshalJSON`/`UnmarshalJSON` for a struct with an open extra bag
    /// (D-196): a package-local `alias` type (same fields, no methods)
    /// lets `encoding/json`'s ordinary struct-tag marshaling handle every
    /// named field — including whatever pointer/`omitempty`/nullable-wrapper
    /// shape `field_type` gave it — without reimplementing that dispatch
    /// here. Only the merge with the extra field is hand-written.
    fn extra_json_methods(
        &mut self,
        name: &str,
        s: &ir::StructDecl,
        extra_ty: &str,
        extra_field: &str,
    ) {
        self.imports.insert("encoding/json");
        let _ = writeln!(
            self.body,
            "func (s {name}) MarshalJSON() ([]byte, error) {{"
        );
        let _ = writeln!(self.body, "\ttype alias {name}");
        self.body
            .push_str("\tnamed, err := json.Marshal(alias(s))\n");
        self.body
            .push_str("\tif err != nil {\n\t\treturn nil, err\n\t}\n");
        self.body.push_str("\tvar m map[string]json.RawMessage\n");
        self.body.push_str(
            "\tif err := json.Unmarshal(named, &m); err != nil {\n\t\treturn nil, err\n\t}\n",
        );
        let _ = writeln!(self.body, "\tfor k, v := range s.{extra_field} {{");
        self.body.push_str("\t\traw, err := json.Marshal(v)\n");
        self.body
            .push_str("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n");
        self.body.push_str("\t\tm[k] = raw\n\t}\n");
        self.body.push_str("\treturn json.Marshal(m)\n}\n\n");

        let _ = writeln!(
            self.body,
            "func (s *{name}) UnmarshalJSON(data []byte) error {{"
        );
        let _ = writeln!(self.body, "\ttype alias {name}");
        self.body.push_str(
            "\tif err := json.Unmarshal(data, (*alias)(s)); err != nil {\n\t\treturn err\n\t}\n",
        );
        self.body.push_str("\tvar m map[string]json.RawMessage\n");
        self.body
            .push_str("\tif err := json.Unmarshal(data, &m); err != nil {\n\t\treturn err\n\t}\n");
        for field in &s.fields {
            let _ = writeln!(self.body, "\tdelete(m, {:?})", field.wire_name);
        }
        let _ = writeln!(
            self.body,
            "\ts.{extra_field} = make(map[string]{extra_ty}, len(m))"
        );
        self.body.push_str("\tfor k, raw := range m {\n");
        let _ = writeln!(self.body, "\t\tvar v {extra_ty}");
        self.body.push_str(
            "\t\tif err := json.Unmarshal(raw, &v); err != nil {\n\t\t\treturn err\n\t\t}\n",
        );
        let _ = writeln!(self.body, "\t\ts.{extra_field}[k] = v");
        self.body.push_str("\t}\n");
        self.body.push_str("\treturn nil\n}\n\n");
    }

    /// Open enums (D-105): a named string type — unknown values
    /// round-trip for free (TR-Go.2: no serializers needed).
    fn enum_decl(&mut self, name: &str, e: &ir::EnumDecl) {
        let _ = writeln!(self.body, "type {name} string\n");
        if e.values.is_empty() {
            return;
        }
        // Constants are package-scoped: prefix with the type name.
        let rows: Vec<(String, &str)> = e
            .values
            .iter()
            .map(|value| (format!("{name}{}", constant(value)), value.as_str()))
            .collect();
        let width = rows.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
        self.body.push_str("const (\n");
        for (constant_name, value) in rows {
            let _ = writeln!(self.body, "\t{constant_name:<width$} {name} = {value:?}");
        }
        self.body.push_str(")\n\n");
    }

    /// Unions (D-012 lineage, TR-Go.2): the only generated serializers.
    /// Discriminated unions dispatch on the tag; unknown tags are
    /// retained raw (open unions, G-10). Structural unions round-trip
    /// raw bytes.
    fn union_decl(&mut self, name: &str, u: &ir::UnionDecl) {
        self.imports.insert("encoding/json");

        // Variant fields need decl-backed types and a discriminator; a
        // union that doesn't fit lowers structurally.
        let discriminated: Option<Vec<(&str, u32)>> = match &u.discriminator {
            Some(_) => u
                .variants
                .iter()
                .map(|v| match (&v.discriminator_value, &v.ty) {
                    (Some(value), ir::Type::Decl(id)) => Some((value.as_str(), id.0)),
                    _ => None,
                })
                .collect(),
            None => None,
        };

        let Some(variants) = discriminated else {
            let _ = writeln!(
                self.body,
                "// {name} is a structural union; callers inspect the raw value.\n\
                 type {name} struct {{\n\tRaw json.RawMessage\n}}\n\n\
                 func (u {name}) MarshalJSON() ([]byte, error) {{\n\
                 \tif u.Raw == nil {{\n\t\treturn []byte(\"null\"), nil\n\t}}\n\
                 \treturn u.Raw, nil\n}}\n\n\
                 func (u *{name}) UnmarshalJSON(data []byte) error {{\n\
                 \tu.Raw = append(u.Raw[:0], data...)\n\treturn nil\n}}\n"
            );
            return;
        };

        let field = u
            .discriminator
            .as_deref()
            .expect("discriminated variants imply a discriminator");
        let rows: Vec<(String, String, &str)> = variants
            .iter()
            .map(|(value, id)| {
                let ty = self.program.decl(ir::DeclId(*id)).name.as_str().to_string();
                (constant(value), ty, *value)
            })
            .collect();

        let name_width = rows
            .iter()
            .map(|(n, _, _)| n.len())
            .max()
            .unwrap_or(0)
            .max("Unknown".len());
        let _ = writeln!(
            self.body,
            "// {name} is a union discriminated on {field:?}; exactly one\n\
             // variant is set. Unknown tags are retained in Unknown (open union)."
        );
        let _ = writeln!(self.body, "type {name} struct {{");
        for (variant, ty, _) in &rows {
            // The type is the last column: no padding after it (gofmt
            // strips trailing whitespace).
            let _ = writeln!(self.body, "\t{variant:<name_width$} *{ty}");
        }
        let _ = writeln!(self.body, "\t{:<name_width$} json.RawMessage", "Unknown");
        self.body.push_str("}\n\n");

        // MarshalJSON: delegate to the variant that is set.
        let _ = writeln!(
            self.body,
            "func (u {name}) MarshalJSON() ([]byte, error) {{"
        );
        self.body.push_str("\tswitch {\n");
        for (variant, _, _) in &rows {
            let _ = writeln!(
                self.body,
                "\tcase u.{variant} != nil:\n\t\treturn json.Marshal(u.{variant})"
            );
        }
        self.body.push_str(
            "\tcase u.Unknown != nil:\n\t\treturn u.Unknown, nil\n\t}\n\treturn []byte(\"null\"), nil\n}\n\n",
        );

        // UnmarshalJSON: dispatch on the discriminator tag.
        let _ = writeln!(
            self.body,
            "func (u *{name}) UnmarshalJSON(data []byte) error {{"
        );
        let _ = writeln!(
            self.body,
            "\tvar probe struct {{\n\t\tTag string `json:{field:?}`\n\t}}\n\
             \tif err := json.Unmarshal(data, &probe); err != nil {{\n\t\treturn err\n\t}}\n\
             \tswitch probe.Tag {{"
        );
        for (variant, ty, value) in &rows {
            let _ = writeln!(
                self.body,
                "\tcase {value:?}:\n\t\tu.{variant} = new({ty})\n\t\treturn json.Unmarshal(data, u.{variant})"
            );
        }
        self.body
            .push_str("\t}\n\tu.Unknown = append(u.Unknown[:0], data...)\n\treturn nil\n}\n\n");
    }

    /// Tri-state mapping (D-110, TR-Go.1). Returns (type expr, omitempty).
    fn field_type(&mut self, ty: &ir::Type) -> (String, bool) {
        match ty {
            ir::Type::Optional(inner) => {
                // Optional<Nullable<T>> → *serialization.Nullable[T] with
                // omitempty: nil = absent, non-nil = sent (null or value)
                // — the full tri-state, resolving BG-1.
                if let ir::Type::Nullable(nullable) = &**inner {
                    (format!("*{}", self.nullable_type(nullable)), true)
                } else {
                    (self.pointer_type(inner), true)
                }
            }
            // Bare Nullable<T> (key always present, value may be null) is
            // the wrapper by value.
            ir::Type::Nullable(inner) => (self.nullable_type(inner), false),
            ir::Type::Bool
            | ir::Type::Int64
            | ir::Type::Float64
            | ir::Type::String
            | ir::Type::Date
            | ir::Type::DateTime
            | ir::Type::Binary
            | ir::Type::JsonValue
            | ir::Type::List(_)
            | ir::Type::Map(_)
            | ir::Type::Decl(_) => (self.bare_type(ty), false),
        }
    }

    /// A pointer for absence — except types that are already nilable
    /// (slices, maps, interfaces), which stay bare (TR-Go.1, G-1).
    fn pointer_type(&mut self, ty: &ir::Type) -> String {
        let bare = self.bare_type(ty);
        if bare.starts_with("[]")
            || bare.starts_with("map[")
            || bare == "any"
            || bare == "io.Reader"
            || bare == "json.RawMessage"
        {
            bare
        } else {
            format!("*{bare}")
        }
    }

    fn bare_type(&mut self, ty: &ir::Type) -> String {
        match ty {
            ir::Type::Bool => "bool".into(),
            ir::Type::Int64 => "int64".into(),
            ir::Type::Float64 => "float64".into(),
            ir::Type::String => "string".into(),
            ir::Type::Date => {
                self.imports.insert(SERIALIZATION_IMPORT);
                "serialization.Date".into()
            }
            ir::Type::DateTime => {
                self.imports.insert("time");
                "time.Time".into()
            }
            ir::Type::Binary => {
                self.imports.insert("io");
                "io.Reader".into()
            }
            ir::Type::JsonValue => "any".into(),
            ir::Type::List(inner) => format!("[]{}", self.bare_type(inner)),
            ir::Type::Map(inner) => format!("map[string]{}", self.bare_type(inner)),
            ir::Type::Decl(id) => self.program.decl(*id).name.as_str().to_string(),
            // A `Nullable` nested inside a container keeps its wrapper (a
            // `[]Nullable[T]` round-trips per-element null). An `Optional`
            // there is a pointer.
            ir::Type::Nullable(inner) => self.nullable_type(inner),
            ir::Type::Optional(inner) => self.pointer_type(inner),
        }
    }

    /// `serialization.Nullable[T]`, importing the package.
    fn nullable_type(&mut self, inner: &ir::Type) -> String {
        self.imports.insert(SERIALIZATION_IMPORT);
        format!("serialization.Nullable[{}]", self.bare_type(inner))
    }
}
