//! Generated round-trip tests (FR-7.8, VR-4).
//!
//! Tests that compile *and pass* under `go test`, exercising the exact
//! serialization semantics VR-4 names:
//!
//! - **optional presence / absence / explicit-null on write** — the
//!   D-110 tri-state through `serialization.Nullable[T]` (the write side
//!   is the guarantee; `encoding/json` collapses read-side null to nil);
//! - **known/unknown discriminators** — the generated union
//!   `Marshal/UnmarshalJSON` dispatch, including unknown-tag retention
//!   (G-10, open unions).
//!
//! Generated from the same IR, so the tests track the real types.

use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::constant;

use crate::models::{GeneratedFile, module_dir_and_package};

/// Generate the round-trip test files: the serialization-package tests
/// plus one `roundtrip_test.go` per module that has discriminated unions.
pub fn generate_tests(analysis: &gantry_sema::Analysis<'_>) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let mut files = vec![GeneratedFile {
        path: "serialization/serialization_test.go".to_string(),
        content: SERIALIZATION_TEST.to_string(),
    }];

    // Group discriminated unions by module, in program order.
    let mut modules: Vec<(ir::ModulePath, Vec<usize>)> = Vec::new();
    for (index, decl) in program.decls.iter().enumerate() {
        let is_discriminated_union = matches!(
            &decl.kind,
            ir::DeclKind::Union(u) if u.discriminator.is_some()
                && u.variants.iter().any(|v| {
                    v.discriminator_value.is_some() && matches!(v.ty, ir::Type::Decl(_))
                })
        );
        if !is_discriminated_union {
            continue;
        }
        match modules.iter_mut().find(|(m, _)| *m == decl.module) {
            Some((_, v)) => v.push(index),
            None => modules.push((decl.module.clone(), vec![index])),
        }
    }

    for (module, indices) in &modules {
        files.push(union_test_file(program, module, indices));
    }
    files
}

fn union_test_file(
    program: &ir::Program,
    module: &ir::ModulePath,
    indices: &[usize],
) -> GeneratedFile {
    let (dir, package) = module_dir_and_package(module);
    let mut body = format!(
        "// Code generated by box-gantry. DO NOT EDIT.\npackage {package}\n\n\
         import (\n\t\"encoding/json\"\n\t\"strings\"\n\t\"testing\"\n)\n\n"
    );

    for &index in indices {
        let decl = &program.decls[index];
        let ir::DeclKind::Union(u) = &decl.kind else {
            continue;
        };
        let discriminator = u.discriminator.as_deref().unwrap_or("type");
        // The first variant that carries both a value and a decl type.
        let Some(value) = u
            .variants
            .iter()
            .find_map(|v| match (&v.discriminator_value, &v.ty) {
                (Some(value), ir::Type::Decl(_)) => Some(value.clone()),
                _ => None,
            })
        else {
            continue;
        };
        let union = decl.name.as_str();
        let variant_field = constant(&value);

        // Known discriminator dispatches to the right variant and the tag
        // survives a re-marshal; an unknown tag is retained raw (VR-4).
        let known_json = format!("{{{discriminator:?}:{value:?}}}");
        let unknown_json = format!("{{{discriminator:?}:\"__gantry_unknown__\"}}");
        let _ = writeln!(
            body,
            "func Test{union}RoundTrip(t *testing.T) {{\n\
             \tvar known {union}\n\
             \tif err := json.Unmarshal([]byte(`{known_json}`), &known); err != nil {{\n\
             \t\tt.Fatalf(\"unmarshal known: %v\", err)\n\t}}\n\
             \tif known.{variant_field} == nil {{\n\
             \t\tt.Fatalf(\"discriminator {value} did not select the {variant_field} variant\")\n\t}}\n\
             \tout, err := json.Marshal(known)\n\tif err != nil {{\n\t\tt.Fatalf(\"marshal: %v\", err)\n\t}}\n\
             \tif !strings.Contains(string(out), {value:?}) {{\n\
             \t\tt.Fatalf(\"re-marshal dropped the discriminator: %s\", out)\n\t}}\n\n\
             \tvar unknown {union}\n\
             \tif err := json.Unmarshal([]byte(`{unknown_json}`), &unknown); err != nil {{\n\
             \t\tt.Fatalf(\"unmarshal unknown: %v\", err)\n\t}}\n\
             \tif unknown.Unknown == nil {{\n\
             \t\tt.Fatalf(\"unknown discriminator was not retained\")\n\t}}\n\
             }}\n"
        );
    }

    // Exactly one trailing newline (gofmt-clean, G-17).
    body.truncate(body.trim_end().len());
    body.push('\n');
    GeneratedFile {
        path: format!("{dir}/roundtrip_test.go"),
        content: body,
    }
}

/// Table tests for the serialization package's tri-state and Date. Static
/// (the behavior is fixed), but real `go test`-run coverage of VR-4's
/// optional presence/absence/explicit-null.
const SERIALIZATION_TEST: &str = r#"// Code generated by box-gantry. DO NOT EDIT.
package serialization

import (
	"encoding/json"
	"testing"
)

type triState struct {
	Field *Nullable[string] `json:"field,omitempty"`
}

func TestNullableWriteTriState(t *testing.T) {
	// The tri-state is expressed on write (Box clear-on-update, BG-1):
	// absent omits the key, Null serializes null, Value serializes it.
	absent, err := json.Marshal(triState{})
	if err != nil {
		t.Fatal(err)
	}
	if string(absent) != "{}" {
		t.Fatalf("absent should omit the key, got %s", absent)
	}

	null, err := json.Marshal(triState{Field: Null[string]()})
	if err != nil {
		t.Fatal(err)
	}
	if string(null) != `{"field":null}` {
		t.Fatalf("null should serialize as null, got %s", null)
	}

	value, err := json.Marshal(triState{Field: Value("x")})
	if err != nil {
		t.Fatal(err)
	}
	if string(value) != `{"field":"x"}` {
		t.Fatalf("value should serialize the value, got %s", value)
	}
}

func TestNullableRead(t *testing.T) {
	// A present value round-trips to a valid Nullable.
	var back triState
	if err := json.Unmarshal([]byte(`{"field":"y"}`), &back); err != nil {
		t.Fatal(err)
	}
	if back.Field == nil || !back.Field.Valid || back.Field.Value != "y" {
		t.Fatalf("value should unmarshal to a valid Nullable with the value")
	}

	// A JSON null does not error. encoding/json collapses null to a nil
	// pointer for pointer fields (UnmarshalJSON is not called), so on read
	// null and absent both surface as nil — acceptable, since the
	// tri-state guarantee is a write-side one.
	back = triState{}
	if err := json.Unmarshal([]byte(`{"field":null}`), &back); err != nil {
		t.Fatal(err)
	}
	if back.Field != nil {
		t.Fatalf("read null should surface as nil (absent-equivalent), got %+v", back.Field)
	}
}

func TestDateRoundTrip(t *testing.T) {
	var d Date
	if err := json.Unmarshal([]byte(`"2026-07-12"`), &d); err != nil {
		t.Fatal(err)
	}
	if d.String() != "2026-07-12" {
		t.Fatalf("date parse: got %s", d.String())
	}
	out, err := json.Marshal(d)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != `"2026-07-12"` {
		t.Fatalf("date marshal: got %s", out)
	}
}
"#;
