//! Reference documentation generation (FR-7.7).
//!
//! Per-manager Markdown plus the auth / pagination / errors cross-cutting
//! guides, generated from the same IR the code is (so the docs describe the
//! real TypeScript surface — class names, method names, parameter and return
//! types — and can't drift from it). Deterministic, like all output (FR-6.2).

use std::collections::HashMap;
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_sema::Analysis;
use gantry_synth::{PagedOperation, detect_pagination};

use crate::GeneratedFile;
use crate::managers::{camel, method_bases, plan_managers};
use crate::models::type_name;

/// Generate `docs/` — an index, one page per manager, and the guides.
pub fn generate_docs(analysis: &Analysis<'_>) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let paged: HashMap<usize, PagedOperation> = detect_pagination(analysis)
        .into_iter()
        .map(|p| (p.operation, p))
        .collect();
    let planned = plan_managers(analysis);

    let mut files = Vec::new();
    files.push(index_page(&planned));
    for (key, indices, name) in &planned {
        files.push(manager_page(
            program,
            &paged,
            key,
            indices,
            &name.class,
            &name.field,
            &name.module,
        ));
    }
    files.push(guide("auth", AUTH_GUIDE));
    files.push(guide("pagination", PAGINATION_GUIDE));
    files.push(guide("errors", ERRORS_GUIDE));
    files
}

fn index_page(planned: &[(&String, &Vec<usize>, crate::managers::ManagerName)]) -> GeneratedFile {
    let mut body = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# Box SDK reference\n\n\
         One resource manager per Box API tag, reached through the single\n\
         `Client` entry point.\n\n## Guides\n\n\
         - [Authentication](auth.md)\n- [Pagination](pagination.md)\n- [Errors](errors.md)\n\n\
         ## Managers\n\n| Manager | Operations |\n|---|---|\n",
    );
    for (_, indices, name) in planned {
        let _ = writeln!(
            body,
            "| [{class}](managers/{module}.md) | {count} |",
            class = name.class,
            module = name.module,
            count = indices.len(),
        );
    }
    GeneratedFile {
        path: "docs/README.md".to_string(),
        content: body,
    }
}

#[allow(clippy::too_many_arguments)]
fn manager_page(
    program: &ir::Program,
    paged: &HashMap<usize, PagedOperation>,
    _key: &str,
    op_indices: &[usize],
    class: &str,
    field: &str,
    module: &str,
) -> GeneratedFile {
    let mut body = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# {class}\n\n\
         Reach these methods through the `{field}` field on `Client`.\n\n",
    );
    // Deduped method bases (shared with the printer), camelCased per method.
    let bases = method_bases(program, op_indices);
    for (pos, &index) in op_indices.iter().enumerate() {
        let op = &program.operations[index];
        let method = camel(&bases[pos]);
        let _ = writeln!(body, "## {method}\n");
        if op.deprecated {
            body.push_str("> **Deprecated.**\n\n");
        }
        let _ = writeln!(
            body,
            "`{http} {path}`\n",
            http = http_method(op.method),
            path = render_path(op),
        );

        if !op.params.is_empty() {
            body.push_str("| Parameter | In | Type | Required |\n|---|---|---|---|\n");
            for param in &op.params {
                let required = !matches!(param.ty, ir::Type::Optional(_));
                let _ = writeln!(
                    body,
                    "| `{name}` | {loc} | `{ty}` | {req} |",
                    name = param.wire_name,
                    loc = param_location(param.location),
                    ty = describe(program, unwrap(&param.ty)),
                    req = if required { "yes" } else { "no" },
                );
            }
            body.push('\n');
        }
        if let Some(req) = &op.request {
            let _ = writeln!(
                body,
                "**Request body** (`{media}`): `{ty}`\n",
                media = request_media(req.media),
                ty = describe(program, unwrap(&req.ty)),
            );
        }
        let _ = writeln!(
            body,
            "**Returns:** {}\n",
            describe_response(program, &op.response)
        );
        if paged.contains_key(&index) {
            let _ = writeln!(
                body,
                "Paginated — `{method}(...)` is an async iterable that yields each \
                 entry across pages (`for await (const item of ...)`), threading \
                 the cursor for you. See the [pagination guide](../pagination.md).\n"
            );
        }
    }
    GeneratedFile {
        path: format!("docs/managers/{module}.md"),
        content: body,
    }
}

fn guide(name: &str, content: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("docs/{name}.md"),
        content: format!("<!-- Generated by box-gantry. DO NOT EDIT. -->\n{content}"),
    }
}

/// A readable TypeScript type name for a type, for docs only — matching the
/// `models` type mapping so the docs describe the real generated surface.
fn describe(program: &ir::Program, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Bool => "boolean".into(),
        ir::Type::Int64 | ir::Type::Float64 => "number".into(),
        // Box dates/date-times are ISO-8601 strings on the wire (TR-TS.2).
        ir::Type::String | ir::Type::Date | ir::Type::DateTime => "string".into(),
        ir::Type::Binary => "Blob".into(),
        ir::Type::JsonValue => "unknown".into(),
        ir::Type::List(inner) => format!("Array<{}>", describe(program, inner)),
        ir::Type::Map(inner) => format!("Record<string, {}>", describe(program, inner)),
        // Match the `models` mapping exactly: declaration names go through
        // `type_name` (global-collision suffixing).
        ir::Type::Decl(id) => type_name(program.decl(*id).name.as_str()),
        ir::Type::Optional(inner) => format!("{} | undefined", describe(program, inner)),
        ir::Type::Nullable(inner) => format!("{} | null", describe(program, inner)),
    }
}

fn describe_response(program: &ir::Program, response: &ir::ResponseShape) -> String {
    match response {
        ir::ResponseShape::None => "`void`".into(),
        ir::ResponseShape::Json(ty) => format!("`{}`", describe(program, unwrap(ty))),
        ir::ResponseShape::Binary => "a binary stream (`runtime.Stream`)".into(),
        ir::ResponseShape::Text => "text (`string`)".into(),
        ir::ResponseShape::Redirect => "a redirect URL (`string`)".into(),
    }
}

fn unwrap(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}

fn render_path(op: &ir::Operation) -> String {
    let mut out = String::new();
    for segment in &op.path {
        out.push('/');
        match segment {
            ir::PathSegment::Literal(text) => out.push_str(text),
            ir::PathSegment::Parameter(name) => {
                let _ = write!(out, "{{{}}}", name.as_str());
            }
            ir::PathSegment::Composite(parts) => {
                for part in parts {
                    match part {
                        ir::PathPart::Literal(text) => out.push_str(text),
                        ir::PathPart::Parameter(name) => {
                            let _ = write!(out, "{{{}}}", name.as_str());
                        }
                    }
                }
            }
        }
    }
    out
}

fn http_method(method: ir::HttpMethod) -> &'static str {
    match method {
        ir::HttpMethod::Get => "GET",
        ir::HttpMethod::Put => "PUT",
        ir::HttpMethod::Post => "POST",
        ir::HttpMethod::Delete => "DELETE",
        ir::HttpMethod::Options => "OPTIONS",
        ir::HttpMethod::Head => "HEAD",
        ir::HttpMethod::Patch => "PATCH",
        ir::HttpMethod::Trace => "TRACE",
    }
}

fn param_location(location: ir::ParamLocation) -> &'static str {
    match location {
        ir::ParamLocation::Path => "path",
        ir::ParamLocation::Query => "query",
        ir::ParamLocation::Header => "header",
    }
}

fn request_media(media: ir::RequestMedia) -> &'static str {
    match media {
        ir::RequestMedia::Json => "application/json",
        ir::RequestMedia::JsonPatch => "application/json-patch+json",
        ir::RequestMedia::UrlEncoded => "application/x-www-form-urlencoded",
        ir::RequestMedia::Multipart => "multipart/form-data",
        ir::RequestMedia::OctetStream => "application/octet-stream",
    }
}

const AUTH_GUIDE: &str = "# Authentication\n\n\
Build a `Client` from one of the four Box auth flows. Each flow is an `Auth`\n\
the runtime uses to fetch a bearer token; the network layer refreshes on a\n\
`401` and retries once. The flow builders live in the `auth` namespace (JWT on\n\
the Node-only `./jwt` subpath) and are passed straight to `new Client(...)`.\n\n\
## Developer Token\n\n\
A fixed token from the Developer Console, for quick local testing:\n\n\
```ts\n\
import { auth } from '@unofficialbox/box-open-sdk';\n\
const client = new Client(auth.developerToken('DEVELOPER_TOKEN'));\n\
```\n\n\
## Client Credentials Grant (server auth, no key)\n\n\
Set exactly one subject — `enterpriseId` for the service account, or `userId`\n\
to act as a managed user:\n\n\
```ts\n\
import { auth } from '@unofficialbox/box-open-sdk';\n\
const client = new Client(auth.clientCredentials({\n\
  clientId: 'CLIENT_ID',\n\
  clientSecret: 'CLIENT_SECRET',\n\
  enterpriseId: 'ENTERPRISE_ID',\n\
}));\n\
```\n\n\
## JWT (server auth with a signing key)\n\n\
Parses (and if needed decrypts) the RSA key up front, so a bad key fails\n\
loudly at construction. It reaches `node:crypto`, so it is a Node-only leaf\n\
imported from the runtime's `./jwt` entry point and returns a promise:\n\n\
```ts\n\
import { jwtAuth } from '@unofficialbox/box-open-sdk/jwt';\n\
const auth = await jwtAuth({\n\
  clientId: 'CLIENT_ID',\n\
  clientSecret: 'CLIENT_SECRET',\n\
  publicKeyId: 'PUBLIC_KEY_ID',\n\
  privateKeyPem: privateKeyPem, // optionally encrypted; set passphrase\n\
  enterpriseId: 'ENTERPRISE_ID',\n\
});\n\
const client = new Client(auth);\n\
```\n\n\
## OAuth 2.0 (authorization code)\n\n\
Redirect the user to the authorize URL, exchange the returned code, then reuse\n\
the rotated refresh token on later runs (persist it via `onRefresh`):\n\n\
```ts\n\
import { auth } from '@unofficialbox/box-open-sdk';\n\
// later runs: resume from the stored refresh token.\n\
const source = auth.oauth({ clientId: 'CLIENT_ID', clientSecret: 'CLIENT_SECRET' }, storedRefreshToken);\n\
const client = new Client(source);\n\
```\n";

const PAGINATION_GUIDE: &str = "# Pagination\n\n\
Marker- and offset-paginated list operations return an `AsyncIterableIterator`\n\
that yields one entry at a time, threading the cursor for you — the list method\n\
*is* the paginator, so drive it directly with `for await ... of`:\n\n\
```ts\n\
for await (const item of client.folders.listItems(folderId)) {\n\
  // use item\n\
}\n\
```\n\n\
It walks every page until the response has no next cursor (or an empty page, for\n\
offset pagination), and owns a private copy of the options you pass, so your\n\
value is never mutated. The wire cursor (`next_marker` / `offset`, verbatim per\n\
TR-TS.2) is threaded through the options for you.\n";

const ERRORS_GUIDE: &str = "# Errors\n\n\
Methods are `async` and surface failure by throwing — the return type only\n\
describes the success value. A thrown `BoxApiError` is either a transport\n\
failure or a non-2xx response after the network layer's retries (exponential\n\
backoff + jitter, `401` refresh, `Retry-After`). It carries the HTTP `status`\n\
when the failure came with a response, and the underlying `cause` for\n\
transport or decode failures:\n\n\
```ts\n\
import { runtime } from '@unofficialbox/box-open-sdk';\n\
try {\n\
  await client.files.getFileById(fileId);\n\
} catch (err) {\n\
  if (err instanceof runtime.BoxApiError) {\n\
    // err.status (number | undefined), err.cause\n\
  }\n\
}\n\
```\n";
