//! The TypeScript backend (FR-6, TR-TypeScript, D-143).
//!
//! Lowers the verified IR to a self-contained TypeScript package. The type
//! system expresses the IR's shapes almost directly, so the model layer is a
//! near-structural map: structs → `interface`s, the tri-state → `?:`/`| null`
//! (no wrapper type, TR-TS.2), `oneOf` → discriminated unions and open enums →
//! string-literal unions widened with `(string & {})` (TR-TS.1).
//!
//! The verification gate is the TypeScript 7 native compiler: `tsc --noEmit`
//! under `strict` (VR-1.5), the TS analogue of `go build`/`cargo check`.
//!
//! This slice emits the model layer + the package scaffold (`package.json`,
//! `tsconfig.json`, provenance). Not yet emitted (later M6 slices): the
//! `Promise`-based managers/client, the `fetch` runtime, docs, and tests.

mod models;

pub use models::generate_models;

/// One generated file, path relative to the SDK package root.
#[derive(Debug)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Provenance stamped into the generated SDK for traceability (NF-7): the
/// engine version that produced it and the fingerprint of the input specs.
#[derive(Debug, Clone)]
pub struct BuildInfo {
    pub engine: String,
    pub spec_fingerprint: String,
}

impl BuildInfo {
    pub fn new(spec_fingerprint: impl Into<String>) -> Self {
        Self {
            engine: env!("CARGO_PKG_VERSION").to_string(),
            spec_fingerprint: spec_fingerprint.into(),
        }
    }
}

/// Generate the SDK package tree for a verified program, stamped with the build
/// provenance (NF-7). The output is a self-contained TypeScript package that
/// `tsc --noEmit` type-checks clean under `strict` (VR-1.5).
///
/// Takes the manifest so synthesis keys off capability axes, never the language
/// name (FR-4.2); this slice reads only `manifest.key`.
pub fn generate(
    analysis: &gantry_sema::Analysis<'_>,
    manifest: &gantry_manifest::CapabilityManifest,
    build: &BuildInfo,
) -> Vec<GeneratedFile> {
    let mut files = vec![
        GeneratedFile {
            path: "package.json".to_string(),
            content: package_json(),
        },
        GeneratedFile {
            path: "tsconfig.json".to_string(),
            content: TSCONFIG.to_string(),
        },
        GeneratedFile {
            path: "src/buildinfo.ts".to_string(),
            content: buildinfo_ts(manifest, build),
        },
        GeneratedFile {
            path: "src/index.ts".to_string(),
            content: "// Code generated by box-gantry. DO NOT EDIT.\n\n\
                      export * as models from './models/index.js';\n\
                      export * as buildinfo from './buildinfo.js';\n"
                .to_string(),
        },
    ];
    files.extend(generate_models(analysis, build));
    files.sort_by(|a, b| a.path.cmp(&b.path));
    files
}

/// The generated package manifest. `type: module` (ESM, TR-TS.4); no runtime
/// dependencies yet (the model layer is pure types).
fn package_json() -> String {
    "{\n\
     \x20 \"name\": \"box-sdk\",\n\
     \x20 \"version\": \"0.1.0\",\n\
     \x20 \"description\": \"Generated TypeScript SDK for the Box API.\",\n\
     \x20 \"type\": \"module\",\n\
     \x20 \"types\": \"./src/index.ts\",\n\
     \x20 \"license\": \"MIT\"\n\
     }\n"
    .to_string()
}

/// The compiler configuration: `strict` + `noEmit` (VR-1.5), NodeNext ESM
/// resolution (so imports carry the `.js` extension), `skipLibCheck` to keep
/// the gate scoped to the generated code.
const TSCONFIG: &str = "{\n\
     \x20 \"compilerOptions\": {\n\
     \x20   \"strict\": true,\n\
     \x20   \"noEmit\": true,\n\
     \x20   \"target\": \"ES2022\",\n\
     \x20   \"module\": \"NodeNext\",\n\
     \x20   \"moduleResolution\": \"NodeNext\",\n\
     \x20   \"declaration\": true,\n\
     \x20   \"skipLibCheck\": true,\n\
     \x20   \"forceConsistentCasingInFileNames\": true\n\
     \x20 },\n\
     \x20 \"include\": [\"src/**/*.ts\"]\n\
     }\n";

/// The `buildinfo` module: exported constants naming the engine, the spec
/// fingerprint, and the target key the SDK was generated from (NF-7).
fn buildinfo_ts(manifest: &gantry_manifest::CapabilityManifest, build: &BuildInfo) -> String {
    format!(
        "// Code generated by box-gantry {engine} (spec {fingerprint}). DO NOT EDIT.\n\
         \n\
         /** The box-gantry engine version that generated this SDK. */\n\
         export const ENGINE = {engine:?};\n\
         /** Fingerprint of the input spec set. */\n\
         export const SPEC_FINGERPRINT = {fingerprint:?};\n\
         /** The target language key (FR-4). */\n\
         export const TARGET = {target:?};\n",
        engine = build.engine,
        fingerprint = build.spec_fingerprint,
        target = manifest.key,
    )
}
