//! Model generation: IR declarations → TypeScript source files.
//!
//! One `.ts` module per IR module (API versions redefine names, and the base
//! and versioned modules share no references, so each is its own module —
//! mirroring D-147). The type system is a near-structural fit for the IR:
//!
//! - struct → `export interface`, with the tri-state mapped straight onto the
//!   type system — absent → `field?: T`, explicit null → `T | null`, so the
//!   absent-vs-null distinction needs no wrapper (TR-TS.2);
//! - open enum → a string-literal union widened with `(string & {})`; closed
//!   enum → the bare literal union (TR-TS.1);
//! - discriminated union → a union of its variant interfaces, each carrying its
//!   own literal discriminator; open unions add a catch-all so an unknown tag is
//!   retained (TR-TS.1);
//! - alias → `export type`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::pascal;
use gantry_sema::Analysis;

use crate::{BuildInfo, GeneratedFile};

/// Generate `src/models/<module>.ts` per IR module plus the `index.ts` barrel.
pub fn generate_models(analysis: &Analysis<'_>, build: &BuildInfo) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let modules = module_names(program);
    // Every declaration's home module and TypeScript name, indexed by
    // `DeclId` (== position in `program.decls`) so type references resolve —
    // and, when they cross a module boundary, produce an `import`.
    let decls: Vec<(String, String)> = program
        .decls
        .iter()
        .map(|d| (modules[&d.module].clone(), type_name(d.name.as_str())))
        .collect();

    // Group declaration indices by module, in program order (stable output).
    let mut grouped: Vec<(ir::ModulePath, Vec<usize>)> = Vec::new();
    for (index, decl) in program.decls.iter().enumerate() {
        match grouped.iter_mut().find(|(m, _)| *m == decl.module) {
            Some((_, v)) => v.push(index),
            None => grouped.push((decl.module.clone(), vec![index])),
        }
    }
    let mut named: Vec<(String, Vec<usize>, Option<&ir::ApiVersion>)> = grouped
        .iter()
        .map(|(m, indices)| {
            let version = indices
                .first()
                .and_then(|&i| program.decls[i].api_version.as_ref());
            (modules[m].clone(), indices.clone(), version)
        })
        .collect();
    named.sort_by(|a, b| a.0.cmp(&b.0));

    let mut files = Vec::new();
    for (name, indices, version) in &named {
        files.push(render_module(
            program, &decls, name, indices, *version, build,
        ));
    }
    // The barrel re-exports each module as a namespace. The version merge
    // (D-190) collapses the versioned schema modules into one `schemas`, so a
    // name shared across API versions is a single `models.schemas.ClientError`.
    let mut index = String::from("// Code generated by box-gantry. DO NOT EDIT.\n\n");
    for (name, _, _) in &named {
        let _ = writeln!(index, "export * as {name} from './{name}.js';");
    }
    files.push(GeneratedFile {
        path: "src/models/index.ts".to_string(),
        content: index,
    });
    files
}

fn render_module(
    program: &ir::Program,
    decls: &[(String, String)],
    module: &str,
    indices: &[usize],
    version: Option<&ir::ApiVersion>,
    build: &BuildInfo,
) -> GeneratedFile {
    let mut printer = Printer {
        program,
        decls,
        module,
        imports: BTreeMap::new(),
        body: String::new(),
    };
    for &index in indices {
        printer.decl(&program.decls[index]);
    }

    let api_version = version.map_or("unversioned", |v| v.0.as_str());
    let mut content = format!(
        "// Code generated by box-gantry {} (spec {}) for Box API {api_version}. DO NOT EDIT.\n\n",
        build.engine, build.spec_fingerprint
    );
    // Cross-module type references, as `import type` (erased at build time).
    for (from, names) in &printer.imports {
        let list = names.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = writeln!(content, "import type {{ {list} }} from './{from}.js';");
    }
    if !printer.imports.is_empty() {
        content.push('\n');
    }
    content.push_str(printer.body.trim_end());
    content.push('\n');

    GeneratedFile {
        path: format!("src/models/{module}.ts"),
        content,
    }
}

struct Printer<'p> {
    program: &'p ir::Program,
    /// `DeclId` → (home module, TypeScript name).
    decls: &'p [(String, String)],
    /// The module currently being rendered (references to it stay bare).
    module: &'p str,
    /// Cross-module references to import: module → the names it provides.
    imports: BTreeMap<String, BTreeSet<String>>,
    body: String,
}

impl Printer<'_> {
    fn decl(&mut self, decl: &ir::Decl) {
        let name = type_name(decl.name.as_str());
        match &decl.kind {
            ir::DeclKind::Struct(s) => self.struct_decl(&name, s),
            ir::DeclKind::Enum(e) => self.enum_decl(&name, e),
            ir::DeclKind::Union(u) => self.union_decl(&name, u),
            ir::DeclKind::Alias(ty) => {
                let target = self.ts_type(ty);
                let _ = writeln!(self.body, "export type {name} = {target};\n");
            }
        }
    }

    fn struct_decl(&mut self, name: &str, s: &ir::StructDecl) {
        if s.fields.is_empty() && s.extra.is_none() {
            // An empty interface is a lint smell; a type alias to an empty
            // object is the tsc-clean equivalent.
            let _ = writeln!(self.body, "export type {name} = Record<string, never>;\n");
            return;
        }
        if s.fields.is_empty() {
            // A pure open map (D-196, no named fields — `GenericSource`'s
            // real shape): nothing to intersect with, just the map itself.
            let extra_ty = self.ts_type(s.extra.as_ref().expect("checked above"));
            let _ = writeln!(
                self.body,
                "export type {name} = Record<string, {extra_ty}>;\n"
            );
            return;
        }
        // D-196: named fields alongside a non-`false` `additionalProperties`.
        // An `interface` with both named properties *and* an index
        // signature forces every named property's type to be assignable to
        // the index signature's value type — a real constraint tsc
        // enforces, and one an arbitrary typed `additionalProperties`
        // wouldn't generally satisfy. Intersecting a plain object type with
        // `Record<string, T>` instead sidesteps that: each half of the
        // intersection keeps its own member types.
        let extra_ty = s.extra.as_ref().map(|t| self.ts_type(t));
        let (keyword, eq) = match extra_ty {
            Some(_) => ("type", "= "),
            None => ("interface", ""),
        };
        let _ = writeln!(self.body, "export {keyword} {name} {eq}{{");
        for field in &s.fields {
            // Peel the tri-state wrappers: an outer `Optional` makes the key
            // optional (`?:`), a `Nullable` widens the value with `| null`.
            let mut ty = &field.ty;
            let mut optional = false;
            let mut nullable = false;
            loop {
                match ty {
                    ir::Type::Optional(inner) => {
                        optional = true;
                        ty = inner;
                    }
                    ir::Type::Nullable(inner) => {
                        nullable = true;
                        ty = inner;
                    }
                    // A non-wrapper type: the field's base type is reached
                    // (enumerated, never wildcarded — NF-1).
                    ir::Type::Bool
                    | ir::Type::Int64
                    | ir::Type::Float64
                    | ir::Type::String
                    | ir::Type::Date
                    | ir::Type::DateTime
                    | ir::Type::Binary
                    | ir::Type::JsonValue
                    | ir::Type::List(_)
                    | ir::Type::Map(_)
                    | ir::Type::Decl(_) => break,
                }
            }
            let base = self.ts_type(ty);
            let key = field_key(&field.wire_name);
            let opt = if optional { "?" } else { "" };
            let null = if nullable { " | null" } else { "" };
            let _ = writeln!(self.body, "  {key}{opt}: {base}{null};");
        }
        match extra_ty {
            Some(extra_ty) => {
                let _ = writeln!(self.body, "}} & Record<string, {extra_ty}>;\n");
            }
            None => self.body.push_str("}\n\n"),
        }
    }

    fn enum_decl(&mut self, name: &str, e: &ir::EnumDecl) {
        if e.values.is_empty() {
            let _ = writeln!(self.body, "export type {name} = string;\n");
            return;
        }
        let mut variants: Vec<String> = e.values.iter().map(|v| format!("{v:?}")).collect();
        // Open enums retain unknown values: widen with `(string & {})`, which
        // keeps literal autocomplete while accepting any string (TR-TS.1).
        if matches!(e.extensibility, ir::Extensibility::Open) {
            variants.push("(string & {})".to_string());
        }
        let _ = writeln!(
            self.body,
            "export type {name} = {};\n",
            variants.join(" | ")
        );
    }

    fn union_decl(&mut self, name: &str, u: &ir::UnionDecl) {
        match discriminated_variants(self.program, u) {
            Some(variants) => {
                // Safe: `discriminated_variants` only returns `Some` when the
                // union has a discriminator.
                let disc = field_key(u.discriminator.as_deref().unwrap());
                let mut members: Vec<String> = variants
                    .iter()
                    .map(|(id, value)| {
                        // Pin the discriminator to its literal via an
                        // intersection, so the union narrows even though the
                        // variant's own discriminator field is an open
                        // (string-widened) enum (TR-TS.1).
                        format!("({} & {{ {disc}: {value:?} }})", self.decl_ref(*id))
                    })
                    .collect();
                // Open unions keep an unrecognized tag: the discriminator is
                // present but matches no known literal (TR-TS.1). Requiring the
                // key keeps the catch-all from swallowing `{}`; closed unions
                // reject an unknown tag structurally.
                if matches!(u.extensibility, ir::Extensibility::Open) {
                    members.push(format!("{{ {disc}: string; [key: string]: unknown }}"));
                }
                let _ = writeln!(self.body, "export type {name} = {};\n", members.join(" | "));
            }
            // A union without a clean discriminator lowers to `unknown` — the
            // caller inspects it (mirrors the structural fallback in Go/Rust).
            None => {
                let _ = writeln!(self.body, "export type {name} = unknown;\n");
            }
        }
    }

    /// A TypeScript type expression for an IR type, recording any cross-module
    /// declaration reference as an import.
    fn ts_type(&mut self, ty: &ir::Type) -> String {
        match ty {
            ir::Type::Bool => "boolean".into(),
            ir::Type::Int64 => "number".into(),
            ir::Type::Float64 => "number".into(),
            ir::Type::String => "string".into(),
            // Box dates/date-times are ISO-8601 strings on the wire.
            ir::Type::Date => "string".into(),
            ir::Type::DateTime => "string".into(),
            ir::Type::Binary => "Blob".into(),
            ir::Type::JsonValue => "unknown".into(),
            ir::Type::List(inner) => format!("Array<{}>", self.ts_type(inner)),
            ir::Type::Map(inner) => format!("Record<string, {}>", self.ts_type(inner)),
            ir::Type::Decl(id) => self.decl_ref(*id),
            ir::Type::Optional(inner) => format!("{} | undefined", self.ts_type(inner)),
            ir::Type::Nullable(inner) => format!("{} | null", self.ts_type(inner)),
        }
    }

    /// Reference a declaration by its TypeScript name, importing it when it
    /// lives in another module.
    fn decl_ref(&mut self, id: ir::DeclId) -> String {
        let (home, name) = &self.decls[id.0 as usize];
        if home != self.module {
            self.imports
                .entry(home.clone())
                .or_default()
                .insert(name.clone());
        }
        name.clone()
    }
}

/// The `(declaration id, discriminator value)` pairs a discriminated union
/// lowers to — every variant a tagged, discriminator-carrying struct — or
/// `None` when it lowers to the structural `unknown` fallback (no
/// discriminator, or any variant that isn't a discriminator-carrying
/// declaration). The literal value lets each union member pin its tag so the
/// union narrows.
pub(crate) fn discriminated_variants(
    program: &ir::Program,
    u: &ir::UnionDecl,
) -> Option<Vec<(ir::DeclId, String)>> {
    let discriminator = u.discriminator.as_deref()?;
    u.variants
        .iter()
        .map(|v| match (&v.discriminator_value, &v.ty) {
            (Some(value), ir::Type::Decl(id))
                if decl_carries_field(program, *id, discriminator) =>
            {
                Some((*id, value.clone()))
            }
            _ => None,
        })
        .collect()
}

/// Whether a declaration is a struct with a field serialized under `wire_name`
/// — the invariant a typed discriminated union relies on.
fn decl_carries_field(program: &ir::Program, id: ir::DeclId, wire_name: &str) -> bool {
    matches!(
        &program.decl(id).kind,
        ir::DeclKind::Struct(s) if s.fields.iter().any(|f| f.wire_name == wire_name)
    )
}

/// An interface member key: the wire name verbatim when it is a valid
/// identifier (serialization is identity, TR-TS.2), quoted otherwise.
fn field_key(wire: &str) -> String {
    let mut chars = wire.chars();
    let valid = matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid {
        wire.to_string()
    } else {
        format!("{wire:?}")
    }
}

/// A TypeScript type name for an IR declaration: PascalCase, kept clear of the
/// ambient/global type names it would otherwise shadow.
pub(crate) fn type_name(name: &str) -> String {
    let pascal = pascal(name);
    if GLOBAL_TYPES.contains(&pascal.as_str()) {
        format!("{pascal}_")
    } else {
        pascal
    }
}

/// A collision-free lowercase module name per IR module path — flattening a
/// path with `_` is not injective (`[a_b]` and `[a, b]` collapse), so names are
/// allocated deterministically and shared, never recomputed (mirrors D-149).
pub(crate) fn module_names(program: &ir::Program) -> BTreeMap<ir::ModulePath, String> {
    let mut paths: Vec<ir::ModulePath> = Vec::new();
    for decl in &program.decls {
        if !paths.contains(&decl.module) {
            paths.push(decl.module.clone());
        }
    }
    let mut named: Vec<(ir::ModulePath, String)> = paths
        .into_iter()
        .map(|p| (p.clone(), module_name(&p)))
        .collect();
    named.sort_by(|a, b| a.1.cmp(&b.1));
    let mut used: Vec<String> = Vec::new();
    let mut map = BTreeMap::new();
    for (path, name) in named {
        map.insert(path, dedupe(&mut used, name));
    }
    map
}

fn module_name(module: &ir::ModulePath) -> String {
    if module.0.is_empty() {
        return "root".to_string();
    }
    module
        .0
        .iter()
        .map(|segment| {
            let mut out: String = segment
                .as_str()
                .chars()
                .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
                .collect();
            out.make_ascii_lowercase();
            if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
                out.insert(0, 'm');
            }
            out
        })
        .collect::<Vec<_>>()
        .join("_")
}

fn dedupe(used: &mut Vec<String>, base: String) -> String {
    if !used.contains(&base) {
        used.push(base.clone());
        return base;
    }
    let mut n = 2;
    loop {
        let candidate = format!("{base}_{n}");
        if !used.contains(&candidate) {
            used.push(candidate.clone());
            return candidate;
        }
        n += 1;
    }
}

/// Ambient/global type names an exported declaration must not shadow (an
/// `interface Date {}` would merge with the global `Date`).
const GLOBAL_TYPES: &[&str] = &[
    "Array", "Blob", "Boolean", "Date", "Error", "Function", "Map", "Number", "Object", "Promise",
    "Record", "Set", "String", "Symbol",
];
