//! Generated behavioral tests (FR-7.8, VR-4).
//!
//! Test files that both type-check under `tsc --noEmit` (VR-1.5) and *run* under
//! Node's built-in test runner (`node --test`, type-stripping the `.ts` in
//! place) — the TypeScript analogue of Rust's `cargo test` round-trip suite
//! (D-156). Two files, generated from the same IR so they track the real types:
//!
//! - `serialization.test.ts` — the tri-state (absent / explicit-null / value)
//!   through the `JSON.stringify`/`JSON.parse` wire codec, and ISO-8601
//!   date/date-time round-trips (serialization is identity, TR-TS.2);
//! - `unions.test.ts` — one test per discriminated union: known-tag dispatch,
//!   plus open-union unknown-tag retention via the `{ [key]: unknown }`
//!   catch-all (closed unions carry no catch-all, so they test known dispatch
//!   only) (TR-TS.1).
//!
//! `node:test`/`node:assert` are declared ambiently in `node-test.d.ts` (kept
//! local so the gate needs no `@types/node`, whose global `fetch` would clash
//! with the DOM lib — the same trick `jwt.ts` uses for `node:crypto`).

use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_sema::Analysis;

use crate::GeneratedFile;
use crate::models::{discriminated_variants, module_names, type_name};

const HEADER: &str = "// Code generated by box-gantry. DO NOT EDIT.\n";

/// Generate the behavioral test files: the fixed serialization tests, the
/// per-union round-trip tests, and the ambient `node:test`/`node:assert` decls.
pub fn generate_tests(analysis: &Analysis<'_>) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let modules = module_names(program);

    let mut body = format!(
        "{HEADER}\n\
         // Per-union round-trip tests (VR-4): known-tag dispatch, and open-union\n\
         // unknown-tag retention via the `{{ [key: string]: unknown }}` catch-all.\n\
         import {{ test }} from 'node:test';\n\
         import assert from 'node:assert/strict';\n\
         import type * as models from './models/index.js';\n\n",
    );
    for decl in &program.decls {
        let ir::DeclKind::Union(union) = &decl.kind else {
            continue;
        };
        // Only unions that lower to a typed discriminated union (every variant a
        // tagged, discriminator-carrying decl); a union with a tagless sibling
        // lowers to `unknown`, with no discriminator to assert against.
        let Some(variants) = discriminated_variants(program, union) else {
            continue;
        };
        let (Some((_, value)), Some(discriminator)) =
            (variants.first(), union.discriminator.as_deref())
        else {
            continue;
        };
        let module = modules
            .get(&decl.module)
            .cloned()
            .unwrap_or_else(|| type_name(decl.name.as_str()));
        let union_name = type_name(decl.name.as_str());
        let open = matches!(union.extensibility, ir::Extensibility::Open);

        // JS/JSON string literals, escaped through `{:?}`.
        let disc_lit = format!("{discriminator:?}"); // "type"
        let value_lit = format!("{value:?}"); // "file"
        let known_doc = js_string(&format!("{{{disc_lit}:{value_lit}}}")); // "{\"type\":\"file\"}"

        let _ = writeln!(
            body,
            "test('{module}.{union_name} dispatches on {disc_esc} — known {value_esc}{open_note}', () => {{",
            disc_esc = escape_name(discriminator),
            value_esc = escape_name(value),
            open_note = if open { ", unknown retained" } else { "" },
        );
        // Known-tag dispatch: a document carrying the discriminator parses as the
        // union and the tag round-trips.
        let _ = writeln!(
            body,
            "  const known = JSON.parse({known_doc}) as models.{module}.{union_name};"
        );
        let _ = writeln!(
            body,
            "  assert.equal((known as Record<string, unknown>)[{disc_lit}], {value_lit});"
        );
        if open {
            // Open unions retain an unrecognized tag: an object whose
            // discriminator matches no known variant is assignable via the
            // catch-all member (this line type-checks only because the catch-all
            // exists — a closed union would reject it).
            let _ = writeln!(
                body,
                "  const unknown: models.{module}.{union_name} = {{ {disc_lit}: '__gantry_unknown__' }};"
            );
            let _ = writeln!(
                body,
                "  assert.equal((unknown as Record<string, unknown>)[{disc_lit}], '__gantry_unknown__');"
            );
        }
        body.push_str("});\n\n");
    }
    // Exactly one trailing newline (formatter-clean).
    body.truncate(body.trim_end().len());
    body.push('\n');

    vec![
        GeneratedFile {
            path: "src/serialization.test.ts".to_string(),
            content: SERIALIZATION_TEST.to_string(),
        },
        GeneratedFile {
            path: "src/unions.test.ts".to_string(),
            content: body,
        },
        GeneratedFile {
            path: "src/node-test.d.ts".to_string(),
            content: NODE_TEST_DECL.to_string(),
        },
    ]
}

/// A JS double-quoted string literal whose value is `s` (escaped through `{:?}`).
fn js_string(s: &str) -> String {
    format!("{s:?}")
}

/// A discriminator/value rendered safe for a single-quoted test-name string
/// (drops anything that could break the `'...'` literal).
fn escape_name(s: &str) -> String {
    s.chars()
        .filter(|c| *c != '\'' && *c != '\\' && !c.is_control())
        .collect()
}

/// Fixed behavioral tests for the tri-state wire codec and typed date/time
/// (VR-4). `JSON.stringify`/`JSON.parse` is the codec — serialization is
/// identity (TR-TS.2) — so it must preserve absent vs explicit-null vs value.
const SERIALIZATION_TEST: &str = "// Code generated by box-gantry. DO NOT EDIT.\n\
\n\
// Serialization behavioral tests (VR-4): the tri-state (absent / explicit-null\n\
// / value) through the JSON wire codec, and ISO-8601 date/date-time round-trips.\n\
import { test } from 'node:test';\n\
import assert from 'node:assert/strict';\n\
\n\
// The tri-state mapped straight onto the type system (TR-TS.2): absent is an\n\
// omitted key, explicit null is `| null`, a value is the value.\n\
interface TriState {\n\
  field?: string | null;\n\
}\n\
\n\
test('tri-state serializes absent / null / value distinctly (Box clear-on-update)', () => {\n\
  const absent: TriState = {};\n\
  assert.equal(JSON.stringify(absent), '{}');\n\
  const nulled: TriState = { field: null };\n\
  assert.equal(JSON.stringify(nulled), '{\\\"field\\\":null}');\n\
  const valued: TriState = { field: 'x' };\n\
  assert.equal(JSON.stringify(valued), '{\\\"field\\\":\\\"x\\\"}');\n\
});\n\
\n\
test('tri-state deserializes absent / null / value distinctly', () => {\n\
  const valued = JSON.parse('{\\\"field\\\":\\\"y\\\"}') as TriState;\n\
  assert.equal(valued.field, 'y');\n\
  const nulled = JSON.parse('{\\\"field\\\":null}') as TriState;\n\
  assert.equal(nulled.field, null);\n\
  const absent = JSON.parse('{}') as TriState;\n\
  assert.equal(absent.field, undefined);\n\
  // Absent is distinguishable from null: the key is simply not present.\n\
  assert.equal('field' in absent, false);\n\
  assert.equal('field' in nulled, true);\n\
});\n\
\n\
test('ISO-8601 date and date-time strings round-trip through JSON', () => {\n\
  // Box dates/date-times are ISO strings on the wire (TR-TS.2); JSON preserves them.\n\
  const date = JSON.parse('{\\\"d\\\":\\\"2026-07-12\\\"}') as { d: string };\n\
  assert.equal(date.d, '2026-07-12');\n\
  assert.equal(JSON.stringify(date), '{\\\"d\\\":\\\"2026-07-12\\\"}');\n\
  const dt = JSON.parse('{\\\"t\\\":\\\"2026-07-12T08:30:00Z\\\"}') as { t: string };\n\
  assert.equal(dt.t, '2026-07-12T08:30:00Z');\n\
});\n";

/// A minimal ambient declaration for the slice of `node:test` / `node:assert`
/// the generated tests use — kept local so the `tsc` gate needs no
/// `@types/node` (whose global `fetch`/`Request`/`Response` would clash with the
/// DOM lib the runtime relies on). Node supplies the behavior at run time.
const NODE_TEST_DECL: &str = "// Code generated by box-gantry. DO NOT EDIT.\n\
\n\
declare module 'node:test' {\n\
  export function test(name: string, fn: () => void | Promise<void>): void;\n\
}\n\
declare module 'node:assert/strict' {\n\
  interface StrictAssert {\n\
    equal(actual: unknown, expected: unknown): void;\n\
    deepEqual(actual: unknown, expected: unknown): void;\n\
    ok(value: unknown): void;\n\
  }\n\
  const assert: StrictAssert;\n\
  export default assert;\n\
}\n";
