//! Per-endpoint Markdown reference docs for the Apex SDK (FR-7.7, TR-Apex.5).
//!
//! One page per endpoint under `docs/<manager>/<method>.md`, plus a manager
//! index and a top-level index. Each page is generated from the *same*
//! [`OpSignature`] the manager code is, so a snippet can never drift from the
//! real method surface — same name, param order, and types. The pages are
//! tuned for both a human reader and an AI coding assistant: every endpoint
//! opens with a self-contained, copy-pasteable snippet and the exact SDK
//! types it touches. Apex has no `import` statement (classes are visible
//! namespace-wide), so the "Imports & setup" section documents that and shows
//! the one-time client bootstrap. Deterministic, like all output (FR-6.2).

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use gantry_ir::naming::camel;
use gantry_manifest::{CapabilityManifest, ModuleSystem};
use gantry_sema::Analysis;
use gantry_synth::{PageStyle, PagedOperation, detect_pagination};

use crate::managers::{ManagerInfo, OpSignature, manager_infos, op_signature, unique_method_name};
use crate::models::ClassNames;
use crate::{GeneratedFile, safe_word};

/// Generate the `docs/` tree: a top index, a per-manager index, and one page
/// per endpoint.
pub fn generate_docs(analysis: &Analysis<'_>, manifest: &CapabilityManifest) -> Vec<GeneratedFile> {
    let ModuleSystem::Flat { identifier_limit } = manifest.modules else {
        panic!("the Apex backend requires the flat-namespace manifest axis");
    };
    let limit = identifier_limit as usize;
    let program = analysis.program;
    let names = ClassNames::build(program, limit);
    let infos = manager_infos(analysis, &names, limit);

    // Paginated operations are documented (the cursor loop) rather than given
    // extra classes — the base method's envelope already carries the page and
    // the cursor (D-131).
    let paged_ops = detect_pagination(analysis);
    let paged: HashMap<usize, &PagedOperation> =
        paged_ops.iter().map(|p| (p.operation, p)).collect();

    let mut files = Vec::new();
    let mut index_rows: Vec<(String, usize)> = Vec::new();

    for info in &infos {
        let op_indices = &analysis.managers[&info.manager];
        let mut used: HashSet<String> = HashSet::new();
        let mut endpoints: Vec<(OpSignature, Option<&PagedOperation>)> = Vec::new();
        for &index in op_indices {
            let op = &program.operations[index];
            let method_name = unique_method_name(op, &mut used);
            endpoints.push((
                op_signature(program, &names, op, method_name),
                paged.get(&index).copied(),
            ));
        }
        for (sig, page) in &endpoints {
            files.push(GeneratedFile {
                path: format!("docs/{}/{}.md", info.manager, sig.method_name),
                content: endpoint_page(info, sig, *page),
            });
        }
        files.push(GeneratedFile {
            path: format!("docs/{}/README.md", info.manager),
            content: manager_index(info, &endpoints),
        });
        index_rows.push((info.manager.clone(), endpoints.len()));
    }

    files.push(GeneratedFile {
        path: "docs/README.md".to_string(),
        content: top_index(&index_rows),
    });

    // Cross-cutting topic guides (FR-7.7): the Apex-flavored authentication,
    // pagination, and error-handling references, alongside the endpoint pages.
    files.push(GeneratedFile {
        path: "docs/auth.md".to_string(),
        content: AUTH_GUIDE.to_string(),
    });
    files.push(GeneratedFile {
        path: "docs/pagination.md".to_string(),
        content: PAGINATION_GUIDE.to_string(),
    });
    files.push(GeneratedFile {
        path: "docs/errors.md".to_string(),
        content: ERRORS_GUIDE.to_string(),
    });
    files
}

/// Authentication guide (FR-7.7): the three server-viable Box auth flows the
/// Apex runtime provides, each a `BoxTokenProvider`. Interactive OAuth 2.0 is
/// a documented platform exclusion (D-141) — it needs a browser
/// redirect/callback that server-side Apex cannot perform.
const AUTH_GUIDE: &str = "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
     # Authentication\n\n\
     Every callout is authorized by a `BoxTokenProvider`: the runtime mints and\n\
     caches an access token, attaches it as a bearer token, and refreshes once\n\
     on a `401`. Construct the entry-point client with the provider for your\n\
     flow:\n\n\
     ```apex\n\
     Box client = new Box(new BoxHttpClient(provider));\n\
     ```\n\n\
     ## Developer Token\n\n\
     A short-lived token from the Box developer console — handy for scripts and\n\
     tests.\n\n\
     ```apex\n\
     BoxTokenProvider provider = BoxAuth.developerToken('DEVELOPER_TOKEN');\n\
     ```\n\n\
     ## Client Credentials Grant (server auth, no key)\n\n\
     ```apex\n\
     BoxTokenProvider provider = BoxAuth.clientCredentials(\n\
     \x20   'CLIENT_ID', 'CLIENT_SECRET', 'enterprise', 'ENTERPRISE_ID');\n\
     ```\n\n\
     ## JWT (server auth with a signing key)\n\n\
     The private key never appears in Apex — it lives in a Salesforce\n\
     certificate and signs via `Crypto.signWithCertificate`.\n\n\
     ```apex\n\
     BoxTokenProvider provider = BoxAuth.jwt(\n\
     \x20   'CLIENT_ID', 'CLIENT_SECRET', 'enterprise', 'ENTERPRISE_ID',\n\
     \x20   'PUBLIC_KEY_ID', 'certificate_name');\n\
     ```\n\n\
     ## OAuth 2.0 (authorization code) — not available on-platform\n\n\
     Interactive OAuth needs a browser redirect and callback, which server-side\n\
     Apex cannot perform. Use the Client Credentials Grant or JWT above for\n\
     server-to-server access instead.\n";

/// Pagination guide (FR-7.7): the governor-limit-aware cursor loop. No page
/// iterator class is generated — the base method's envelope is the page
/// (D-131).
const PAGINATION_GUIDE: &str = "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
     # Pagination\n\n\
     List endpoints return their page directly: the response envelope carries\n\
     both the entries and the cursor for the next page. There is no separate\n\
     iterator class — one callout fetches one page, which keeps each\n\
     transaction inside Apex's callout limit (D-131). Loop until the cursor is\n\
     blank (marker style) or a page comes back empty (offset style). The\n\
     schematic marker loop:\n\n\
     ```apex\n\
     Box client = new Box(myBoxClient);\n\
     // `page` is the list endpoint's return type; it carries the entries and\n\
     // the next-page cursor. Pass the cursor back on each call until it is\n\
     // blank.\n\
     Envelope page = client.someManager.listSomething(/* …, */ null /* cursor */);\n\
     while (String.isNotBlank(page.cursorField)) {\n\
     \x20   // handle page.entriesField\n\
     \x20   page = client.someManager.listSomething(/* …, */ page.cursorField);\n\
     }\n\
     ```\n\n\
     Each paginated endpoint's reference page (`docs/<manager>/<op>.md`, flagged\n\
     `Paged`) shows its concrete envelope type, cursor and entries field names,\n\
     and the exact loop — marker or offset — for that operation.\n";

/// Errors guide (FR-7.7): the exceptions error model (TR-Apex).
const ERRORS_GUIDE: &str = "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
     # Errors\n\n\
     The SDK uses Apex's idiomatic error model: a failed request throws. The\n\
     runtime retries transient failures (exponential backoff, `Retry-After`,\n\
     and one `401` refresh); a non-2xx response that survives the retries is\n\
     raised as a `BoxApiException` carrying the HTTP status and the parsed Box\n\
     error body. Wrap calls in `try`/`catch`:\n\n\
     ```apex\n\
     try {\n\
     \x20   FileFull f = client.files.getById(fileId, null, null, null, null);\n\
     } catch (BoxApiException e) {\n\
     \x20   System.debug(e.statusCode + ': ' + e.getMessage());\n\
     }\n\
     ```\n";

/// The top-level docs index: every manager with its endpoint count.
fn top_index(rows: &[(String, usize)]) -> String {
    let mut out = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # Box SDK for Apex — endpoint reference\n\n\
         One page per endpoint, grouped by resource manager. Reach every\n\
         endpoint through the single `Box` client. Apex needs no `import`\n\
         statements — every generated class is visible in the namespace.\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient);\n\
         ```\n\n\
         ## Managers\n\n| Manager | Endpoints |\n|---|---|\n",
    );
    for (manager, count) in rows {
        let _ = writeln!(out, "| [`{manager}`]({manager}/README.md) | {count} |");
    }
    out
}

/// A manager's index: its endpoints as a linked table (paged ones flagged).
fn manager_index(
    info: &ManagerInfo,
    endpoints: &[(OpSignature, Option<&PagedOperation>)],
) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{manager}`\n\n\
         {count} endpoint(s), reached via `client.{field}`.\n\n\
         | Endpoint | Method | Path | Paged |\n|---|---|---|---|\n",
        manager = info.manager,
        count = endpoints.len(),
        field = info.field,
    );
    for (sig, page) in endpoints {
        let _ = writeln!(
            out,
            "| [`{name}`]({name}.md) | `{http}` | `{path}` | {paged} |",
            name = sig.method_name,
            http = sig.http,
            path = sig.path_display,
            paged = if page.is_some() { "yes" } else { "" },
        );
    }
    out
}

/// One endpoint's page: setup, parameters, request/response, a runnable
/// example, and — for paged operations — the cursor loop.
fn endpoint_page(info: &ManagerInfo, sig: &OpSignature, page: Option<&PagedOperation>) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{class}.{name}`\n\n\
         `{http} {path}`\n\n",
        class = info.class,
        name = sig.method_name,
        http = sig.http,
        path = sig.path_display,
    );
    if sig.deprecated {
        out.push_str("> **Deprecated** by the Box API.\n\n");
    }

    // Imports & setup — Apex has no import statement, so this documents the
    // namespace-global model and the one-time client bootstrap.
    out.push_str(
        "## Imports & setup\n\n\
         Apex has no `import` statement — every generated SDK class is visible\n\
         in the org namespace. Construct the entry-point client once:\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient); // myBoxClient implements BoxClient\n\
         ```\n\n",
    );
    let _ = writeln!(out, "**SDK types used:** {}\n", types_used(info, sig));

    // Parameters.
    if sig.params.is_empty() {
        out.push_str("## Parameters\n\n_None._\n\n");
    } else {
        out.push_str("## Parameters\n\n| Name | In | Type | Required |\n|---|---|---|---|\n");
        for param in &sig.params {
            let _ = writeln!(
                out,
                "| `{name}` | {loc} | `{ty}` | {req} |",
                name = param.name,
                loc = location_label(param.location),
                ty = param.apex_type,
                req = if param.optional { "no" } else { "yes" },
            );
        }
        out.push('\n');
    }

    // Request body.
    if let Some(body) = &sig.body_type {
        let _ = writeln!(out, "## Request body\n\n`{body}`\n");
    }

    // Returns.
    if sig.return_ty == "void" {
        out.push_str("## Returns\n\n_No content._\n\n");
    } else {
        let _ = writeln!(out, "## Returns\n\n`{}`\n", sig.return_ty);
    }

    // Pagination — no extra classes; the base method's envelope is the page,
    // so this documents the cursor loop (D-131).
    if let Some(page) = page {
        out.push_str(&pagination_section(info, sig, page));
    }

    // Example — a complete, copy-pasteable call. Required params appear as
    // named variables you supply; optional params are `null`.
    out.push_str("## Example\n\n```apex\n");
    out.push_str("Box client = new Box(myBoxClient);\n");
    let call = format!(
        "client.{field}.{name}({args})",
        field = info.field,
        name = sig.method_name,
        args = example_args(sig),
    );
    if sig.return_ty == "void" {
        let _ = writeln!(out, "{call};");
    } else {
        let _ = writeln!(out, "{ty} result = {call};", ty = sig.return_ty);
    }
    out.push_str("```\n");
    out
}

/// The pagination guide for a paged endpoint: the base method's envelope is
/// the page (`entries` + cursor), so this documents the explicit cursor loop
/// — one page per callout, the governor-limit-aware pattern (D-131). No page
/// classes are generated.
fn pagination_section(info: &ManagerInfo, sig: &OpSignature, page: &PagedOperation) -> String {
    let envelope = &sig.return_ty;
    let entries = safe_word(page.entries_wire.as_str());
    let cursor = safe_word(page.cursor_wire.as_str());
    let cursor_arg = safe_word(&camel(&page.param_wire));

    let mut out = String::from("## Pagination\n\n");
    match page.style {
        PageStyle::Marker => {
            let first = pagination_call(info, sig, &cursor_arg, "null");
            let next = pagination_call(info, sig, &cursor_arg, &format!("page.{cursor}"));
            let _ = writeln!(
                out,
                "Paginated by the `{param}` cursor. The `{envelope}` returned here carries \
                 `{entries}` (this page) and `{cursor}` (the cursor for the next page — blank \
                 on the last). Loop until the cursor is blank:\n",
                param = page.param_wire,
            );
            out.push_str("```apex\n");
            let _ = writeln!(out, "{envelope} page = {first};");
            let _ = writeln!(out, "while (String.isNotBlank(page.{cursor})) {{");
            let _ = writeln!(out, "    // handle page.{entries}");
            let _ = writeln!(out, "    page = {next};");
            let _ = writeln!(out, "}}");
        }
        PageStyle::Offset => {
            // The offset advances client-side; the request cursor is the
            // running `offset` variable, not the echoed response field.
            let call = pagination_call(info, sig, &cursor_arg, "offset");
            let _ = writeln!(
                out,
                "Paginated by the `{param}` cursor. The `{envelope}` returned here carries \
                 `{entries}` (this page). Advance `offset` by the page size until a page \
                 returns no entries:\n",
                param = page.param_wire,
            );
            out.push_str("```apex\n");
            let _ = writeln!(out, "Long offset = 0;");
            let _ = writeln!(out, "{envelope} page = {call};");
            let _ = writeln!(
                out,
                "while (page.{entries} != null && !page.{entries}.isEmpty()) {{"
            );
            let _ = writeln!(out, "    // handle page.{entries}");
            let _ = writeln!(out, "    offset += page.{entries}.size();");
            let _ = writeln!(out, "    page = {call};");
            let _ = writeln!(out, "}}");
        }
    }
    out.push_str("```\n\n");
    out
}

/// Render `client.<field>.<method>(…)` with the cursor argument substituted
/// (the rest: required params by name, optionals `null`).
fn pagination_call(
    info: &ManagerInfo,
    sig: &OpSignature,
    cursor_arg: &str,
    cursor_value: &str,
) -> String {
    let mut parts: Vec<String> = sig
        .params
        .iter()
        .map(|p| {
            if p.name == cursor_arg {
                cursor_value.to_string()
            } else if p.optional {
                "null".to_string()
            } else {
                p.name.clone()
            }
        })
        .collect();
    if sig.body_type.is_some() {
        parts.push("body".to_string());
    }
    format!(
        "client.{field}.{method}({args})",
        field = info.field,
        method = sig.method_name,
        args = parts.join(", "),
    )
}

/// The example call arguments: a named variable per required param, `null`
/// per optional param, and `body` for the request body — in signature order.
fn example_args(sig: &OpSignature) -> String {
    let mut parts: Vec<String> = sig
        .params
        .iter()
        .map(|p| {
            if p.optional {
                "null".to_string()
            } else {
                p.name.clone()
            }
        })
        .collect();
    if sig.body_type.is_some() {
        parts.push("body".to_string());
    }
    parts.join(", ")
}

/// The distinct SDK types an endpoint touches, as an inline code list.
fn types_used(info: &ManagerInfo, sig: &OpSignature) -> String {
    let mut types: Vec<String> = vec!["Box".to_string(), info.class.clone()];
    if let Some(body) = &sig.body_type {
        types.push(body.clone());
    }
    if sig.return_ty != "void" {
        types.push(sig.return_ty.clone());
    }
    let mut seen = HashSet::new();
    types
        .into_iter()
        .filter(|t| seen.insert(t.clone()))
        .map(|t| format!("`{t}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn location_label(loc: gantry_ir::ParamLocation) -> &'static str {
    match loc {
        gantry_ir::ParamLocation::Path => "path",
        gantry_ir::ParamLocation::Query => "query",
        gantry_ir::ParamLocation::Header => "header",
    }
}
