//! Per-endpoint Markdown reference docs for the Apex SDK (FR-7.7, TR-Apex.5).
//!
//! One page per endpoint under `docs/<manager>/<method>.md`, plus a manager
//! index and a top-level index. Each page is generated from the *same*
//! [`OpSignature`] the manager code is, so a snippet can never drift from the
//! real method surface — same name, param order, and types. The pages are
//! tuned for both a human reader and an AI coding assistant: every endpoint
//! opens with a self-contained, copy-pasteable snippet and the exact SDK
//! types it touches. Apex has no `import` statement (classes are visible
//! namespace-wide), so the "Imports & setup" section documents that and shows
//! the one-time client bootstrap. Deterministic, like all output (FR-6.2).

use std::collections::HashSet;
use std::fmt::Write as _;

use gantry_manifest::{CapabilityManifest, ModuleSystem};
use gantry_sema::Analysis;

use crate::GeneratedFile;
use crate::managers::{ManagerInfo, OpSignature, manager_infos, op_signature, unique_method_name};
use crate::models::ClassNames;

/// Generate the `docs/` tree: a top index, a per-manager index, and one page
/// per endpoint.
pub fn generate_docs(analysis: &Analysis<'_>, manifest: &CapabilityManifest) -> Vec<GeneratedFile> {
    let ModuleSystem::Flat { identifier_limit } = manifest.modules else {
        panic!("the Apex backend requires the flat-namespace manifest axis");
    };
    let limit = identifier_limit as usize;
    let program = analysis.program;
    let names = ClassNames::build(program, limit);
    let infos = manager_infos(analysis, &names, limit);

    let mut files = Vec::new();
    let mut index_rows: Vec<(String, usize)> = Vec::new();

    for info in &infos {
        let op_indices = &analysis.managers[&info.manager];
        let mut used: HashSet<String> = HashSet::new();
        let mut endpoints: Vec<OpSignature> = Vec::new();
        for &index in op_indices {
            let op = &program.operations[index];
            let method_name = unique_method_name(op, &mut used);
            endpoints.push(op_signature(program, &names, op, method_name));
        }
        for sig in &endpoints {
            files.push(GeneratedFile {
                path: format!("docs/{}/{}.md", info.manager, sig.method_name),
                content: endpoint_page(info, sig),
            });
        }
        files.push(GeneratedFile {
            path: format!("docs/{}/README.md", info.manager),
            content: manager_index(info, &endpoints),
        });
        index_rows.push((info.manager.clone(), endpoints.len()));
    }

    files.push(GeneratedFile {
        path: "docs/README.md".to_string(),
        content: top_index(&index_rows),
    });
    files
}

/// The top-level docs index: every manager with its endpoint count.
fn top_index(rows: &[(String, usize)]) -> String {
    let mut out = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # Box SDK for Apex — endpoint reference\n\n\
         One page per endpoint, grouped by resource manager. Reach every\n\
         endpoint through the single `Box` client. Apex needs no `import`\n\
         statements — every generated class is visible in the namespace.\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient);\n\
         ```\n\n\
         ## Managers\n\n| Manager | Endpoints |\n|---|---|\n",
    );
    for (manager, count) in rows {
        let _ = writeln!(out, "| [`{manager}`]({manager}/README.md) | {count} |");
    }
    out
}

/// A manager's index: its endpoints as a linked table.
fn manager_index(info: &ManagerInfo, endpoints: &[OpSignature]) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{manager}`\n\n\
         {count} endpoint(s), reached via `client.{field}`.\n\n\
         | Endpoint | Method | Path |\n|---|---|---|\n",
        manager = info.manager,
        count = endpoints.len(),
        field = info.field,
    );
    for sig in endpoints {
        let _ = writeln!(
            out,
            "| [`{name}`]({name}.md) | `{http}` | `{path}` |",
            name = sig.method_name,
            http = sig.http,
            path = sig.path_display,
        );
    }
    out
}

/// One endpoint's page: setup, parameters, request/response, and a runnable
/// example.
fn endpoint_page(info: &ManagerInfo, sig: &OpSignature) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{class}.{name}`\n\n\
         `{http} {path}`\n\n",
        class = info.class,
        name = sig.method_name,
        http = sig.http,
        path = sig.path_display,
    );
    if sig.deprecated {
        out.push_str("> **Deprecated** by the Box API.\n\n");
    }

    // Imports & setup — Apex has no import statement, so this documents the
    // namespace-global model and the one-time client bootstrap.
    out.push_str(
        "## Imports & setup\n\n\
         Apex has no `import` statement — every generated SDK class is visible\n\
         in the org namespace. Construct the entry-point client once:\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient); // myBoxClient implements BoxClient\n\
         ```\n\n",
    );
    let _ = writeln!(out, "**SDK types used:** {}\n", types_used(info, sig));

    // Parameters.
    if sig.params.is_empty() {
        out.push_str("## Parameters\n\n_None._\n\n");
    } else {
        out.push_str("## Parameters\n\n| Name | In | Type | Required |\n|---|---|---|---|\n");
        for param in &sig.params {
            let _ = writeln!(
                out,
                "| `{name}` | {loc} | `{ty}` | {req} |",
                name = param.name,
                loc = location_label(param.location),
                ty = param.apex_type,
                req = if param.optional { "no" } else { "yes" },
            );
        }
        out.push('\n');
    }

    // Request body.
    if let Some(body) = &sig.body_type {
        let _ = writeln!(out, "## Request body\n\n`{body}`\n");
    }

    // Returns.
    if sig.return_ty == "void" {
        out.push_str("## Returns\n\n_No content._\n\n");
    } else {
        let _ = writeln!(out, "## Returns\n\n`{}`\n", sig.return_ty);
    }

    // Example — a complete, copy-pasteable call. Required params appear as
    // named variables you supply; optional params are `null`.
    out.push_str("## Example\n\n```apex\n");
    out.push_str("Box client = new Box(myBoxClient);\n");
    let call = format!(
        "client.{field}.{name}({args})",
        field = info.field,
        name = sig.method_name,
        args = example_args(sig),
    );
    if sig.return_ty == "void" {
        let _ = writeln!(out, "{call};");
    } else {
        let _ = writeln!(out, "{ty} result = {call};", ty = sig.return_ty);
    }
    out.push_str("```\n");
    out
}

/// The example call arguments: a named variable per required param, `null`
/// per optional param, and `body` for the request body — in signature order.
fn example_args(sig: &OpSignature) -> String {
    let mut parts: Vec<String> = sig
        .params
        .iter()
        .map(|p| {
            if p.optional {
                "null".to_string()
            } else {
                p.name.clone()
            }
        })
        .collect();
    if sig.body_type.is_some() {
        parts.push("body".to_string());
    }
    parts.join(", ")
}

/// The distinct SDK types an endpoint touches, as an inline code list.
fn types_used(info: &ManagerInfo, sig: &OpSignature) -> String {
    let mut types: Vec<String> = vec!["Box".to_string(), info.class.clone()];
    if let Some(body) = &sig.body_type {
        types.push(body.clone());
    }
    if sig.return_ty != "void" {
        types.push(sig.return_ty.clone());
    }
    let mut seen = HashSet::new();
    types
        .into_iter()
        .filter(|t| seen.insert(t.clone()))
        .map(|t| format!("`{t}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn location_label(loc: gantry_ir::ParamLocation) -> &'static str {
    match loc {
        gantry_ir::ParamLocation::Path => "path",
        gantry_ir::ParamLocation::Query => "query",
        gantry_ir::ParamLocation::Header => "header",
    }
}
