//! Per-endpoint Markdown reference docs for the Apex SDK (FR-7.7, TR-Apex.5).
//!
//! One page per endpoint under `docs/<manager>/<method>.md`, plus a manager
//! index and a top-level index. Each page is generated from the *same*
//! [`OpSignature`] the manager code is, so a snippet can never drift from the
//! real method surface — same name, param order, and types. The pages are
//! tuned for both a human reader and an AI coding assistant: every endpoint
//! opens with a self-contained, copy-pasteable snippet and the exact SDK
//! types it touches. Apex has no `import` statement (classes are visible
//! namespace-wide), so the "Imports & setup" section documents that and shows
//! the one-time client bootstrap. Deterministic, like all output (FR-6.2).

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use gantry_ir::naming::camel;
use gantry_manifest::{CapabilityManifest, ModuleSystem};
use gantry_sema::Analysis;
use gantry_synth::{PageStyle, PagedOperation, detect_pagination};

use crate::managers::{ManagerInfo, OpSignature, manager_infos, op_signature, unique_method_name};
use crate::models::ClassNames;
use crate::{GeneratedFile, safe_word};

/// Generate the `docs/` tree: a top index, a per-manager index, and one page
/// per endpoint.
pub fn generate_docs(analysis: &Analysis<'_>, manifest: &CapabilityManifest) -> Vec<GeneratedFile> {
    let ModuleSystem::Flat { identifier_limit } = manifest.modules else {
        panic!("the Apex backend requires the flat-namespace manifest axis");
    };
    let limit = identifier_limit as usize;
    let program = analysis.program;
    let names = ClassNames::build(program, limit);
    let infos = manager_infos(analysis, &names, limit);

    // Paginated operations are documented (the cursor loop) rather than given
    // extra classes — the base method's envelope already carries the page and
    // the cursor (D-131).
    let paged_ops = detect_pagination(analysis);
    let paged: HashMap<usize, &PagedOperation> =
        paged_ops.iter().map(|p| (p.operation, p)).collect();

    let mut files = Vec::new();
    let mut index_rows: Vec<(String, usize)> = Vec::new();

    for info in &infos {
        let op_indices = &analysis.managers[&info.manager];
        let mut used: HashSet<String> = HashSet::new();
        let mut endpoints: Vec<(OpSignature, Option<&PagedOperation>)> = Vec::new();
        for &index in op_indices {
            let op = &program.operations[index];
            let method_name = unique_method_name(op, &mut used);
            endpoints.push((
                op_signature(program, &names, op, method_name),
                paged.get(&index).copied(),
            ));
        }
        for (sig, page) in &endpoints {
            files.push(GeneratedFile {
                path: format!("docs/{}/{}.md", info.manager, sig.method_name),
                content: endpoint_page(info, sig, *page),
            });
        }
        files.push(GeneratedFile {
            path: format!("docs/{}/README.md", info.manager),
            content: manager_index(info, &endpoints),
        });
        index_rows.push((info.manager.clone(), endpoints.len()));
    }

    files.push(GeneratedFile {
        path: "docs/README.md".to_string(),
        content: top_index(&index_rows),
    });
    files
}

/// The top-level docs index: every manager with its endpoint count.
fn top_index(rows: &[(String, usize)]) -> String {
    let mut out = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # Box SDK for Apex — endpoint reference\n\n\
         One page per endpoint, grouped by resource manager. Reach every\n\
         endpoint through the single `Box` client. Apex needs no `import`\n\
         statements — every generated class is visible in the namespace.\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient);\n\
         ```\n\n\
         ## Managers\n\n| Manager | Endpoints |\n|---|---|\n",
    );
    for (manager, count) in rows {
        let _ = writeln!(out, "| [`{manager}`]({manager}/README.md) | {count} |");
    }
    out
}

/// A manager's index: its endpoints as a linked table (paged ones flagged).
fn manager_index(
    info: &ManagerInfo,
    endpoints: &[(OpSignature, Option<&PagedOperation>)],
) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{manager}`\n\n\
         {count} endpoint(s), reached via `client.{field}`.\n\n\
         | Endpoint | Method | Path | Paged |\n|---|---|---|---|\n",
        manager = info.manager,
        count = endpoints.len(),
        field = info.field,
    );
    for (sig, page) in endpoints {
        let _ = writeln!(
            out,
            "| [`{name}`]({name}.md) | `{http}` | `{path}` | {paged} |",
            name = sig.method_name,
            http = sig.http,
            path = sig.path_display,
            paged = if page.is_some() { "yes" } else { "" },
        );
    }
    out
}

/// One endpoint's page: setup, parameters, request/response, a runnable
/// example, and — for paged operations — the cursor loop.
fn endpoint_page(info: &ManagerInfo, sig: &OpSignature, page: Option<&PagedOperation>) -> String {
    let mut out = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # `{class}.{name}`\n\n\
         `{http} {path}`\n\n",
        class = info.class,
        name = sig.method_name,
        http = sig.http,
        path = sig.path_display,
    );
    if sig.deprecated {
        out.push_str("> **Deprecated** by the Box API.\n\n");
    }

    // Imports & setup — Apex has no import statement, so this documents the
    // namespace-global model and the one-time client bootstrap.
    out.push_str(
        "## Imports & setup\n\n\
         Apex has no `import` statement — every generated SDK class is visible\n\
         in the org namespace. Construct the entry-point client once:\n\n\
         ```apex\n\
         Box client = new Box(myBoxClient); // myBoxClient implements BoxClient\n\
         ```\n\n",
    );
    let _ = writeln!(out, "**SDK types used:** {}\n", types_used(info, sig));

    // Parameters.
    if sig.params.is_empty() {
        out.push_str("## Parameters\n\n_None._\n\n");
    } else {
        out.push_str("## Parameters\n\n| Name | In | Type | Required |\n|---|---|---|---|\n");
        for param in &sig.params {
            let _ = writeln!(
                out,
                "| `{name}` | {loc} | `{ty}` | {req} |",
                name = param.name,
                loc = location_label(param.location),
                ty = param.apex_type,
                req = if param.optional { "no" } else { "yes" },
            );
        }
        out.push('\n');
    }

    // Request body.
    if let Some(body) = &sig.body_type {
        let _ = writeln!(out, "## Request body\n\n`{body}`\n");
    }

    // Returns.
    if sig.return_ty == "void" {
        out.push_str("## Returns\n\n_No content._\n\n");
    } else {
        let _ = writeln!(out, "## Returns\n\n`{}`\n", sig.return_ty);
    }

    // Pagination — no extra classes; the base method's envelope is the page,
    // so this documents the cursor loop (D-131).
    if let Some(page) = page {
        out.push_str(&pagination_section(info, sig, page));
    }

    // Example — a complete, copy-pasteable call. Required params appear as
    // named variables you supply; optional params are `null`.
    out.push_str("## Example\n\n```apex\n");
    out.push_str("Box client = new Box(myBoxClient);\n");
    let call = format!(
        "client.{field}.{name}({args})",
        field = info.field,
        name = sig.method_name,
        args = example_args(sig),
    );
    if sig.return_ty == "void" {
        let _ = writeln!(out, "{call};");
    } else {
        let _ = writeln!(out, "{ty} result = {call};", ty = sig.return_ty);
    }
    out.push_str("```\n");
    out
}

/// The pagination guide for a paged endpoint: the base method's envelope is
/// the page (`entries` + cursor), so this documents the explicit cursor loop
/// — one page per callout, the governor-limit-aware pattern (D-131). No page
/// classes are generated.
fn pagination_section(info: &ManagerInfo, sig: &OpSignature, page: &PagedOperation) -> String {
    let envelope = &sig.return_ty;
    let entries = safe_word(page.entries_wire.as_str());
    let cursor = safe_word(page.cursor_wire.as_str());
    let cursor_arg = safe_word(&camel(&page.param_wire));

    let mut out = String::from("## Pagination\n\n");
    match page.style {
        PageStyle::Marker => {
            let first = pagination_call(info, sig, &cursor_arg, "null");
            let next = pagination_call(info, sig, &cursor_arg, &format!("page.{cursor}"));
            let _ = writeln!(
                out,
                "Paginated by the `{param}` cursor. The `{envelope}` returned here carries \
                 `{entries}` (this page) and `{cursor}` (the cursor for the next page — blank \
                 on the last). Loop until the cursor is blank:\n",
                param = page.param_wire,
            );
            out.push_str("```apex\n");
            let _ = writeln!(out, "{envelope} page = {first};");
            let _ = writeln!(out, "while (String.isNotBlank(page.{cursor})) {{");
            let _ = writeln!(out, "    // handle page.{entries}");
            let _ = writeln!(out, "    page = {next};");
            let _ = writeln!(out, "}}");
        }
        PageStyle::Offset => {
            // The offset advances client-side; the request cursor is the
            // running `offset` variable, not the echoed response field.
            let call = pagination_call(info, sig, &cursor_arg, "offset");
            let _ = writeln!(
                out,
                "Paginated by the `{param}` cursor. The `{envelope}` returned here carries \
                 `{entries}` (this page). Advance `offset` by the page size until a page \
                 returns no entries:\n",
                param = page.param_wire,
            );
            out.push_str("```apex\n");
            let _ = writeln!(out, "Long offset = 0;");
            let _ = writeln!(out, "{envelope} page = {call};");
            let _ = writeln!(
                out,
                "while (page.{entries} != null && !page.{entries}.isEmpty()) {{"
            );
            let _ = writeln!(out, "    // handle page.{entries}");
            let _ = writeln!(out, "    offset += page.{entries}.size();");
            let _ = writeln!(out, "    page = {call};");
            let _ = writeln!(out, "}}");
        }
    }
    out.push_str("```\n\n");
    out
}

/// Render `client.<field>.<method>(…)` with the cursor argument substituted
/// (the rest: required params by name, optionals `null`).
fn pagination_call(
    info: &ManagerInfo,
    sig: &OpSignature,
    cursor_arg: &str,
    cursor_value: &str,
) -> String {
    let mut parts: Vec<String> = sig
        .params
        .iter()
        .map(|p| {
            if p.name == cursor_arg {
                cursor_value.to_string()
            } else if p.optional {
                "null".to_string()
            } else {
                p.name.clone()
            }
        })
        .collect();
    if sig.body_type.is_some() {
        parts.push("body".to_string());
    }
    format!(
        "client.{field}.{method}({args})",
        field = info.field,
        method = sig.method_name,
        args = parts.join(", "),
    )
}

/// The example call arguments: a named variable per required param, `null`
/// per optional param, and `body` for the request body — in signature order.
fn example_args(sig: &OpSignature) -> String {
    let mut parts: Vec<String> = sig
        .params
        .iter()
        .map(|p| {
            if p.optional {
                "null".to_string()
            } else {
                p.name.clone()
            }
        })
        .collect();
    if sig.body_type.is_some() {
        parts.push("body".to_string());
    }
    parts.join(", ")
}

/// The distinct SDK types an endpoint touches, as an inline code list.
fn types_used(info: &ManagerInfo, sig: &OpSignature) -> String {
    let mut types: Vec<String> = vec!["Box".to_string(), info.class.clone()];
    if let Some(body) = &sig.body_type {
        types.push(body.clone());
    }
    if sig.return_ty != "void" {
        types.push(sig.return_ty.clone());
    }
    let mut seen = HashSet::new();
    types
        .into_iter()
        .filter(|t| seen.insert(t.clone()))
        .map(|t| format!("`{t}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn location_label(loc: gantry_ir::ParamLocation) -> &'static str {
    match loc {
        gantry_ir::ParamLocation::Path => "path",
        gantry_ir::ParamLocation::Query => "query",
        gantry_ir::ParamLocation::Header => "header",
    }
}
