//! Go stub rendering (FR-5.3).
//!
//! The stubs are rendered from the contract data itself, so the stub
//! surface and the declared surface cannot drift (FR-5.2). Generated SDK
//! code compiles against this package in verification without the real
//! runtime (G-1). Error shape and context threading come from the
//! capability manifest's axes — never from a language name (FR-4.2).

use std::fmt::Write as _;

use gantry_manifest::{AsyncModel, CapabilityManifest, ErrorModel};

use crate::{ContractFn, ContractType, Receiver, RuntimeContract};

/// Render the compilable Go stub package for a contract.
///
/// Output is gofmt-clean by construction (G-17) and deterministic
/// (FR-6.2); every stub panics loudly when called (NF-1 — a stub that
/// silently returns zero values would hide missing runtime wiring).
pub fn go_stubs(contract: &RuntimeContract, manifest: &CapabilityManifest) -> String {
    assert_eq!(
        manifest.error_model,
        ErrorModel::ValueAndError,
        "the Go stub renderer implements the (T, error) axis"
    );
    assert_eq!(
        manifest.async_model,
        AsyncModel::Sync,
        "the Go stub renderer implements the sync axis"
    );

    let mut out = String::new();
    out.push_str(
        "// Code generated by gantry-contract — do not edit.\n\
         //\n\
         // Compilable stubs for the hand-written runtime surface (FR-5.3).\n\
         // Generated SDK code compile-verifies against this package; the\n\
         // real runtime implements the same contract.\n\
         package gantryruntime\n\n\
         import (\n\
         \t\"context\"\n\
         \t\"io\"\n\
         )\n\n\
         // Request is the runtime-owned HTTP request envelope.\n\
         type Request struct{ private struct{} }\n\n\
         // Response is the runtime-owned HTTP response envelope.\n\
         type Response struct{ private struct{} }\n\n\
         // TokenSource yields an access token for the configured auth flow.\n\
         type TokenSource interface {\n\
         \tAccessToken(ctx context.Context) (string, error)\n\
         }\n\n\
         // Option configures a Client at construction (the With* surface).\n\
         type Option func(*Client)\n\n\
         // Client is the runtime session holding config (auth, base URLs,\n\
         // HTTP client, retry policy). Session-receiver contract functions\n\
         // are its methods.\n\
         type Client struct{ private struct{} }\n\n\
         // New builds a runtime Client for a token source and options.\n\
         func New(ts TokenSource, opts ...Option) *Client {\n\
         \tpanic(\"gantryruntime stub: New is not wired to a real runtime\")\n\
         }\n\n",
    );

    for function in contract.functions {
        render_fn(&mut out, function);
    }
    // Exactly one trailing newline: gofmt-clean by construction (G-17).
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn render_fn(out: &mut String, function: &ContractFn) {
    // The behavior clause travels into the stub as documentation.
    let _ = writeln!(out, "// {} — {}", go_name(function.name), function.behavior);

    let mut params: Vec<String> = Vec::new();
    if function.takes_context {
        params.push("ctx context.Context".to_string());
    }
    for (name, ty) in function.params {
        params.push(format!("{} {}", go_param(name), go_type(*ty)));
    }

    let ret = match (function.ret, function.fallible) {
        (Some(ty), true) => format!(" ({}, error)", go_type(ty)),
        (Some(ty), false) => format!(" {}", go_type(ty)),
        (None, true) => " error".to_string(),
        (None, false) => String::new(),
    };

    // Session functions are methods on *Client; free functions are
    // package-level (FR-5.1 receiver axis).
    let receiver = match function.receiver {
        Receiver::Session => "(c *Client) ",
        Receiver::Free => "",
    };
    let _ = writeln!(
        out,
        "func {receiver}{name}({params}){ret} {{\n\tpanic(\"gantryruntime stub: {raw} is not wired to a real runtime\")\n}}\n",
        name = go_name(function.name),
        params = params.join(", "),
        raw = function.name,
    );
}

/// Exported PascalCase: `with_json_body` → `WithJSONBody`? No — initialisms
/// stay simple (`WithJsonBody`) until the FR-1.2 casing layer decides
/// initialism policy for the whole backend at once.
fn go_name(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    for part in snake.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn go_param(snake: &str) -> String {
    let pascal = go_name(snake);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => pascal,
    }
}

fn go_type(ty: ContractType) -> &'static str {
    match ty {
        ContractType::Context => "context.Context",
        ContractType::String => "string",
        ContractType::Bytes => "[]byte",
        ContractType::Bool => "bool",
        ContractType::Int64 => "int64",
        ContractType::Json => "any",
        ContractType::Request => "*Request",
        ContractType::Response => "*Response",
        ContractType::Stream => "io.Reader",
    }
}

/// A `go.mod` for the stub package, pinned to the TR-Go.4 minimum.
pub const GO_MOD: &str = "module boxgantry.invalid/gantryruntime\n\ngo 1.23\n";
