//! Reference documentation generation (FR-7.7).
//!
//! Per-manager Markdown plus the auth / pagination / errors cross-cutting
//! guides, generated from the same IR the code is — so the docs describe the
//! real Java surface (camelCased method names, record types, blocking methods
//! that throw `BoxApiException`, the `for (var … : …Paginate(…))` idiom) and
//! can't drift from it. The Java analogue of the Rust (D-155) and TypeScript
//! (D-163) docs slices. Deterministic, like all output (FR-6.2).

use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::snake;
use gantry_sema::Analysis;
use gantry_synth::detect_pagination;

use crate::GeneratedFile;
use crate::managers::{ManagerPlan, deduped_methods, plan_managers};
use crate::models::type_names;

/// Generate `docs/` — an index, one page per manager, and the guides.
pub fn generate_docs(analysis: &Analysis<'_>) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let base_version = program
        .operations
        .first()
        .and_then(|op| op.api_version.clone());
    let paged: HashMap<usize, ()> = detect_pagination(analysis)
        .into_iter()
        .map(|p| (p.operation, ()))
        .collect();
    let names = type_names(program);
    let plans = plan_managers(analysis);

    // The chunked-upload guide ships only when the orchestrator itself does
    // (VR-6): the docs must not describe a `BoxChunkedUpload` a synthetic spec
    // never emitted.
    let has_chunked = crate::emits_chunked_upload(analysis);

    let mut files = Vec::new();
    files.push(index_page(&plans, has_chunked));
    for plan in &plans {
        files.push(manager_page(
            program,
            base_version.as_ref(),
            &paged,
            &names,
            plan,
        ));
    }
    files.push(guide("auth", AUTH_GUIDE));
    files.push(guide("pagination", PAGINATION_GUIDE));
    files.push(guide("errors", ERRORS_GUIDE));
    if has_chunked {
        files.push(guide("chunked-upload", CHUNKED_UPLOAD_GUIDE));
    }
    files
}

/// `docs/README.md` — an index linking the guides and tabulating every manager.
fn index_page(plans: &[ManagerPlan], has_chunked: bool) -> GeneratedFile {
    let chunked_link = if has_chunked {
        "\n- [Chunked upload](chunked-upload.md)"
    } else {
        ""
    };
    let mut body = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# Box SDK reference\n\n\
         One resource manager per Box API tag, reached through the single\n\
         `com.box.sdk.Client` entry point.\n\n## Guides\n\n\
         - [Authentication](auth.md)\n- [Pagination](pagination.md)\n- [Errors](errors.md)\
         {chunked_link}\n\n\
         ## Managers\n\n| Manager | Field | Operations |\n|---|---|---|\n",
    );
    for plan in plans {
        let _ = writeln!(
            body,
            "| [{class}](managers/{class}.md) | `client.{field}` | {count} |",
            class = plan.class,
            field = plan.field,
            count = plan.ops.len(),
        );
    }
    GeneratedFile {
        path: "docs/README.md".to_string(),
        content: body,
    }
}

/// `docs/managers/<Class>.md` — one page per manager: each operation's HTTP
/// line, parameter table, request/response types, and a pagination note.
fn manager_page(
    program: &ir::Program,
    base_version: Option<&ir::ApiVersion>,
    paged: &HashMap<usize, ()>,
    names: &BTreeMap<ir::DeclId, String>,
    plan: &ManagerPlan,
) -> GeneratedFile {
    let mut body = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# {class}\n\n\
         Reach these methods through the `{field}` field on `com.box.sdk.Client`.\n\
         Each is a **blocking** call returning its value directly and throwing\n\
         `com.box.sdk.runtime.Runtime.BoxApiException` on failure.\n\n",
        class = plan.class,
        field = plan.field,
    );
    for (index, method) in deduped_methods(program, &plan.ops, base_version) {
        let op = &program.operations[index];
        let _ = writeln!(body, "## {method}\n");
        if op.deprecated {
            body.push_str("> **Deprecated.**\n\n");
        }
        let _ = writeln!(
            body,
            "`{http} {path}`\n",
            http = http_method(op.method),
            path = render_path(op),
        );

        if !op.params.is_empty() {
            body.push_str("| Parameter | In | Type | Required |\n|---|---|---|---|\n");
            for param in &op.params {
                let required = !matches!(param.ty, ir::Type::Optional(_));
                let _ = writeln!(
                    body,
                    "| `{name}` | {loc} | `{ty}` | {req} |",
                    name = param.wire_name,
                    loc = param_location(param.location),
                    ty = describe(program, names, unwrap(&param.ty)),
                    req = if required { "yes" } else { "no" },
                );
            }
            body.push('\n');
        }
        if let Some(req) = &op.request {
            let _ = writeln!(
                body,
                "**Request body** (`{media}`): `{ty}`\n",
                media = request_media(req.media),
                ty = describe(program, names, unwrap(&req.ty)),
            );
        }
        let _ = writeln!(
            body,
            "**Returns:** {}\n",
            describe_response(program, names, &op.response)
        );
        if paged.contains_key(&index) {
            let _ = writeln!(
                body,
                "Paginated — also available as `{method}Paginate(...)`, returning an\n\
                 `Iterable` you loop with `for (var item : …)`. See the\n\
                 [pagination guide](../pagination.md).\n"
            );
        }
    }
    GeneratedFile {
        path: format!("docs/managers/{}.md", plan.class),
        content: body,
    }
}

fn guide(name: &str, content: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("docs/{name}.md"),
        content: format!("<!-- Generated by box-gantry. DO NOT EDIT. -->\n{content}"),
    }
}

/// A readable, Java-flavored name for a type, for docs only — matching the
/// model layer's type mapping so the docs describe the real generated surface
/// (declarations by their simple class name; `Optional`/`Nullable` both read as
/// the underlying type, since a Java reference is already nullable).
fn describe(program: &ir::Program, names: &BTreeMap<ir::DeclId, String>, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Bool => "Boolean".into(),
        ir::Type::Int64 => "Long".into(),
        ir::Type::Float64 => "Double".into(),
        ir::Type::String => "String".into(),
        ir::Type::Date => "java.time.LocalDate".into(),
        ir::Type::DateTime => "java.time.OffsetDateTime".into(),
        ir::Type::Binary => "byte[]".into(),
        ir::Type::JsonValue => "Object".into(),
        ir::Type::List(inner) => format!("List<{}>", describe(program, names, inner)),
        ir::Type::Map(inner) => {
            format!("Map<String, {}>", describe(program, names, inner))
        }
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => describe(program, names, inner),
        ir::Type::Decl(id) => match &program.decl(*id).kind {
            // An alias has no Java type of its own — describe what it resolves to.
            ir::DeclKind::Alias(target) => describe(program, names, target),
            ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) | ir::DeclKind::Enum(_) => {
                names[id].clone()
            }
        },
    }
}

fn describe_response(
    program: &ir::Program,
    names: &BTreeMap<ir::DeclId, String>,
    response: &ir::ResponseShape,
) -> String {
    match response {
        ir::ResponseShape::None => "no content (`void`)".into(),
        ir::ResponseShape::Json(ty) => format!("`{}`", describe(program, names, unwrap(ty))),
        ir::ResponseShape::Binary => "a binary stream (`Runtime.Stream`)".into(),
        ir::ResponseShape::Text => "text (`String`)".into(),
        ir::ResponseShape::Redirect => "a redirect URL (`String`)".into(),
    }
}

fn unwrap(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}

fn render_path(op: &ir::Operation) -> String {
    let mut out = String::new();
    for segment in &op.path {
        out.push('/');
        match segment {
            ir::PathSegment::Literal(text) => out.push_str(text),
            ir::PathSegment::Parameter(name) => {
                let _ = write!(out, "{{{}}}", snake(name.as_str()));
            }
            ir::PathSegment::Composite(parts) => {
                for part in parts {
                    match part {
                        ir::PathPart::Literal(text) => out.push_str(text),
                        ir::PathPart::Parameter(name) => {
                            let _ = write!(out, "{{{}}}", snake(name.as_str()));
                        }
                    }
                }
            }
        }
    }
    out
}

fn http_method(method: ir::HttpMethod) -> &'static str {
    match method {
        ir::HttpMethod::Get => "GET",
        ir::HttpMethod::Put => "PUT",
        ir::HttpMethod::Post => "POST",
        ir::HttpMethod::Delete => "DELETE",
        ir::HttpMethod::Options => "OPTIONS",
        ir::HttpMethod::Head => "HEAD",
        ir::HttpMethod::Patch => "PATCH",
        ir::HttpMethod::Trace => "TRACE",
    }
}

fn param_location(location: ir::ParamLocation) -> &'static str {
    match location {
        ir::ParamLocation::Path => "path",
        ir::ParamLocation::Query => "query",
        ir::ParamLocation::Header => "header",
    }
}

fn request_media(media: ir::RequestMedia) -> &'static str {
    match media {
        ir::RequestMedia::Json => "application/json",
        ir::RequestMedia::JsonPatch => "application/json-patch+json",
        ir::RequestMedia::UrlEncoded => "application/x-www-form-urlencoded",
        ir::RequestMedia::Multipart => "multipart/form-data",
        ir::RequestMedia::OctetStream => "application/octet-stream",
    }
}

const AUTH_GUIDE: &str = "# Authentication\n\n\
Construct a `com.box.sdk.Client` from one of the four Box auth flows. Each is a\n\
`com.box.sdk.runtime.Runtime.Auth` that caches its access token until shortly\n\
before it expires; the network layer refreshes on a `401` and retries once.\n\n\
## Developer Token\n\n\
```java\n\
Client client = new Client(Runtime.developerToken(\"DEVELOPER_TOKEN\"));\n\
```\n\n\
## Client Credentials Grant (server auth, no key)\n\n\
```java\n\
Client client = new Client(Runtime.clientCredentials(\n\
        Runtime.CcgConfig.enterprise(\"CLIENT_ID\", \"CLIENT_SECRET\", \"ENTERPRISE_ID\")));\n\
// or Runtime.CcgConfig.user(\"CLIENT_ID\", \"CLIENT_SECRET\", \"USER_ID\")\n\
```\n\n\
## JWT (server auth with a signing key)\n\n\
```java\n\
// From an app's box_config.json (bad key: fails loudly at construction):\n\
Client client = new Client(Runtime.jwt(Runtime.JwtConfig.fromBoxConfig(boxConfigJson)));\n\
// or build it explicitly:\n\
Runtime.JwtConfig config = Runtime.JwtConfig.enterprise(\n\
        \"CLIENT_ID\", \"CLIENT_SECRET\", \"PUBLIC_KEY_ID\",\n\
        privateKeyPem, keyPassphrase, \"ENTERPRISE_ID\");\n\
Client client = new Client(Runtime.jwt(config));\n\
```\n\n\
## OAuth 2.0 (authorization code)\n\n\
Redirect the user to the consent URL, exchange the returned code, then reuse the\n\
stored (rotated) refresh token on later runs:\n\n\
```java\n\
Runtime.OAuthConfig oauth = new Runtime.OAuthConfig(\"CLIENT_ID\", \"CLIENT_SECRET\");\n\
// first run: redirect to oauth.authorizeUrl(redirectUri, state), then\n\
// Auth auth = oauth.exchangeCode(code, redirectUri);\n\
// later runs: rebuild from the stored refresh token.\n\
Client client = new Client(Runtime.oauth(oauth, storedRefreshToken));\n\
```\n";

const CHUNKED_UPLOAD_GUIDE: &str = "# Chunked upload\n\n\
Large files upload faster through `com.box.sdk.BoxChunkedUpload`, which splits the\n\
content into parts and uploads them **in parallel** (create session → upload each\n\
part with its `Content-Range` and SHA-1 → commit). It uses structured\n\
concurrency, a Java 26 **preview** API, so it — and only it — needs\n\
`--enable-preview` at run time; the rest of the SDK runs on a plain JDK 26.\n\n\
```java\n\
// run with: java --enable-preview ...\n\
var file = new com.box.sdk.BoxChunkedUpload(client)\n\
        .upload(bytes, \"large.bin\", folderId);\n\n\
// or upload a new version of an existing file:\n\
var version = new com.box.sdk.BoxChunkedUpload(client)\n\
        .uploadVersion(bytes, \"large.bin\", fileId);\n\
```\n\n\
Both return the uploaded `Files` object. A failure throws\n\
`com.box.sdk.runtime.Runtime.BoxApiException` like every other call (see the\n\
[errors guide](errors.md)); the first part to fail cancels the rest.\n";

const PAGINATION_GUIDE: &str = "# Pagination\n\n\
Marker- and offset-paginated list operations expose an extra `…Paginate`\n\
method alongside the plain single-page method. It returns an `Iterable` that\n\
threads the cursor for you, so you loop it with an enhanced `for`:\n\n\
```java\n\
for (var item : client.files.getFolderItemsPaginate(folderId, null)) {\n\
    // use item\n\
}\n\
```\n\n\
Pass an options object (or `null`) as the final argument. The paginator stops\n\
when the last page is reached. It is re-iterable: each `iterator()` runs an\n\
independent pass over a private copy of your options, so your options object is\n\
never mutated.\n";

const ERRORS_GUIDE: &str = "# Errors\n\n\
Every I/O method is blocking and returns its value directly. Failures are\n\
thrown as an unchecked `com.box.sdk.runtime.Runtime.BoxApiException` — either a\n\
transport failure or a non-2xx response after the network layer's retries\n\
(exponential backoff + jitter, `401` refresh, `Retry-After`). Because it extends\n\
`RuntimeException`, you catch it only where you mean to handle it:\n\n\
```java\n\
try {\n\
    var file = client.files.getById(fileId, null);\n\
} catch (com.box.sdk.runtime.Runtime.BoxApiException e) {\n\
    // inspect e.getMessage(); the body carries the Box error schema\n\
}\n\
```\n";
