//! NF-8 ship artifact: the Maven packaging scaffold.
//!
//! A `pom.xml` and a short `README.md` that make the generated tree a
//! publishable Maven Central artifact — the Java analogue of the TypeScript npm
//! package (D-167) and the Rust publishable crate (D-169). The SDK is
//! dependency-free (pure JDK), so the POM carries **no** `<dependencies>`; the
//! hand-written runtime is *vendored* over the generated stub at release time
//! (a single-file overwrite, the same self-contained shape Go/Rust/TS ship),
//! not declared as a dependency.
//!
//! `groupId`/`artifactId`/`version` and the project URL are placeholders (the
//! reserved `.invalid` TLD, RFC 2606, so an un-substituted URL can never resolve
//! to a real site); the release pipeline sets the real coordinates, the
//! `MAJOR.MINOR.PATCH` from the FR-9 spec diff, and the repository URL — exactly
//! as the Go module tag and the Rust crate name are set at release.

use crate::{BuildInfo, GeneratedFile};

/// Placeholder Maven coordinates (the release pipeline substitutes the real
/// values, as Go/Rust do for their module path / crate name).
const GROUP_ID: &str = "com.box";
const ARTIFACT_ID: &str = "box-sdk";
const VERSION: &str = "0.1.0";
/// The reserved `.invalid` TLD (RFC 2606) — a placeholder URL that fails safe.
const PROJECT_URL: &str = "https://example.invalid/box-sdk";

/// Emit the Maven packaging files (`pom.xml`, `README.md`).
pub fn generate_ship(build: &BuildInfo) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile {
            path: "pom.xml".to_string(),
            content: pom_xml(build),
        },
        GeneratedFile {
            path: "README.md".to_string(),
            content: readme(),
        },
    ]
}

/// The Maven build file: JDK-only (no dependencies), compiled `--release 26`
/// (the ship-target floor — the runtime uses HTTP/3, a Java 26 API, D-180), with
/// the source + javadoc jars Maven Central requires attached at `package`. Plugin
/// versions are pinned for reproducibility (NF-6).
fn pom_xml(build: &BuildInfo) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!-- Code generated by box-gantry {engine} (spec {fingerprint}). DO NOT EDIT. -->\n\
         <project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n\
         \x20        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\
         \x20        xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n\
         \x20 <modelVersion>4.0.0</modelVersion>\n\
         \n\
         \x20 <groupId>{GROUP_ID}</groupId>\n\
         \x20 <artifactId>{ARTIFACT_ID}</artifactId>\n\
         \x20 <version>{VERSION}</version>\n\
         \x20 <packaging>jar</packaging>\n\
         \n\
         \x20 <name>{ARTIFACT_ID}</name>\n\
         \x20 <description>Generated Box API client for Java.</description>\n\
         \x20 <url>{PROJECT_URL}</url>\n\
         \n\
         \x20 <licenses>\n\
         \x20   <license>\n\
         \x20     <name>MIT License</name>\n\
         \x20     <url>https://opensource.org/licenses/MIT</url>\n\
         \x20   </license>\n\
         \x20 </licenses>\n\
         \n\
         \x20 <developers>\n\
         \x20   <developer>\n\
         \x20     <name>box-gantry</name>\n\
         \x20   </developer>\n\
         \x20 </developers>\n\
         \n\
         \x20 <scm>\n\
         \x20   <url>{PROJECT_URL}</url>\n\
         \x20   <connection>scm:git:{PROJECT_URL}.git</connection>\n\
         \x20   <developerConnection>scm:git:{PROJECT_URL}.git</developerConnection>\n\
         \x20 </scm>\n\
         \n\
         \x20 <properties>\n\
         \x20   <maven.compiler.release>26</maven.compiler.release>\n\
         \x20   <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n\
         \x20 </properties>\n\
         \n\
         \x20 <build>\n\
         \x20   <plugins>\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-compiler-plugin</artifactId>\n\
         \x20       <version>3.13.0</version>\n\
         \x20     </plugin>\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-source-plugin</artifactId>\n\
         \x20       <version>3.3.1</version>\n\
         \x20       <executions>\n\
         \x20         <execution>\n\
         \x20           <id>attach-sources</id>\n\
         \x20           <phase>package</phase>\n\
         \x20           <goals><goal>jar-no-fork</goal></goals>\n\
         \x20         </execution>\n\
         \x20       </executions>\n\
         \x20     </plugin>\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-javadoc-plugin</artifactId>\n\
         \x20       <version>3.11.2</version>\n\
         \x20       <configuration>\n\
         \x20         <doclint>none</doclint>\n\
         \x20         <quiet>true</quiet>\n\
         \x20         <failOnError>false</failOnError>\n\
         \x20       </configuration>\n\
         \x20       <executions>\n\
         \x20         <execution>\n\
         \x20           <id>attach-javadocs</id>\n\
         \x20           <phase>package</phase>\n\
         \x20           <goals><goal>jar</goal></goals>\n\
         \x20         </execution>\n\
         \x20       </executions>\n\
         \x20     </plugin>\n\
         \x20   </plugins>\n\
         \x20 </build>\n\
         </project>\n",
        engine = build.engine,
        fingerprint = build.spec_fingerprint,
    )
}

/// A short package README (NF-8): install coordinates, a first call, and a
/// pointer at the generated `docs/` tree.
fn readme() -> String {
    format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n\
         # {ARTIFACT_ID}\n\
         \n\
         A generated Java client for the Box API — one resource manager per API\n\
         area behind a single `com.box.sdk.Client`, over a dependency-free\n\
         `java.net.http` runtime.\n\
         \n\
         ## Install (Maven)\n\
         \n\
         ```xml\n\
         <dependency>\n\
         \x20 <groupId>{GROUP_ID}</groupId>\n\
         \x20 <artifactId>{ARTIFACT_ID}</artifactId>\n\
         \x20 <version>{VERSION}</version>\n\
         </dependency>\n\
         ```\n\
         \n\
         ## Usage\n\
         \n\
         ```java\n\
         com.box.sdk.Client client = new com.box.sdk.Client(\n\
         \x20       com.box.sdk.runtime.Runtime.developerToken(\"DEVELOPER_TOKEN\"));\n\
         ```\n\
         \n\
         See the `docs/` directory for per-manager reference and the\n\
         authentication, pagination, and errors guides.\n"
    )
}
