//! NF-8 ship artifact: the Maven packaging scaffold.
//!
//! A `pom.xml` and a short `README.md` that make the generated tree a
//! publishable Maven Central artifact — the Java analogue of the TypeScript npm
//! package (D-167) and the Rust publishable crate (D-169). The SDK is
//! dependency-free (pure JDK), so the POM carries **no** `<dependencies>`; the
//! hand-written runtime is *vendored* over the generated stub at release time
//! (a single-file overwrite, the same self-contained shape Go/Rust/TS ship),
//! not declared as a dependency.
//!
//! `groupId`/`artifactId` are the community coordinates `dev.unofficialbox`
//! / `box-open-sdk` — a namespace we verify on Maven Central via the
//! `unofficialbox.dev` domain (DNS), and a name that marks these as distinct
//! from Box's official SDKs. The `version` is set by the release pipeline
//! (`MAJOR.MINOR.PATCH` from the FR-9 spec diff), as the Go module tag is. The
//! generated Java code also lives under the same `dev.unofficialbox` package
//! (D-188), so the SDK is co-installable with Box's official `com.box.sdk`.

use crate::{BuildInfo, GeneratedFile};

/// The published Maven coordinates. The `version` is a default the release
/// pipeline overrides with the FR-9 `MAJOR.MINOR.PATCH` (as Go/Rust do).
const GROUP_ID: &str = "dev.unofficialbox";
const ARTIFACT_ID: &str = "box-open-sdk";
const VERSION: &str = gantry_manifest::SDK_VERSION;
/// The project's GitHub home. Each language ships from its own repository; the
/// `dev.unofficialbox` groupId is verified against the DNS domain, not this URL.
const PROJECT_URL: &str = "https://github.com/unofficialbox/box-open-java-sdk";

/// Emit the Maven packaging files (`pom.xml`, `README.md`).
pub fn generate_ship(build: &BuildInfo) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile {
            path: "pom.xml".to_string(),
            content: pom_xml(build),
        },
        GeneratedFile {
            path: "README.md".to_string(),
            content: readme(),
        },
        // The shared community-design banner the README renders at its top (NF-8).
        GeneratedFile {
            path: "assets/banner.svg".to_string(),
            content: gantry_manifest::banner_svg("Java"),
        },
    ]
}

/// The Maven build file: JDK-only (no dependencies), compiled `--release 26`
/// (the ship-target floor — the runtime uses HTTP/3, a Java 26 API, D-180), with
/// the source + javadoc jars Maven Central requires attached at `package`. Plugin
/// versions are pinned for reproducibility (NF-6).
///
/// A `release` profile carries the GPG signing and Central Portal publishing
/// plugins so `mvn -P release deploy` publishes to Maven Central; it is a
/// profile, not part of the default build, so a plain `mvn package` needs no
/// signing key. Central requires signed artifacts plus the name/description/url/
/// license/developer/scm metadata below — all present here.
fn pom_xml(build: &BuildInfo) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!-- Code generated by box-gantry {engine} (spec {fingerprint}). DO NOT EDIT. -->\n\
         <project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n\
         \x20        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\
         \x20        xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n\
         \x20 <modelVersion>4.0.0</modelVersion>\n\
         \n\
         \x20 <groupId>{GROUP_ID}</groupId>\n\
         \x20 <artifactId>{ARTIFACT_ID}</artifactId>\n\
         \x20 <version>{VERSION}</version>\n\
         \x20 <packaging>jar</packaging>\n\
         \n\
         \x20 <name>{ARTIFACT_ID}</name>\n\
         \x20 <description>Box API client for Java (open source, community, punk rock) — generated, dependency-light, typed models and async managers.</description>\n\
         \x20 <url>{PROJECT_URL}</url>\n\
         \n\
         \x20 <licenses>\n\
         \x20   <license>\n\
         \x20     <name>MIT License</name>\n\
         \x20     <url>https://opensource.org/licenses/MIT</url>\n\
         \x20   </license>\n\
         \x20 </licenses>\n\
         \n\
         \x20 <developers>\n\
         \x20   <developer>\n\
         \x20     <name>box-gantry</name>\n\
         \x20   </developer>\n\
         \x20 </developers>\n\
         \n\
         \x20 <scm>\n\
         \x20   <url>{PROJECT_URL}</url>\n\
         \x20   <connection>scm:git:{PROJECT_URL}.git</connection>\n\
         \x20   <developerConnection>scm:git:{PROJECT_URL}.git</developerConnection>\n\
         \x20 </scm>\n\
         \n\
         \x20 <properties>\n\
         \x20   <maven.compiler.release>26</maven.compiler.release>\n\
         \x20   <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n\
         \x20 </properties>\n\
         \n\
         \x20 <build>\n\
         \x20   <plugins>\n\
         \x20     <!-- Two-pass compile so the core SDK is a plain JDK-26 artifact and\n\
         \x20          only BoxChunkedUpload carries the preview flag (D-183): callers\n\
         \x20          who never touch chunked upload need no preview flag; those who\n\
         \x20          do add enable-preview at run time to unlock the parallel path. -->\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-compiler-plugin</artifactId>\n\
         \x20       <version>3.13.0</version>\n\
         \x20       <executions>\n\
         \x20         <execution>\n\
         \x20           <id>default-compile</id>\n\
         \x20           <configuration>\n\
         \x20             <excludes>\n\
         \x20               <exclude>dev/unofficialbox/BoxChunkedUpload.java</exclude>\n\
         \x20             </excludes>\n\
         \x20           </configuration>\n\
         \x20         </execution>\n\
         \x20         <execution>\n\
         \x20           <id>compile-chunked-upload-preview</id>\n\
         \x20           <phase>compile</phase>\n\
         \x20           <goals><goal>compile</goal></goals>\n\
         \x20           <configuration>\n\
         \x20             <includes>\n\
         \x20               <include>dev/unofficialbox/BoxChunkedUpload.java</include>\n\
         \x20             </includes>\n\
         \x20             <compilerArgs><arg>--enable-preview</arg></compilerArgs>\n\
         \x20           </configuration>\n\
         \x20         </execution>\n\
         \x20       </executions>\n\
         \x20     </plugin>\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-source-plugin</artifactId>\n\
         \x20       <version>3.3.1</version>\n\
         \x20       <executions>\n\
         \x20         <execution>\n\
         \x20           <id>attach-sources</id>\n\
         \x20           <phase>package</phase>\n\
         \x20           <goals><goal>jar-no-fork</goal></goals>\n\
         \x20         </execution>\n\
         \x20       </executions>\n\
         \x20     </plugin>\n\
         \x20     <plugin>\n\
         \x20       <groupId>org.apache.maven.plugins</groupId>\n\
         \x20       <artifactId>maven-javadoc-plugin</artifactId>\n\
         \x20       <version>3.11.2</version>\n\
         \x20       <configuration>\n\
         \x20         <doclint>none</doclint>\n\
         \x20         <quiet>true</quiet>\n\
         \x20         <failOnError>false</failOnError>\n\
         \x20         <release>26</release>\n\
         \x20         <additionalOptions>\n\
         \x20           <additionalOption>--enable-preview</additionalOption>\n\
         \x20         </additionalOptions>\n\
         \x20       </configuration>\n\
         \x20       <executions>\n\
         \x20         <execution>\n\
         \x20           <id>attach-javadocs</id>\n\
         \x20           <phase>package</phase>\n\
         \x20           <goals><goal>jar</goal></goals>\n\
         \x20         </execution>\n\
         \x20       </executions>\n\
         \x20     </plugin>\n\
         \x20   </plugins>\n\
         \x20 </build>\n\
         \n\
         \x20 <!-- `mvn -P release deploy` signs the artifacts and publishes to\n\
         \x20      the Maven Central Portal. Kept in a profile so a plain\n\
         \x20      `mvn package` needs no GPG key. Requires a Central Portal user\n\
         \x20      token under server id `central` in settings.xml, and a GPG\n\
         \x20      secret key on the keyring. -->\n\
         \x20 <profiles>\n\
         \x20   <profile>\n\
         \x20     <id>release</id>\n\
         \x20     <build>\n\
         \x20       <plugins>\n\
         \x20         <plugin>\n\
         \x20           <groupId>org.apache.maven.plugins</groupId>\n\
         \x20           <artifactId>maven-gpg-plugin</artifactId>\n\
         \x20           <version>3.2.7</version>\n\
         \x20           <executions>\n\
         \x20             <execution>\n\
         \x20               <id>sign-artifacts</id>\n\
         \x20               <phase>verify</phase>\n\
         \x20               <goals><goal>sign</goal></goals>\n\
         \x20             </execution>\n\
         \x20           </executions>\n\
         \x20         </plugin>\n\
         \x20         <plugin>\n\
         \x20           <groupId>org.sonatype.central</groupId>\n\
         \x20           <artifactId>central-publishing-maven-plugin</artifactId>\n\
         \x20           <version>0.11.0</version>\n\
         \x20           <extensions>true</extensions>\n\
         \x20           <configuration>\n\
         \x20             <publishingServerId>central</publishingServerId>\n\
         \x20             <!-- true: a validated deployment releases to Central on\n\
         \x20                  upload. Set false to stage it and release by hand\n\
         \x20                  from the Portal instead. -->\n\
         \x20             <autoPublish>true</autoPublish>\n\
         \x20           </configuration>\n\
         \x20         </plugin>\n\
         \x20       </plugins>\n\
         \x20     </build>\n\
         \x20   </profile>\n\
         \x20 </profiles>\n\
         </project>\n",
        engine = build.engine,
        fingerprint = build.spec_fingerprint,
    )
}

/// A short package README (NF-8): install coordinates, a first call, and a
/// pointer at the generated `docs/` tree.
fn readme() -> String {
    // A sentinel + `replace` rather than `format!` so the Java example needs no
    // `{{`/`}}` escaping. The Quickstart is verified to compile with `javac`.
    const TEMPLATE: &str = r##"<!-- Generated by box-gantry. DO NOT EDIT. -->
![Box Open SDK for Java](assets/banner.svg)

# @ARTIFACT@ (Java)

A **community, unofficial** Box API client for Java — one resource manager per
API area behind a single `dev.unofficialbox.Client`, over a dependency-free
`java.net.http` runtime with retry, backoff, and token refresh.

> **Not affiliated with, authorized, or endorsed by Box, Inc.** "Box" is a
> trademark of Box, Inc. This is an independent, generated client.

## Install (Maven)

```xml
<dependency>
  <groupId>@GROUP@</groupId>
  <artifactId>@ARTIFACT@</artifactId>
  <version>@VERSION@</version>
</dependency>
```

## Quickstart

Authenticate, look up the current user, create a folder, upload a file, extract
its fields with Box AI, tag it with metadata, and query for it — end to end.
Request bodies use fluent builders:

```java
import dev.unofficialbox.Client;
import dev.unofficialbox.auth.Auth;
import dev.unofficialbox.runtime.Runtime;
import dev.unofficialbox.model.schemas.*;
import java.util.List;
import java.util.Map;

public final class Quickstart {
    public static void main(String[] args) throws Exception {
        // Client Credentials Grant (server-to-server); developer token, OAuth,
        // and JWT also live in dev.unofficialbox.auth.Auth.
        var client = new Client(Auth.clientCredentials(
            Runtime.CcgConfig.enterprise("CLIENT_ID", "CLIENT_SECRET", "ENTERPRISE_ID")));

        // The current user.
        var me = client.users.getMe(null);
        System.out.println("authenticated as " + me.id());

        // Create a folder at the account root ("0").
        var folder = client.folders.create(
            FolderCreateRequest.builder()
                .name("Invoices")
                .parent(AttributesParent.builder().id("0").build())
                .build(),
            null);

        // Upload a file into it.
        var uploaded = client.uploads.uploadFile(
            FileContentCreateRequest.builder()
                .attributes(PostFileContentAttributes.builder()
                    .name("invoice.pdf")
                    .parent(AttributesParent.builder().id(folder.id()).build())
                    .build())
                .file("<file bytes>".getBytes())
                .build(),
            null);
        var fileId = uploaded.entries().orElseThrow().get(0).id();

        // Extract fields from the file with Box AI.
        var answer = client.ai.extract(
            AiExtract.builder()
                .prompt("Extract the invoice number and total amount.")
                .items(List.of(
                    AiItemBase.builder().id(fileId).type(AiCitationType.FILE).build()))
                .build());
        System.out.println(answer);

        // Attach that metadata to the file (an enterprise template).
        client.fileMetadata.createFileMetadata(
            fileId,
            GetFileIdMetadataIdIdScope.ENTERPRISE,
            "invoiceData",
            Map.of("invoiceNumber", "INV-0042", "total", 1250));

        // Query for files carrying that metadata.
        var results = client.search.queryByMetadata(
            MetadataQuery.builder()
                .from("enterprise_0.invoiceData")
                .ancestorFolderId(folder.id())
                .build());
        System.out.println(results);
    }
}
```

## Parallel chunked upload (opt-in)

The core SDK compiles and runs on a plain JDK 26. `BoxChunkedUpload` uploads a
large file's parts **in parallel** using structured concurrency, a Java 26
**preview** API — so it is a preview-marked class, and code that calls it must
pass `--enable-preview` at **both** compile and run time (with `--release 26` for
`javac`) to unlock the parallel path:

```java
// compile: javac --release 26 --enable-preview ...
// run:     java --enable-preview ...
var file = new dev.unofficialbox.BoxChunkedUpload(client)
        .upload(bytes, "large.bin", folderId);
```

Everything else compiles and runs without the flag.

## Documentation

The [`docs/`](./docs) tree carries the per-manager reference — a call snippet for
every method — and the authentication, pagination, and errors guides.
"##;
    TEMPLATE
        .replace("@ARTIFACT@", ARTIFACT_ID)
        .replace("@GROUP@", GROUP_ID)
        .replace("@VERSION@", VERSION)
}
