//! VR-1.6: generate the full real spec's Java model layer and compile it with
//! the real toolchain — `javac -Xlint:all -Werror` clean. The Java analogue of
//! the Go `go build`, Rust `cargo check`, and TypeScript `tsc --noEmit` gates
//! (TR-Java). Skips cleanly when `javac` is absent (local dev without a JDK);
//! CI installs one, so the gate always runs there.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_java::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_java::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let analysis = gantry_sema::analyze(&lowering.program).unwrap();
    gantry_backend_java::generate(&analysis, &gantry_manifest::java(), &build)
}

/// Write every generated file to disk; return only the `.java` sources (the
/// reference-doc Markdown is written too, but must not be handed to `javac`).
fn write_all(dir: &Path, files: &[gantry_backend_java::GeneratedFile]) -> Vec<PathBuf> {
    let mut sources = Vec::new();
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &file.content).unwrap();
        if file.path.ends_with(".java") {
            sources.push(path);
        }
    }
    sources
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated file carries a do-not-edit header (FR-6.3): Java sources
    // under the Maven source root, and reference docs (FR-7.7) as Markdown under
    // `docs/`.
    for file in &once {
        if file.path == "pom.xml" {
            assert!(
                file.content.starts_with("<?xml"),
                "pom.xml lacks the XML prolog"
            );
        } else if file.path == "README.md" {
            assert!(
                file.content
                    .starts_with("<!-- Generated by box-gantry. DO NOT EDIT. -->"),
                "README.md lacks the do-not-edit header"
            );
        } else if file.path.ends_with(".md") {
            assert!(
                file.path.starts_with("docs/"),
                "unexpected doc path: {}",
                file.path
            );
            assert!(
                file.content
                    .starts_with("<!-- Generated by box-gantry. DO NOT EDIT. -->"),
                "{} lacks the doc header",
                file.path
            );
        } else if file.path == "assets/banner.svg" {
            assert!(
                file.content.starts_with("<svg")
                    && file.content.contains("Box Open SDK for Java"),
                "assets/banner.svg is not the expected community banner"
            );
        } else {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
            assert!(
                (file.path.starts_with("src/main/java/")
                    || file.path.starts_with("src/test/java/"))
                    && file.path.ends_with(".java"),
                "unexpected path: {}",
                file.path
            );
        }
    }
    // The NF-8 ship scaffold (D-179): the Maven build file and the README.
    assert!(once.iter().any(|f| f.path == "pom.xml"));
    assert!(once.iter().any(|f| f.path == "README.md"));
    // The reference docs (FR-7.7): the index, the guides, and per-manager pages.
    assert!(once.iter().any(|f| f.path == "docs/README.md"));
    assert!(once.iter().any(|f| f.path == "docs/auth.md"));
    assert!(once.iter().any(|f| f.path == "docs/pagination.md"));
    assert!(once.iter().any(|f| f.path == "docs/errors.md"));
    // The chunked-upload guide ships with the orchestrator (the real spec has it).
    let chunked_guide = once.iter().find(|f| f.path == "docs/chunked-upload.md");
    assert!(
        chunked_guide.is_some(),
        "the chunked-upload guide should ship alongside BoxChunkedUpload on the real spec"
    );
    assert!(
        chunked_guide.unwrap().content.contains("BoxChunkedUpload")
            && chunked_guide.unwrap().content.contains("--enable-preview"),
        "the chunked-upload guide should name the class and the opt-in preview flag"
    );
    // …and the index links it.
    let index = once.iter().find(|f| f.path == "docs/README.md").unwrap();
    assert!(
        index
            .content
            .contains("[Chunked upload](chunked-upload.md)"),
        "the docs index should link the chunked-upload guide"
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md"))
    );
    // The support + provenance scaffold and at least one model file are present.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/core/Tristate.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/BuildInfo.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("src/main/java/dev/unofficialbox/model/"))
    );
    // The manager/client/runtime layer (D-173): the runtime stub, the SDK
    // entry point, the helper, and at least one manager.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/runtime/Runtime.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/Client.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/internal/Internal.java")
    );
    assert!(once.iter().any(|f| {
        f.path
            .starts_with("src/main/java/dev/unofficialbox/managers/")
    }));
}

/// VR-1.6: the whole generated model tree compiles `javac -Xlint:all -Werror`
/// clean on the real Box spec. `-Werror` makes any lint a hard failure, the
/// Java analogue of `clippy -D warnings` / `tsc` strict. Compiled with
/// `--release 26` — the ship-target floor: the runtime now uses HTTP/3 (D-180),
/// a Java 26 API, so the whole artifact requires JDK 26 (the roadmap's planned
/// "Java-26-mandatory" step). CI runs it under the Corretto 26 toolchain.
#[test]
fn the_generated_model_layer_compiles_under_javac() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());
    // The core SDK is preview-free: BoxChunkedUpload (structured concurrency, a
    // preview API) is excluded here and gated separately (D-183), so this gate
    // proves the rest of the SDK compiles on a plain JDK 26.
    sources.retain(|p| !p.ends_with("BoxChunkedUpload.java"));

    // A smoke driver that constructs the public `Client` from an auth flow, so
    // the whole manager/client surface (D-173) has to type-check as a callable
    // API, not just internally. (It is compiled, never run — the stub session
    // throws at construction.)
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static dev.unofficialbox.Client build(dev.unofficialbox.runtime.Runtime.Auth auth) {\n\
         \x20       return new dev.unofficialbox.Client(auth);\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    // Pass the (900+) sources via an argfile so the command never overflows the
    // OS argument limit.
    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("26")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "javac --release 26 -Xlint:all -Werror failed (VR-1.6):\n{log}"
    );
}

/// FR-5.2: the generated SDK compiles against the **real** hand-written runtime,
/// not just the stub — proving the stub and the runtime can't drift. The Java
/// analogue of the Rust "swap the runtime module and `cargo check`" and the
/// TypeScript "copy the real runtime source and `tsc`" gates. Because the Java
/// runtime is one dependency-free file, the swap is a single-file overwrite: the
/// real `Runtime.java` drops over the generated stub at the same package path,
/// and a smoke driver builds the `Client` from a real auth factory so the whole
/// manager/client tree type-checks against the runtime.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-swap-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());
    // The core SDK is preview-free: BoxChunkedUpload (structured concurrency, a
    // preview API) is excluded here and gated separately (D-183), so this gate
    // proves the rest of the SDK compiles on a plain JDK 26.
    sources.retain(|p| !p.ends_with("BoxChunkedUpload.java"));

    // Swap the generated stub for the real runtime (same package + class name).
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(
        "../../runtimes/java/gantryruntime/src/main/java/dev/unofficialbox/runtime/Runtime.java",
    );
    let stub = dir.join("src/main/java/dev/unofficialbox/runtime/Runtime.java");
    assert!(
        stub.exists(),
        "the generated stub runtime should exist to be swapped"
    );
    std::fs::copy(&real_runtime, &stub).expect("copy the real runtime over the stub");

    // A smoke driver: build the real `Client` from a real auth factory, so the
    // manager surface type-checks against the runtime (the Rust/TS swap pattern).
    // It also drives a paginator through the public `for (var … : list…(…))`
    // idiom (FR-7.3, Option A), so the whole paged path — Client field → the
    // auto-paging list method → `Iterable<Element>` → element type — type-checks
    // against the real runtime.
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static dev.unofficialbox.Client build() {\n\
         \x20       return new dev.unofficialbox.Client(dev.unofficialbox.runtime.Runtime.developerToken(\"dev\"));\n\
         \x20   }\n\
         \x20   public static int countAgents() {\n\
         \x20       int _n = 0;\n\
         \x20       for (var agent : build().aiStudio.listAiAgents(\n\
         \x20               new dev.unofficialbox.managers.AiStudioManager.ListAiAgentsOptions())) {\n\
         \x20           if (agent != null) {\n\
         \x20               _n++;\n\
         \x20           }\n\
         \x20       }\n\
         \x20       return _n;\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("26")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "the generated SDK failed to compile against the real runtime (FR-5.2):\n{log}"
    );
}

/// FR-7.3: every paged operation gets a `<Prefix><Method>Paginator` class in the
/// managers package. On the real Box spec `detect_pagination` finds 64 paged
/// operations (matching the Go/Rust/TS backends); each synthesizes a paginator
/// (no cursor shape falls back on the real spec). The `javac -Werror` gate above
/// already compiles them — this asserts they are actually emitted and shaped as
/// single-pass `Iterable`s.
#[test]
fn paginators_are_generated() {
    let files = generate();
    let paginators: Vec<_> = files
        .iter()
        .filter(|f| f.path.ends_with("Paginator.java"))
        .collect();
    assert_eq!(
        paginators.len(),
        64,
        "expected one paginator per paged operation on the real spec"
    );
    for file in &paginators {
        assert!(
            file.path
                .starts_with("src/main/java/dev/unofficialbox/managers/"),
            "paginator not in the managers package: {}",
            file.path
        );
        assert!(
            file.content.contains("implements java.lang.Iterable<"),
            "paginator {} should be an Iterable",
            file.path
        );
        assert!(
            file.content.contains("public java.util.Iterator<"),
            "paginator {} should expose iterator()",
            file.path
        );
    }
    // Both cursor styles are exercised on the real spec: marker paginators
    // thread a `next_marker`, offset paginators advance by the page length.
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("_cursor += _items.size()")),
        "expected at least one offset-style paginator"
    );
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("!_next.isEmpty()")),
        "expected at least one marker-style paginator"
    );
}

/// FR-7.7: the reference docs describe the real Java surface — per-manager pages
/// with the actual class/field/method names, plus the three cross-cutting
/// guides. Generated from the same IR as the code, so they can't drift.
#[test]
fn reference_docs_describe_the_java_surface() {
    let files = generate();
    let doc = |path: &str| {
        files
            .iter()
            .find(|f| f.path == path)
            .unwrap_or_else(|| panic!("missing doc {path}"))
            .content
            .clone()
    };

    // The index links every manager by its real `Client` field.
    let readme = doc("docs/README.md");
    assert!(readme.contains("# Box SDK reference"), "{readme}");
    assert!(
        readme.contains("[FilesManager](managers/FilesManager.md) | `client.files` |"),
        "{readme}"
    );

    // A per-manager page names the real class and points at the runtime error.
    let files_page = doc("docs/managers/FilesManager.md");
    assert!(files_page.contains("# FilesManager"), "{files_page}");
    assert!(
        files_page.contains("Runtime.BoxApiException"),
        "{files_page}"
    );
    // A manager page documents a paged operation as an auto-paging Iterable.
    assert!(
        files.iter().any(|f| f.path.starts_with("docs/managers/")
            && f.content.contains("returns an auto-paging `Iterable`")),
        "expected a paged operation to document its paginator in the docs"
    );

    // The guides are Java-flavored with real call sites.
    let auth = doc("docs/auth.md");
    assert!(
        auth.contains("new Client(Runtime.developerToken(\"DEVELOPER_TOKEN\"))"),
        "{auth}"
    );
    assert!(auth.contains("Runtime.JwtConfig.fromBoxConfig("), "{auth}");
    let pagination = doc("docs/pagination.md");
    assert!(
        pagination.contains("for (var item : client.folders.listItems(folderId, null))"),
        "{pagination}"
    );
    let errors = doc("docs/errors.md");
    assert!(errors.contains("BoxApiException"), "{errors}");
    let chunked = doc("docs/chunked-upload.md");
    assert!(
        chunked.contains("new dev.unofficialbox.BoxChunkedUpload(client)")
            && chunked.contains(".upload(bytes, \"large.bin\", folderId)"),
        "{chunked}"
    );
}

/// FR-7.8 / VR-4: the generated behavioral tests compile and **run** clean under
/// the real toolchain — the Java analogue of the Rust `cargo test` (D-156) and
/// TypeScript `node --test` (D-166) gates. There is no built-in test framework,
/// so `GeneratedTests` is a plain `main` that exits non-zero on the first failed
/// check; this gate compiles the whole SDK plus the test class and runs it.
#[test]
fn the_generated_behavioral_tests_pass_under_java() {
    if Command::new("javac").arg("-version").output().is_err()
        || Command::new("java").arg("-version").output().is_err()
    {
        eprintln!("SKIPPED: JDK not available; CI installs one and runs this gate");
        return;
    }
    let files = generate();
    assert!(
        files
            .iter()
            .any(|f| f.path == "src/test/java/dev/unofficialbox/GeneratedTests.java"),
        "the generated behavioral-test class should be emitted"
    );

    let dir = std::env::temp_dir().join(format!("gantry-java-bt-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &files);
    // Core SDK is preview-free — exclude the one preview class (D-183).
    sources.retain(|p| !p.ends_with("BoxChunkedUpload.java"));

    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let classes = dir.join("classes");
    std::fs::create_dir_all(&classes).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("26")
        .arg("-d")
        .arg(&classes)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    assert!(
        javac.status.success(),
        "generated tests failed to compile:\n{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr),
    );

    let run = Command::new("java")
        // The core SDK does NOT require --enable-preview (D-183): BoxChunkedUpload,
        // the only preview-API class, is excluded from this gate — so the core
        // compiles and runs on a plain JDK 26.
        .arg("-cp")
        .arg(&classes)
        .arg("dev.unofficialbox.GeneratedTests")
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&run.stdout);
    let stderr = String::from_utf8_lossy(&run.stderr);
    let ok = run.status.success();
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok && stdout.contains("OK:"),
        "generated behavioral tests failed (FR-7.8, VR-4):\n{stdout}{stderr}"
    );
}

/// NF-8: the generated tree is a publishable Maven artifact. The Java analogue
/// of the Rust `cargo publish --dry-run` (D-169) and TypeScript `npm publish
/// --dry-run` (D-167) ship gates. The SDK is dependency-free, so the assembly is
/// just the single-file runtime vendoring the swap test already does — copy the
/// real `Runtime.java` over the generated stub — after which `mvn package` must
/// build the main + sources + javadoc jars Maven Central requires. Skips cleanly
/// when Maven is absent (like the `javac` gate); CI installs it.
#[test]
fn the_generated_sdk_packages_for_publish() {
    if Command::new("mvn").arg("-version").output().is_err() {
        eprintln!("SKIPPED: mvn not available; CI installs Maven and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-pkg-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    // Write the whole tree (Java + docs + pom.xml + README.md).
    for file in &generate() {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &file.content).unwrap();
    }

    // Vendor the hand-written runtime over the generated stub (the ship shape
    // Go/Rust/TS use), so the jar is self-contained with no unpublished dep.
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(
        "../../runtimes/java/gantryruntime/src/main/java/dev/unofficialbox/runtime/Runtime.java",
    );
    let stub = dir.join("src/main/java/dev/unofficialbox/runtime/Runtime.java");
    assert!(
        stub.exists(),
        "the generated stub runtime should exist to vendor over"
    );
    std::fs::copy(&real_runtime, &stub).expect("vendor the real runtime over the stub");

    let mvn = Command::new("mvn")
        .current_dir(&dir)
        .arg("-B")
        .arg("-ntp")
        .arg("-q")
        .arg("package")
        .output()
        .unwrap();
    let ok = mvn.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&mvn.stdout),
        String::from_utf8_lossy(&mvn.stderr)
    );
    // Maven Central requires the artifact + sources + javadoc jars.
    let target = dir.join("target");
    let v = gantry_manifest::SDK_VERSION;
    let jars = [
        format!("box-open-sdk-{v}.jar"),
        format!("box-open-sdk-{v}-sources.jar"),
        format!("box-open-sdk-{v}-javadoc.jar"),
    ];
    let missing: Vec<&str> = jars
        .iter()
        .map(String::as_str)
        .filter(|j| !target.join(j).exists())
        .collect();
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok && missing.is_empty(),
        "mvn package failed to produce a publishable artifact (NF-8); missing {missing:?}:\n{log}"
    );
}

/// D-183: the chunked-upload orchestrator uploads a large file's parts *in
/// parallel* (structured concurrency, a preview API) and reassembles correctly.
/// A mock `HttpServer` implements the three-step Box protocol; the driver points
/// the SDK at it via the `-Dbox.baseUrl.*` override, runs `BoxChunkedUpload`, and
/// asserts every part arrived, the bytes reassemble, and the peak in-flight PUT
/// count proves the fan-out (`CHUNKED_OK`). The whole tree compiles/runs under
/// `--enable-preview`.
#[test]
fn the_chunked_upload_runs_parts_in_parallel() {
    if Command::new("javac").arg("-version").output().is_err()
        || Command::new("java").arg("-version").output().is_err()
    {
        eprintln!("SKIPPED: JDK not available; CI installs one and runs this gate");
        return;
    }
    let files = generate();
    assert!(
        files
            .iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/BoxChunkedUpload.java"),
        "the chunked-upload orchestrator should be emitted for the real spec"
    );

    let dir = std::env::temp_dir().join(format!("gantry-java-chunk-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &files);

    // Vendor the real runtime over the stub (the orchestrator needs a live session).
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(
        "../../runtimes/java/gantryruntime/src/main/java/dev/unofficialbox/runtime/Runtime.java",
    );
    std::fs::copy(
        &real_runtime,
        dir.join("src/main/java/dev/unofficialbox/runtime/Runtime.java"),
    )
    .unwrap();

    let driver = dir.join("ChunkedSmoke.java");
    std::fs::write(&driver, CHUNKED_SMOKE).unwrap();
    sources.push(driver);

    let argfile = dir.join("sources.txt");
    std::fs::write(
        &argfile,
        sources
            .iter()
            .map(|p| p.to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("\n"),
    )
    .unwrap();
    let classes = dir.join("classes");
    std::fs::create_dir_all(&classes).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("26")
        .arg("--enable-preview")
        .arg("-d")
        .arg(&classes)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    assert!(
        javac.status.success(),
        "chunked-upload SDK failed to compile:\n{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr),
    );

    let run = Command::new("java")
        .arg("--enable-preview")
        .arg("-cp")
        .arg(&classes)
        .arg("ChunkedSmoke")
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&run.stdout);
    let stderr = String::from_utf8_lossy(&run.stderr);
    let ok = run.status.success();
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok && stdout.contains("CHUNKED_OK"),
        "chunked upload did not complete (D-183):\n{stdout}{stderr}"
    );
}

/// The chunked-upload behavioral driver: mocks the Box protocol and drives
/// `BoxChunkedUpload`. Compiled + run only by the gate above.
const CHUNKED_SMOKE: &str = r#"import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpExchange;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

/** Mock the Box chunked-upload protocol and drive BoxChunkedUpload end to end. */
public final class ChunkedSmoke {
    static final Map<Integer, byte[]> received = new TreeMap<>();
    static final AtomicInteger inFlight = new AtomicInteger();
    static final AtomicInteger peak = new AtomicInteger();
    static final AtomicInteger puts = new AtomicInteger();
    static final AtomicReference<String> commitBody = new AtomicReference<>();

    static void reply(HttpExchange ex, int code, String body) throws Exception {
        byte[] b = body.getBytes(StandardCharsets.UTF_8);
        ex.sendResponseHeaders(code, b.length);
        try (OutputStream os = ex.getResponseBody()) {
            os.write(b);
        }
    }

    public static void main(String[] args) throws Exception {
        byte[] content = "ABCDEFGHIJKLMNOPQRSTUVW".getBytes(StandardCharsets.UTF_8); // 23 bytes
        HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        ExecutorService exec = Executors.newFixedThreadPool(8); // part PUTs handled concurrently
        server.setExecutor(exec);
        server.createContext("/files/upload_sessions", ex -> {
            try {
                String path = ex.getRequestURI().getPath();
                String method = ex.getRequestMethod();
                if (method.equals("POST") && path.equals("/files/upload_sessions")) {
                    reply(ex, 201, "{\"id\":\"SID\",\"part_size\":5,\"total_parts\":5}");
                } else if (method.equals("PUT")) {
                    int now = inFlight.incrementAndGet();
                    peak.getAndUpdate(p -> Math.max(p, now));
                    puts.incrementAndGet();
                    String range = ex.getRequestHeaders().getFirst("Content-range");
                    String nums = range.substring(range.indexOf(' ') + 1, range.indexOf('/'));
                    int start = Integer.parseInt(nums.substring(0, nums.indexOf('-')));
                    byte[] body = ex.getRequestBody().readAllBytes();
                    synchronized (received) {
                        received.put(start, body);
                    }
                    Thread.sleep(60); // hold so overlap is observable
                    inFlight.decrementAndGet();
                    reply(ex, 200, "{\"part\":{\"part_id\":\"p" + start + "\",\"offset\":" + start
                            + ",\"size\":" + body.length + ",\"sha1\":\"x\"}}");
                } else if (method.equals("POST") && path.endsWith("/commit")) {
                    commitBody.set(new String(ex.getRequestBody().readAllBytes(), StandardCharsets.UTF_8));
                    reply(ex, 201, "{\"total_count\":1,\"entries\":[{\"id\":\"FID\"}]}");
                } else {
                    reply(ex, 404, "{}");
                }
            } catch (Exception e) {
                try {
                    reply(ex, 500, e.toString());
                } catch (Exception ignored) {
                }
            }
        });
        server.start();
        try {
            int port = server.getAddress().getPort();
            System.setProperty("box.baseUrl.upload", "http://127.0.0.1:" + port);
            System.setProperty("box.baseUrl.upload_session", "http://127.0.0.1:" + port);

            dev.unofficialbox.Client client =
                    new dev.unofficialbox.Client(dev.unofficialbox.runtime.Runtime.developerToken("t"));
            dev.unofficialbox.model.schemas.Files result =
                    new dev.unofficialbox.BoxChunkedUpload(client).upload(content, "big.bin", "0");

            check(puts.get() == 5, "expected 5 part PUTs, got " + puts.get());
            ByteArrayOutputStream reassembled = new ByteArrayOutputStream();
            synchronized (received) {
                for (byte[] b : received.values()) {
                    reassembled.write(b);
                }
            }
            check(Arrays.equals(reassembled.toByteArray(), content), "reassembled content mismatch");
            check(result.entries().orElseThrow().size() == 1, "commit should return one file");
            check(peak.get() >= 2, "parts should upload in parallel; peak concurrency was " + peak.get());
            // The commit body lists parts in ascending offset order (fork-order read).
            String body = commitBody.get();
            check(body != null && body.indexOf("\"offset\":0") >= 0
                    && body.indexOf("\"offset\":0") < body.indexOf("\"offset\":20"),
                    "committed parts should be in offset order: " + body);
            System.out.println("CHUNKED_OK parts=" + puts.get() + " peak=" + peak.get());
        } finally {
            // The mock server's executor threads are non-daemon; shut them down so
            // the JVM exits even when an assertion above fails (never hang CI).
            server.stop(0);
            exec.shutdownNow();
        }
    }

    static void check(boolean cond, String message) {
        if (!cond) {
            throw new AssertionError(message);
        }
    }
}
"#;

/// D-192: the shipped tree must carry the real runtime, never the
/// compile-only contract stub. Every other gate here proves the output
/// *compiles* — which the stub does, while panicking on every call. This is
/// the one that proves it *works*.
#[test]
fn no_generated_file_ships_the_runtime_stub() {
    let files = generate();
    let findings = gantry_verify::shipping::stub_findings(
        files.iter().map(|f| (f.path.as_str(), f.content.as_str())),
    );
    assert!(
        findings.is_empty(),
        "generated SDK ships runtime stubs instead of the vendored runtime: {findings:#?}"
    );
    // The runtime is actually present, so an empty result can't mean
    // "nothing was emitted".
    assert!(
        files
            .iter()
            .any(|f| f.path == "src/main/java/dev/unofficialbox/runtime/Runtime.java"),
        "expected the vendored runtime at src/main/java/dev/unofficialbox/runtime/Runtime.java"
    );
}
