//! VR-1.6: generate the full real spec's Java model layer and compile it with
//! the real toolchain — `javac -Xlint:all -Werror` clean. The Java analogue of
//! the Go `go build`, Rust `cargo check`, and TypeScript `tsc --noEmit` gates
//! (TR-Java). Skips cleanly when `javac` is absent (local dev without a JDK);
//! CI installs one, so the gate always runs there.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_java::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_java::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let analysis = gantry_sema::analyze(&lowering.program).unwrap();
    gantry_backend_java::generate(&analysis, &gantry_manifest::java(), &build)
}

/// Write every generated file to disk; return only the `.java` sources (the
/// reference-doc Markdown is written too, but must not be handed to `javac`).
fn write_all(dir: &Path, files: &[gantry_backend_java::GeneratedFile]) -> Vec<PathBuf> {
    let mut sources = Vec::new();
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &file.content).unwrap();
        if file.path.ends_with(".java") {
            sources.push(path);
        }
    }
    sources
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated file carries a do-not-edit header (FR-6.3): Java sources
    // under the Maven source root, and reference docs (FR-7.7) as Markdown under
    // `docs/`.
    for file in &once {
        if file.path == "pom.xml" {
            assert!(
                file.content.starts_with("<?xml"),
                "pom.xml lacks the XML prolog"
            );
        } else if file.path == "README.md" {
            assert!(
                file.content
                    .starts_with("<!-- Generated by box-gantry. DO NOT EDIT. -->"),
                "README.md lacks the do-not-edit header"
            );
        } else if file.path.ends_with(".md") {
            assert!(
                file.path.starts_with("docs/"),
                "unexpected doc path: {}",
                file.path
            );
            assert!(
                file.content
                    .starts_with("<!-- Generated by box-gantry. DO NOT EDIT. -->"),
                "{} lacks the doc header",
                file.path
            );
        } else {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
            assert!(
                (file.path.starts_with("src/main/java/")
                    || file.path.starts_with("src/test/java/"))
                    && file.path.ends_with(".java"),
                "unexpected path: {}",
                file.path
            );
        }
    }
    // The NF-8 ship scaffold (D-179): the Maven build file and the README.
    assert!(once.iter().any(|f| f.path == "pom.xml"));
    assert!(once.iter().any(|f| f.path == "README.md"));
    // The reference docs (FR-7.7): the index, the guides, and per-manager pages.
    assert!(once.iter().any(|f| f.path == "docs/README.md"));
    assert!(once.iter().any(|f| f.path == "docs/auth.md"));
    assert!(once.iter().any(|f| f.path == "docs/pagination.md"));
    assert!(once.iter().any(|f| f.path == "docs/errors.md"));
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md"))
    );
    // The support + provenance scaffold and at least one model file are present.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/core/Tristate.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/BuildInfo.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("src/main/java/com/box/sdk/model/"))
    );
    // The manager/client/runtime layer (D-173): the runtime stub, the SDK
    // entry point, the helper, and at least one manager.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/runtime/Runtime.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/Client.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/internal/Internal.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("src/main/java/com/box/sdk/managers/"))
    );
}

/// VR-1.6: the whole generated model tree compiles `javac -Xlint:all -Werror`
/// clean on the real Box spec. `-Werror` makes any lint a hard failure, the
/// Java analogue of `clippy -D warnings` / `tsc` strict. Compiled with
/// `--release 21` so the gate enforces the documented compatibility floor (the
/// model layer uses only stable features) regardless of the host JDK — CI runs
/// it under the Corretto 26 ship-target toolchain, contributors under whatever
/// JDK ≥ 21 they have.
#[test]
fn the_generated_model_layer_compiles_under_javac() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());

    // A smoke driver that constructs the public `Client` from an auth flow, so
    // the whole manager/client surface (D-173) has to type-check as a callable
    // API, not just internally. (It is compiled, never run — the stub session
    // throws at construction.)
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static com.box.sdk.Client build(com.box.sdk.runtime.Runtime.Auth auth) {\n\
         \x20       return new com.box.sdk.Client(auth);\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    // Pass the (900+) sources via an argfile so the command never overflows the
    // OS argument limit.
    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("21")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "javac --release 21 -Xlint:all -Werror failed (VR-1.6):\n{log}"
    );
}

/// FR-5.2: the generated SDK compiles against the **real** hand-written runtime,
/// not just the stub — proving the stub and the runtime can't drift. The Java
/// analogue of the Rust "swap the runtime module and `cargo check`" and the
/// TypeScript "copy the real runtime source and `tsc`" gates. Because the Java
/// runtime is one dependency-free file, the swap is a single-file overwrite: the
/// real `Runtime.java` drops over the generated stub at the same package path,
/// and a smoke driver builds the `Client` from a real auth factory so the whole
/// manager/client tree type-checks against the runtime.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-swap-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());

    // Swap the generated stub for the real runtime (same package + class name).
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../runtimes/java/gantryruntime/src/main/java/com/box/sdk/runtime/Runtime.java");
    let stub = dir.join("src/main/java/com/box/sdk/runtime/Runtime.java");
    assert!(
        stub.exists(),
        "the generated stub runtime should exist to be swapped"
    );
    std::fs::copy(&real_runtime, &stub).expect("copy the real runtime over the stub");

    // A smoke driver: build the real `Client` from a real auth factory, so the
    // manager surface type-checks against the runtime (the Rust/TS swap pattern).
    // It also drives a paginator through the public `for (var … : …Paginate(…))`
    // idiom (FR-7.3), so the whole paged path — Client field → paginate method →
    // `Iterable<Element>` → element type — type-checks against the real runtime.
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static com.box.sdk.Client build() {\n\
         \x20       return new com.box.sdk.Client(com.box.sdk.runtime.Runtime.developerToken(\"dev\"));\n\
         \x20   }\n\
         \x20   public static int countAgents() {\n\
         \x20       int _n = 0;\n\
         \x20       for (var agent : build().aiStudio.getAiAgentsPaginate(\n\
         \x20               new com.box.sdk.managers.AiStudioManager.GetAiAgentsOptions())) {\n\
         \x20           if (agent != null) {\n\
         \x20               _n++;\n\
         \x20           }\n\
         \x20       }\n\
         \x20       return _n;\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("21")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "the generated SDK failed to compile against the real runtime (FR-5.2):\n{log}"
    );
}

/// FR-7.3: every paged operation gets a `<Prefix><Method>Paginator` class in the
/// managers package. On the real Box spec `detect_pagination` finds 64 paged
/// operations (matching the Go/Rust/TS backends); each synthesizes a paginator
/// (no cursor shape falls back on the real spec). The `javac -Werror` gate above
/// already compiles them — this asserts they are actually emitted and shaped as
/// single-pass `Iterable`s.
#[test]
fn paginators_are_generated() {
    let files = generate();
    let paginators: Vec<_> = files
        .iter()
        .filter(|f| f.path.ends_with("Paginator.java"))
        .collect();
    assert_eq!(
        paginators.len(),
        64,
        "expected one paginator per paged operation on the real spec"
    );
    for file in &paginators {
        assert!(
            file.path.starts_with("src/main/java/com/box/sdk/managers/"),
            "paginator not in the managers package: {}",
            file.path
        );
        assert!(
            file.content.contains("implements java.lang.Iterable<"),
            "paginator {} should be an Iterable",
            file.path
        );
        assert!(
            file.content.contains("public java.util.Iterator<"),
            "paginator {} should expose iterator()",
            file.path
        );
    }
    // Both cursor styles are exercised on the real spec: marker paginators
    // thread a `next_marker`, offset paginators advance by the page length.
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("_cursor += _items.size()")),
        "expected at least one offset-style paginator"
    );
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("!_next.isEmpty()")),
        "expected at least one marker-style paginator"
    );
}

/// FR-7.7: the reference docs describe the real Java surface — per-manager pages
/// with the actual class/field/method names, plus the three cross-cutting
/// guides. Generated from the same IR as the code, so they can't drift.
#[test]
fn reference_docs_describe_the_java_surface() {
    let files = generate();
    let doc = |path: &str| {
        files
            .iter()
            .find(|f| f.path == path)
            .unwrap_or_else(|| panic!("missing doc {path}"))
            .content
            .clone()
    };

    // The index links every manager by its real `Client` field.
    let readme = doc("docs/README.md");
    assert!(readme.contains("# Box SDK reference"), "{readme}");
    assert!(
        readme.contains("[FilesManager](managers/FilesManager.md) | `client.files` |"),
        "{readme}"
    );

    // A per-manager page names the real class and points at the runtime error.
    let files_page = doc("docs/managers/FilesManager.md");
    assert!(files_page.contains("# FilesManager"), "{files_page}");
    assert!(
        files_page.contains("Runtime.BoxApiException"),
        "{files_page}"
    );
    // Some manager page points a paged operation at its `…Paginate` variant.
    assert!(
        files.iter().any(|f| f.path.starts_with("docs/managers/")
            && f.content.contains("Paginate(...)`, returning an")),
        "expected a paged operation to link its paginator in the docs"
    );

    // The guides are Java-flavored with real call sites.
    let auth = doc("docs/auth.md");
    assert!(
        auth.contains("new Client(Runtime.developerToken(\"DEVELOPER_TOKEN\"))"),
        "{auth}"
    );
    assert!(auth.contains("Runtime.JwtConfig.fromBoxConfig("), "{auth}");
    let pagination = doc("docs/pagination.md");
    assert!(
        pagination.contains("for (var item : client.files.getFolderItemsPaginate(folderId, null))"),
        "{pagination}"
    );
    let errors = doc("docs/errors.md");
    assert!(errors.contains("BoxApiException"), "{errors}");
}

/// FR-7.8 / VR-4: the generated behavioral tests compile and **run** clean under
/// the real toolchain — the Java analogue of the Rust `cargo test` (D-156) and
/// TypeScript `node --test` (D-166) gates. There is no built-in test framework,
/// so `GeneratedTests` is a plain `main` that exits non-zero on the first failed
/// check; this gate compiles the whole SDK plus the test class and runs it.
#[test]
fn the_generated_behavioral_tests_pass_under_java() {
    if Command::new("javac").arg("-version").output().is_err()
        || Command::new("java").arg("-version").output().is_err()
    {
        eprintln!("SKIPPED: JDK not available; CI installs one and runs this gate");
        return;
    }
    let files = generate();
    assert!(
        files
            .iter()
            .any(|f| f.path == "src/test/java/com/box/sdk/GeneratedTests.java"),
        "the generated behavioral-test class should be emitted"
    );

    let dir = std::env::temp_dir().join(format!("gantry-java-bt-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let sources = write_all(&dir, &files);

    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let classes = dir.join("classes");
    std::fs::create_dir_all(&classes).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("21")
        .arg("-d")
        .arg(&classes)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    assert!(
        javac.status.success(),
        "generated tests failed to compile:\n{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr),
    );

    let run = Command::new("java")
        .arg("-cp")
        .arg(&classes)
        .arg("com.box.sdk.GeneratedTests")
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&run.stdout);
    let stderr = String::from_utf8_lossy(&run.stderr);
    let ok = run.status.success();
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok && stdout.contains("OK:"),
        "generated behavioral tests failed (FR-7.8, VR-4):\n{stdout}{stderr}"
    );
}

/// NF-8: the generated tree is a publishable Maven artifact. The Java analogue
/// of the Rust `cargo publish --dry-run` (D-169) and TypeScript `npm publish
/// --dry-run` (D-167) ship gates. The SDK is dependency-free, so the assembly is
/// just the single-file runtime vendoring the swap test already does — copy the
/// real `Runtime.java` over the generated stub — after which `mvn package` must
/// build the main + sources + javadoc jars Maven Central requires. Skips cleanly
/// when Maven is absent (like the `javac` gate); CI installs it.
#[test]
fn the_generated_sdk_packages_for_publish() {
    if Command::new("mvn").arg("-version").output().is_err() {
        eprintln!("SKIPPED: mvn not available; CI installs Maven and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-pkg-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    // Write the whole tree (Java + docs + pom.xml + README.md).
    for file in &generate() {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &file.content).unwrap();
    }

    // Vendor the hand-written runtime over the generated stub (the ship shape
    // Go/Rust/TS use), so the jar is self-contained with no unpublished dep.
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../runtimes/java/gantryruntime/src/main/java/com/box/sdk/runtime/Runtime.java");
    let stub = dir.join("src/main/java/com/box/sdk/runtime/Runtime.java");
    assert!(
        stub.exists(),
        "the generated stub runtime should exist to vendor over"
    );
    std::fs::copy(&real_runtime, &stub).expect("vendor the real runtime over the stub");

    let mvn = Command::new("mvn")
        .current_dir(&dir)
        .arg("-B")
        .arg("-ntp")
        .arg("-q")
        .arg("package")
        .output()
        .unwrap();
    let ok = mvn.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&mvn.stdout),
        String::from_utf8_lossy(&mvn.stderr)
    );
    // Maven Central requires the artifact + sources + javadoc jars.
    let target = dir.join("target");
    let jars = [
        "box-sdk-0.1.0.jar",
        "box-sdk-0.1.0-sources.jar",
        "box-sdk-0.1.0-javadoc.jar",
    ];
    let missing: Vec<&str> = jars
        .iter()
        .copied()
        .filter(|j| !target.join(j).exists())
        .collect();
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok && missing.is_empty(),
        "mvn package failed to produce a publishable artifact (NF-8); missing {missing:?}:\n{log}"
    );
}
