//! VR-1.6: generate the full real spec's Java model layer and compile it with
//! the real toolchain — `javac -Xlint:all -Werror` clean. The Java analogue of
//! the Go `go build`, Rust `cargo check`, and TypeScript `tsc --noEmit` gates
//! (TR-Java). Skips cleanly when `javac` is absent (local dev without a JDK);
//! CI installs one, so the gate always runs there.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_java::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_java::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let analysis = gantry_sema::analyze(&lowering.program).unwrap();
    gantry_backend_java::generate(&analysis, &gantry_manifest::java(), &build)
}

fn write_all(dir: &Path, files: &[gantry_backend_java::GeneratedFile]) -> Vec<PathBuf> {
    let mut written = Vec::new();
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &file.content).unwrap();
        written.push(path);
    }
    written
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated Java file carries the do-not-edit header (FR-6.3) and
    // sits under the Maven source root.
    for file in &once {
        assert!(
            file.content.starts_with("// Code generated by "),
            "{} lacks the header",
            file.path
        );
        assert!(
            file.path.starts_with("src/main/java/") && file.path.ends_with(".java"),
            "unexpected path: {}",
            file.path
        );
    }
    // The support + provenance scaffold and at least one model file are present.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/core/Tristate.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/BuildInfo.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("src/main/java/com/box/sdk/model/"))
    );
    // The manager/client/runtime layer (D-173): the runtime stub, the SDK
    // entry point, the helper, and at least one manager.
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/runtime/Runtime.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/Client.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path == "src/main/java/com/box/sdk/internal/Internal.java")
    );
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("src/main/java/com/box/sdk/managers/"))
    );
}

/// VR-1.6: the whole generated model tree compiles `javac -Xlint:all -Werror`
/// clean on the real Box spec. `-Werror` makes any lint a hard failure, the
/// Java analogue of `clippy -D warnings` / `tsc` strict. Compiled with
/// `--release 21` so the gate enforces the documented compatibility floor (the
/// model layer uses only stable features) regardless of the host JDK — CI runs
/// it under the Corretto 26 ship-target toolchain, contributors under whatever
/// JDK ≥ 21 they have.
#[test]
fn the_generated_model_layer_compiles_under_javac() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());

    // A smoke driver that constructs the public `Client` from an auth flow, so
    // the whole manager/client surface (D-173) has to type-check as a callable
    // API, not just internally. (It is compiled, never run — the stub session
    // throws at construction.)
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static com.box.sdk.Client build(com.box.sdk.runtime.Runtime.Auth auth) {\n\
         \x20       return new com.box.sdk.Client(auth);\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    // Pass the (900+) sources via an argfile so the command never overflows the
    // OS argument limit.
    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("21")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "javac --release 21 -Xlint:all -Werror failed (VR-1.6):\n{log}"
    );
}

/// FR-5.2: the generated SDK compiles against the **real** hand-written runtime,
/// not just the stub — proving the stub and the runtime can't drift. The Java
/// analogue of the Rust "swap the runtime module and `cargo check`" and the
/// TypeScript "copy the real runtime source and `tsc`" gates. Because the Java
/// runtime is one dependency-free file, the swap is a single-file overwrite: the
/// real `Runtime.java` drops over the generated stub at the same package path,
/// and a smoke driver builds the `Client` from a real auth factory so the whole
/// manager/client tree type-checks against the runtime.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("javac").arg("-version").output().is_err() {
        eprintln!("SKIPPED: javac not available; CI installs a JDK and runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-java-swap-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut sources = write_all(&dir, &generate());

    // Swap the generated stub for the real runtime (same package + class name).
    let real_runtime = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../runtimes/java/gantryruntime/src/main/java/com/box/sdk/runtime/Runtime.java");
    let stub = dir.join("src/main/java/com/box/sdk/runtime/Runtime.java");
    assert!(
        stub.exists(),
        "the generated stub runtime should exist to be swapped"
    );
    std::fs::copy(&real_runtime, &stub).expect("copy the real runtime over the stub");

    // A smoke driver: build the real `Client` from a real auth factory, so the
    // manager surface type-checks against the runtime (the Rust/TS swap pattern).
    // It also drives a paginator through the public `for (var … : …Paginate(…))`
    // idiom (FR-7.3), so the whole paged path — Client field → paginate method →
    // `Iterable<Element>` → element type — type-checks against the real runtime.
    let smoke = dir.join("Smoke.java");
    std::fs::write(
        &smoke,
        "public final class Smoke {\n\
         \x20   public static com.box.sdk.Client build() {\n\
         \x20       return new com.box.sdk.Client(com.box.sdk.runtime.Runtime.developerToken(\"dev\"));\n\
         \x20   }\n\
         \x20   public static int countAgents() {\n\
         \x20       int _n = 0;\n\
         \x20       for (var agent : build().aiStudio.getAiAgentsPaginate(\n\
         \x20               new com.box.sdk.managers.AiStudioManager.GetAiAgentsOptions())) {\n\
         \x20           if (agent != null) {\n\
         \x20               _n++;\n\
         \x20           }\n\
         \x20       }\n\
         \x20       return _n;\n\
         \x20   }\n\
         }\n",
    )
    .unwrap();
    sources.push(smoke);

    let argfile = dir.join("sources.txt");
    let listing: String = sources
        .iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&argfile, listing).unwrap();
    let out = dir.join("classes");
    std::fs::create_dir_all(&out).unwrap();

    let javac = Command::new("javac")
        .arg("--release")
        .arg("21")
        .arg("-Xlint:all")
        .arg("-Werror")
        .arg("-d")
        .arg(&out)
        .arg(format!("@{}", argfile.display()))
        .output()
        .unwrap();
    let ok = javac.status.success();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&javac.stdout),
        String::from_utf8_lossy(&javac.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    assert!(
        ok,
        "the generated SDK failed to compile against the real runtime (FR-5.2):\n{log}"
    );
}

/// FR-7.3: every paged operation gets a `<Prefix><Method>Paginator` class in the
/// managers package. On the real Box spec `detect_pagination` finds 64 paged
/// operations (matching the Go/Rust/TS backends); each synthesizes a paginator
/// (no cursor shape falls back on the real spec). The `javac -Werror` gate above
/// already compiles them — this asserts they are actually emitted and shaped as
/// single-pass `Iterable`s.
#[test]
fn paginators_are_generated() {
    let files = generate();
    let paginators: Vec<_> = files
        .iter()
        .filter(|f| f.path.ends_with("Paginator.java"))
        .collect();
    assert_eq!(
        paginators.len(),
        64,
        "expected one paginator per paged operation on the real spec"
    );
    for file in &paginators {
        assert!(
            file.path.starts_with("src/main/java/com/box/sdk/managers/"),
            "paginator not in the managers package: {}",
            file.path
        );
        assert!(
            file.content.contains("implements java.lang.Iterable<"),
            "paginator {} should be an Iterable",
            file.path
        );
        assert!(
            file.content.contains("public java.util.Iterator<"),
            "paginator {} should expose iterator()",
            file.path
        );
    }
    // Both cursor styles are exercised on the real spec: marker paginators
    // thread a `next_marker`, offset paginators advance by the page length.
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("_cursor += _items.size()")),
        "expected at least one offset-style paginator"
    );
    assert!(
        paginators
            .iter()
            .any(|f| f.content.contains("!_next.isEmpty()")),
        "expected at least one marker-style paginator"
    );
}
