//! Reference documentation generation (FR-7.7).
//!
//! Per-manager Markdown plus the auth / pagination / errors cross-cutting
//! guides, generated from the same IR the code is (so the docs describe the
//! real Rust surface — method names, types, paged variants — and can't drift
//! from it). Deterministic, like all output (FR-6.2).

use std::collections::HashMap;
use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::{pascal, snake};
use gantry_sema::Analysis;
use gantry_synth::PagedOperation;

use crate::GeneratedFile;
use crate::managers::method_name;

/// Generate `docs/` — an index, one page per manager, and the guides.
pub fn generate_docs(analysis: &Analysis<'_>, paged: &[PagedOperation]) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let paged_by_op: HashMap<usize, &PagedOperation> =
        paged.iter().map(|p| (p.operation, p)).collect();

    let mut files = Vec::new();
    files.push(index_page(analysis));
    for (manager, op_indices) in &analysis.managers {
        files.push(manager_page(program, &paged_by_op, manager, op_indices));
    }
    files.push(guide("auth", AUTH_GUIDE));
    files.push(guide("pagination", PAGINATION_GUIDE));
    files.push(guide("errors", ERRORS_GUIDE));
    files
}

fn index_page(analysis: &Analysis<'_>) -> GeneratedFile {
    let mut body = String::from(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# Box SDK reference\n\n\
         One resource manager per Box API tag, reached through the single\n\
         `client::Client` entry point.\n\n## Guides\n\n\
         - [Authentication](auth.md)\n- [Pagination](pagination.md)\n- [Errors](errors.md)\n\n\
         ## Managers\n\n| Manager | Operations |\n|---|---|\n",
    );
    for (manager, ops) in &analysis.managers {
        let _ = writeln!(
            body,
            "| [{name}](managers/{manager}.md) | {count} |",
            name = pascal(manager),
            count = ops.len(),
        );
    }
    GeneratedFile {
        path: "docs/README.md".to_string(),
        content: body,
    }
}

fn manager_page(
    program: &ir::Program,
    paged: &HashMap<usize, &PagedOperation>,
    manager: &str,
    op_indices: &[usize],
) -> GeneratedFile {
    let mut body = format!(
        "<!-- Generated by box-gantry. DO NOT EDIT. -->\n# {}Manager\n\n\
         Reach these methods through the `{}` field on `client::Client`.\n\n",
        pascal(manager),
        snake(manager),
    );
    for &index in op_indices {
        let op = &program.operations[index];
        let method = method_name(op);
        let _ = writeln!(body, "## {method}\n");
        if op.deprecated {
            body.push_str("> **Deprecated.**\n\n");
        }
        let _ = writeln!(
            body,
            "`{http} {path}`\n",
            http = http_method(op.method),
            path = render_path(op),
        );

        let params: Vec<&ir::Param> = op.params.iter().collect();
        if !params.is_empty() {
            body.push_str("| Parameter | In | Type | Required |\n|---|---|---|---|\n");
            for param in &params {
                let required = !matches!(param.ty, ir::Type::Optional(_));
                let _ = writeln!(
                    body,
                    "| `{name}` | {loc} | `{ty}` | {req} |",
                    name = param.wire_name,
                    loc = param_location(param.location),
                    ty = describe(program, unwrap(&param.ty)),
                    req = if required { "yes" } else { "no" },
                );
            }
            body.push('\n');
        }
        if let Some(req) = &op.request {
            let _ = writeln!(
                body,
                "**Request body** (`{media}`): `{ty}`\n",
                media = request_media(req.media),
                ty = describe(program, unwrap(&req.ty)),
            );
        }
        let _ = writeln!(
            body,
            "**Returns:** {}\n",
            describe_response(program, &op.response)
        );
        let _ = writeln!(
            body,
            "**Example**\n\n{}",
            call_snippet(program, manager, op, &method, paged.contains_key(&index))
        );
        if paged.contains_key(&index) {
            let _ = writeln!(
                body,
                "Paginated — `{method}(...)` returns a paginator you drive with \
                 `.next().await`, threading the cursor for you. See the \
                 [pagination guide](../pagination.md).\n"
            );
        }
    }
    GeneratedFile {
        path: format!("docs/managers/{manager}.md"),
        content: body,
    }
}

fn guide(name: &str, content: &str) -> GeneratedFile {
    GeneratedFile {
        path: format!("docs/{name}.md"),
        content: format!("<!-- Generated by box-gantry. DO NOT EDIT. -->\n{content}"),
    }
}

/// A call snippet for one operation: the manager method with placeholder
/// arguments in the printer's order (required params, body, then `None` for the
/// options), `.await?`, and idiomatic result binding — the paginated form drives
/// the paginator with `while let`. Shape-correct fragment (argument count/order
/// match the real async signature; values are placeholders), so the docs show
/// *how to call* every method (FR-7.7).
fn call_snippet(
    program: &ir::Program,
    manager: &str,
    op: &ir::Operation,
    method: &str,
    paged: bool,
) -> String {
    let mut args: Vec<String> = Vec::new();
    let mut has_optional = false;
    for param in &op.params {
        if matches!(param.ty, ir::Type::Optional(_)) {
            has_optional = true;
        } else {
            args.push(rust_placeholder(program, &param.ty, &param.wire_name));
        }
    }
    if let Some(req) = &op.request {
        args.push(rust_body_literal(program, unwrap(&req.ty)));
    }
    if has_optional {
        args.push("None".to_string());
    }
    let field = snake(manager);
    let call = format!("client.{field}.{method}({})", args.join(", "));

    let mut out = String::from("```rust\n");
    if paged {
        let _ = writeln!(
            out,
            "let mut pages = {call};\n\
             while let Some(item) = pages.next().await {{\n\
             \x20   // use item\n}}"
        );
    } else if matches!(op.response, ir::ResponseShape::None) {
        let _ = writeln!(out, "{call}.await?;");
    } else {
        let _ = writeln!(out, "let result = {call}.await?;");
    }
    out.push_str("```\n");
    out
}

/// A placeholder value for a required argument, by type. Strings show the
/// parameter name (upper-cased); a decl-typed param falls back to
/// `Default::default()` (a readable "provide a value" in a fragment).
fn rust_placeholder(program: &ir::Program, ty: &ir::Type, wire_name: &str) -> String {
    let _ = program;
    match unwrap(ty) {
        ir::Type::String => format!("\"{}\".to_string()", wire_name.to_uppercase()),
        ir::Type::Int64 | ir::Type::Float64 => "0".to_string(),
        ir::Type::Bool => "false".to_string(),
        ir::Type::DateTime => "chrono::Utc::now()".to_string(),
        ir::Type::List(_) => "vec![]".to_string(),
        // Enums, structs, dates, maps, JSON: a default value keeps the call
        // readable without pinning a specific variant/field set.
        ir::Type::Decl(_)
        | ir::Type::Date
        | ir::Type::Map(_)
        | ir::Type::JsonValue
        | ir::Type::Binary
        | ir::Type::Optional(_)
        | ir::Type::Nullable(_) => "Default::default()".to_string(),
    }
}

/// A placeholder literal for a request body: a struct/decl body shows its type
/// with an elided field set; a list/map body is its own empty literal.
fn rust_body_literal(program: &ir::Program, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Decl(id) => format!(
            "schemas::{} {{ /* … */ }}",
            crate::models::type_name(program.decl(*id).name.as_str())
        ),
        ir::Type::List(_) => "vec![]".to_string(),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::Map(_)
        | ir::Type::Optional(_)
        | ir::Type::Nullable(_) => "Default::default()".to_string(),
    }
}

/// A readable (Rust-flavored) name for a type, for docs only — matching the
/// `models` type mapping so the docs describe the real generated surface.
fn describe(program: &ir::Program, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Bool => "bool".into(),
        ir::Type::Int64 => "i64".into(),
        ir::Type::Float64 => "f64".into(),
        ir::Type::String => "String".into(),
        ir::Type::Date => "chrono::NaiveDate".into(),
        ir::Type::DateTime => "chrono::DateTime<chrono::Utc>".into(),
        ir::Type::Binary => "Vec<u8>".into(),
        ir::Type::JsonValue => "serde_json::Value".into(),
        ir::Type::List(inner) => format!("Vec<{}>", describe(program, inner)),
        ir::Type::Map(inner) => {
            format!(
                "std::collections::HashMap<String, {}>",
                describe(program, inner)
            )
        }
        // Match the `models` type mapping exactly: declaration names go through
        // `type_name` (prelude-collision suffixing), and `Nullable`/`Optional`
        // both map to `Option<T>` — so the docs name the real generated types.
        ir::Type::Decl(id) => crate::models::type_name(program.decl(*id).name.as_str()),
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => {
            format!("Option<{}>", describe(program, inner))
        }
    }
}

fn describe_response(program: &ir::Program, response: &ir::ResponseShape) -> String {
    match response {
        ir::ResponseShape::None => "no content".into(),
        ir::ResponseShape::Json(ty) => format!("`{}`", describe(program, unwrap(ty))),
        ir::ResponseShape::Binary => "a binary stream (`runtime::Stream`)".into(),
        ir::ResponseShape::Text => "text (`String`)".into(),
        ir::ResponseShape::Redirect => "a redirect URL (`String`)".into(),
    }
}

fn unwrap(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}

fn render_path(op: &ir::Operation) -> String {
    let mut out = String::new();
    for segment in &op.path {
        out.push('/');
        match segment {
            ir::PathSegment::Literal(text) => out.push_str(text),
            ir::PathSegment::Parameter(name) => {
                let _ = write!(out, "{{{}}}", name.as_str());
            }
            ir::PathSegment::Composite(parts) => {
                for part in parts {
                    match part {
                        ir::PathPart::Literal(text) => out.push_str(text),
                        ir::PathPart::Parameter(name) => {
                            let _ = write!(out, "{{{}}}", name.as_str());
                        }
                    }
                }
            }
        }
    }
    out
}

fn http_method(method: ir::HttpMethod) -> &'static str {
    match method {
        ir::HttpMethod::Get => "GET",
        ir::HttpMethod::Put => "PUT",
        ir::HttpMethod::Post => "POST",
        ir::HttpMethod::Delete => "DELETE",
        ir::HttpMethod::Options => "OPTIONS",
        ir::HttpMethod::Head => "HEAD",
        ir::HttpMethod::Patch => "PATCH",
        ir::HttpMethod::Trace => "TRACE",
    }
}

fn param_location(location: ir::ParamLocation) -> &'static str {
    match location {
        ir::ParamLocation::Path => "path",
        ir::ParamLocation::Query => "query",
        ir::ParamLocation::Header => "header",
    }
}

fn request_media(media: ir::RequestMedia) -> &'static str {
    match media {
        ir::RequestMedia::Json => "application/json",
        ir::RequestMedia::JsonPatch => "application/json-patch+json",
        ir::RequestMedia::UrlEncoded => "application/x-www-form-urlencoded",
        ir::RequestMedia::Multipart => "multipart/form-data",
        ir::RequestMedia::OctetStream => "application/octet-stream",
    }
}

const AUTH_GUIDE: &str = "# Authentication\n\n\
Every request is authorized through the runtime's token source: the\n\
generated code calls `auth.access_token().await` and attaches the bearer\n\
token, and the network layer refreshes on a `401` and retries once. Pass\n\
one of the four Box auth flows to `Client::new` at construction; each is a\n\
`auth::Auth` that caches its access token until shortly before it\n\
expires.\n\n\
## Developer Token\n\n\
```rust\n\
let client = Client::new(auth::Auth::developer_token(\"DEVELOPER_TOKEN\"));\n\
```\n\n\
## Client Credentials Grant (server auth, no key)\n\n\
```rust\n\
let client = Client::new(auth::Auth::client_credentials(\n\
    \"CLIENT_ID\",\n\
    \"CLIENT_SECRET\",\n\
    // enterprise or managed-user subject:\n\
    runtime::Subject::Enterprise(\"ENTERPRISE_ID\"),\n\
));\n\
```\n\n\
## JWT (server auth with a signing key)\n\n\
```rust\n\
let auth = auth::Auth::jwt(auth::JwtConfig {\n\
    client_id: \"CLIENT_ID\".into(),\n\
    client_secret: \"CLIENT_SECRET\".into(),\n\
    public_key_id: \"PUBLIC_KEY_ID\".into(),\n\
    private_key_pem: private_key_pem, // optionally encrypted; set passphrase\n\
    subject: runtime::Subject::Enterprise(\"ENTERPRISE_ID\".into()),\n\
    ..Default::default()\n\
})?; // bad key: fails loudly at construction\n\
let client = Client::new(auth);\n\
```\n\n\
## OAuth 2.0 (authorization code)\n\n\
Redirect the user to the authorize URL, exchange the returned code, then\n\
reuse the stored refresh token on later runs:\n\n\
```rust\n\
// later runs: rebuild from the stored refresh token.\n\
let auth = auth::Auth::oauth(\"CLIENT_ID\", \"CLIENT_SECRET\", stored_refresh_token);\n\
let client = Client::new(auth);\n\
```\n";

const PAGINATION_GUIDE: &str = "# Pagination\n\n\
Marker- and offset-paginated list operations return a paginator — the list\n\
method *is* the paginator. You drive it with `.next().await`, which yields one\n\
element at a time and threads the cursor for you:\n\n\
```rust\n\
let mut pages = client.folders.list_items(folder_id, None);\n\
while let Some(item) = pages.next().await {\n\
    let item = item?;\n\
    // use item\n\
}\n\
```\n\n\
The paginator stops when the last page is reached. It owns a copy of the\n\
options you pass, so your value is never mutated.\n";

const ERRORS_GUIDE: &str = "# Errors\n\n\
Every I/O method returns `Result<T, runtime::Error>`. An `Err` is either a\n\
transport failure or a non-2xx response after the network layer's retries\n\
(exponential backoff + jitter, `401` refresh, `Retry-After`). Response\n\
bodies for error statuses carry the Box error schema and can be inspected\n\
on the returned error.\n";
