//! The Rust backend: lowering + printer (FR-6, TR-Rust).
//!
//! Generates the SDK crate tree's **model layer**: the `models` module mirrors
//! the IR module tree one Rust module per IR module (names collide across API
//! versions, so they may not share a namespace — D-147), lowering structs,
//! string enums, unions, and aliases to `serde` Rust types.
//!
//! - **Optionality** is `Option<T>`; the absent-vs-null tri-state
//!   (`Optional<Nullable<T>>`, D-110) maps to `Option<Option<T>>` with a
//!   `double_option` deserializer so absence and explicit `null` stay distinct.
//! - **Unions** (TR-Rust.1, D-148): a discriminated union with decl-backed
//!   variants lowers to a typed `enum` with hand-written `Serialize`/
//!   `Deserialize` that dispatch on the tag; open unions retain an unrecognized
//!   tag in an `Unknown(serde_json::Value)` variant (round-trip safe), closed
//!   unions reject it. Structural unions stay a `serde_json::Value` newtype.
//!
//! Output is deterministic (FR-6.2, sorted by path) and rustfmt-clean by
//! construction (TR-Rust.4, G-17), verified by the real toolchain
//! (`cargo fmt --check` + `cargo check` + `clippy -D warnings` — VR-1.2) plus a
//! generated-union round-trip test (VR-4).
//!
//! Not yet emitted (later M5 slices): typed date/time, managers + async client
//! (TR-Rust.3), the `reqwest`/`tokio` runtime (TR-Rust.5), and generated tests
//! + docs.

mod managers;
mod models;

pub use managers::generate_managers;
pub use models::generate_models;

/// One generated file, path relative to the SDK crate root.
#[derive(Debug)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Provenance stamped into the generated SDK for traceability (NF-7): the
/// engine version that produced it and the fingerprint of the input specs.
#[derive(Debug, Clone)]
pub struct BuildInfo {
    /// The box-gantry engine version (workspace version).
    pub engine: String,
    /// The input spec-set fingerprint (`SpecSet::fingerprint`).
    pub spec_fingerprint: String,
}

impl BuildInfo {
    /// Build info for the current engine over a given spec fingerprint.
    pub fn new(spec_fingerprint: impl Into<String>) -> Self {
        Self {
            engine: env!("CARGO_PKG_VERSION").to_string(),
            spec_fingerprint: spec_fingerprint.into(),
        }
    }
}

/// Generate the SDK crate tree for a verified program, stamped with the build
/// provenance (NF-7). The output is a self-contained, publishable Rust crate
/// (the NF-8 ship artifact once the runtime lands).
///
/// Takes the manifest so synthesis keys off capability axes, never the
/// language name (FR-4.2); this slice reads only `manifest.key`.
pub fn generate(
    analysis: &gantry_sema::Analysis<'_>,
    manifest: &gantry_manifest::CapabilityManifest,
    build: &BuildInfo,
) -> Vec<GeneratedFile> {
    let mut files = vec![
        GeneratedFile {
            path: "Cargo.toml".to_string(),
            content: cargo_toml(),
        },
        GeneratedFile {
            path: "src/lib.rs".to_string(),
            content: lib_rs(manifest, build),
        },
        GeneratedFile {
            path: "src/serde_helpers.rs".to_string(),
            content: SERDE_HELPERS.to_string(),
        },
        // The runtime stubs are rendered from the contract (FR-5.2): generated
        // managers compile against exactly the declared surface, without the
        // real runtime (FR-5.3). The real `reqwest`/`tokio` runtime implements
        // the same contract (TR-Rust.5, a later slice).
        GeneratedFile {
            path: "src/runtime.rs".to_string(),
            content: gantry_contract::rust_stubs(&gantry_contract::V1, manifest),
        },
    ];
    files.extend(generate_models(analysis, build));
    files.extend(generate_managers(analysis, build));
    files.sort_by(|a, b| a.path.cmp(&b.path));
    files
}

/// The generated SDK crate manifest. Pinned, minimal deps (serde +
/// serde_json); the runtime crate joins here when TR-Rust.5 lands.
fn cargo_toml() -> String {
    "[package]\n\
     name = \"box-sdk\"\n\
     version = \"0.1.0\"\n\
     edition = \"2021\"\n\
     \n\
     [dependencies]\n\
     serde = { version = \"1\", features = [\"derive\"] }\n\
     serde_json = \"1\"\n"
        .to_string()
}

/// The crate root: module tree + the provenance `buildinfo` constants (NF-7),
/// which let the shipped SDK report its own version and inputs.
fn lib_rs(manifest: &gantry_manifest::CapabilityManifest, build: &BuildInfo) -> String {
    format!(
        "// Code generated by box-gantry {engine} (spec {fingerprint}). DO NOT EDIT.\n\
         #![allow(clippy::large_enum_variant)]\n\
         \n\
         pub mod client;\n\
         pub(crate) mod internal;\n\
         pub mod managers;\n\
         pub mod models;\n\
         mod runtime;\n\
         mod serde_helpers;\n\
         \n\
         /// Build provenance for this generated SDK (NF-7).\n\
         pub mod buildinfo {{\n\
         \x20   /// The box-gantry engine version that generated this crate.\n\
         \x20   pub const ENGINE: &str = {engine:?};\n\
         \x20   /// Fingerprint of the input spec set.\n\
         \x20   pub const SPEC_FINGERPRINT: &str = {fingerprint:?};\n\
         \x20   /// The target language key (FR-4).\n\
         \x20   pub const TARGET: &str = {target:?};\n\
         }}\n",
        engine = build.engine,
        fingerprint = build.spec_fingerprint,
        target = manifest.key,
    )
}

/// Tri-state deserialize helper (D-110): distinguishes an absent field from an
/// explicit `null`. Paired with `#[serde(default, skip_serializing_if =
/// "Option::is_none")]` on an `Option<Option<T>>` field — absent → `None`,
/// `null` → `Some(None)`, value → `Some(Some(v))`.
const SERDE_HELPERS: &str = "\
// Code generated by box-gantry. DO NOT EDIT.
use serde::{Deserialize, Deserializer};

/// Deserialize a present field (value or `null`) into the inner `Option`,
/// wrapping in `Some` so a present `null` reads as `Some(None)` and an absent
/// field (via `#[serde(default)]`) reads as `None`.
pub(crate) fn double_option<'de, T, D>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    T: Deserialize<'de>,
    D: Deserializer<'de>,
{
    Deserialize::deserialize(deserializer).map(Some)
}
";
