//! Manager + client generation: IR operations → async Rust methods that call
//! only through the runtime contract (FR-5.2, TR-Rust.3).
//!
//! One `<Name>Manager` per `x-box-tag`, one `async fn` per operation, and a
//! `Client` entry point wiring a shared runtime session. Methods build the URL
//! from structured path segments (never a re-parsed template, FR-2.2), apply
//! query/header params, encode the request body per media, `fetch` through the
//! session, and decode the response by shape. Optional params travel in a
//! per-operation options struct. Everything reaches the network only via
//! `crate::runtime` (the contract surface), so the generated SDK compiles
//! against the rendered stubs and, later, the real runtime unchanged.

use std::fmt::Write as _;

use gantry_ir as ir;
use gantry_ir::naming::{pascal, snake};
use gantry_sema::Analysis;

use crate::models::{module_name, type_name};
use crate::{BuildInfo, GeneratedFile};

/// Managers reference the runtime through a per-file `use crate::runtime`, so
/// generated paths stay short enough to keep signatures rustfmt-inline.
const RUNTIME: &str = "runtime";

/// Generate the `managers` module (one file per manager), the `client` entry
/// point, and the `internal` helpers.
pub fn generate_managers(analysis: &Analysis<'_>, _build: &BuildInfo) -> Vec<GeneratedFile> {
    let program = analysis.program;
    let base_version = program
        .operations
        .first()
        .and_then(|op| op.api_version.clone());

    // Manager key → (module name, struct name), sorted (BTreeMap) for
    // deterministic output (FR-6.2).
    let managers: Vec<(&String, &Vec<usize>)> = analysis.managers.iter().collect();

    let mut files = Vec::new();

    // managers/mod.rs
    let mut mod_rs = String::from("// Code generated by box-gantry. DO NOT EDIT.\n\n");
    for (key, _) in &managers {
        let _ = writeln!(mod_rs, "pub mod {};", manager_module(key));
    }
    files.push(GeneratedFile {
        path: "src/managers/mod.rs".to_string(),
        content: mod_rs,
    });

    for (key, indices) in &managers {
        let mut p = Printer {
            program,
            base_version: base_version.clone(),
            body: String::new(),
            uses_path_escape: false,
        };
        p.manager(key, indices);
        let mut content = String::from("// Code generated by box-gantry. DO NOT EDIT.\n\n");
        // Alphabetical (rustfmt import order): `internal` before `runtime`.
        if p.uses_path_escape {
            content.push_str("use crate::internal::path_escape;\n");
        }
        content.push_str("use crate::runtime::{self, Error};\n");
        content.push('\n');
        content.push_str(p.body.trim_end());
        content.push('\n');
        files.push(GeneratedFile {
            path: format!("src/managers/{}.rs", manager_module(key)),
            content,
        });
    }

    files.push(GeneratedFile {
        path: "src/client.rs".to_string(),
        content: client_file(&managers),
    });
    files.push(GeneratedFile {
        path: "src/internal.rs".to_string(),
        content: INTERNAL.to_string(),
    });
    files
}

fn manager_module(key: &str) -> String {
    snake(key)
}

fn manager_struct(key: &str) -> String {
    format!("{}Manager", pascal(key))
}

/// The `Client` entry point: one field per manager, a shared runtime session.
fn client_file(managers: &[(&String, &Vec<usize>)]) -> String {
    let mut out = String::from("// Code generated by box-gantry. DO NOT EDIT.\n\n");
    out.push_str("/// The Box SDK client: one manager per API area over a shared session.\n");
    out.push_str("pub struct Client {\n");
    for (key, _) in managers {
        let _ = writeln!(
            out,
            "    pub {field}: crate::managers::{module}::{ty},",
            field = snake(key),
            module = manager_module(key),
            ty = manager_struct(key),
        );
    }
    out.push_str("}\n\n");
    out.push_str("impl Client {\n");
    out.push_str("    /// Build a client for an authentication flow.\n");
    out.push_str("    pub fn new(auth: crate::runtime::Auth) -> Self {\n");
    out.push_str("        let session = std::sync::Arc::new(crate::runtime::Client::new(auth));\n");
    out.push_str("        Self {\n");
    for (key, _) in managers {
        let _ = writeln!(
            out,
            "            {field}: crate::managers::{module}::{ty}::new(session.clone()),",
            field = snake(key),
            module = manager_module(key),
            ty = manager_struct(key),
        );
    }
    out.push_str("        }\n    }\n}\n");
    out
}

struct Printer<'p> {
    program: &'p ir::Program,
    base_version: Option<ir::ApiVersion>,
    body: String,
    /// Whether any method escaped a path parameter, so the file imports
    /// `path_escape`.
    uses_path_escape: bool,
}

impl Printer<'_> {
    fn manager(&mut self, key: &str, indices: &[usize]) {
        let ty = manager_struct(key);
        // Options structs are module-level items (Rust forbids `struct` inside
        // `impl`), emitted before the manager so the methods can name them.
        for &index in indices {
            let op = self.program.operations[index].clone();
            self.options_struct(&op);
        }
        let _ = writeln!(
            self.body,
            "/// Operations for the {key:?} API area.\n\
             pub struct {ty} {{\n\
             \x20   session: std::sync::Arc<{RUNTIME}::Client>,\n\
             }}\n\n\
             impl {ty} {{\n\
             \x20   pub(crate) fn new(session: std::sync::Arc<{RUNTIME}::Client>) -> Self {{\n\
             \x20       Self {{ session }}\n\
             \x20   }}"
        );
        for &index in indices {
            let op = self.program.operations[index].clone();
            self.operation(&op);
        }
        self.body.push_str("}\n");
    }

    /// Emit the module-level options struct for an operation's optional params.
    fn options_struct(&mut self, op: &ir::Operation) {
        let optional: Vec<&ir::Param> = op
            .params
            .iter()
            .filter(|p| matches!(p.ty, ir::Type::Optional(_)))
            .collect();
        if optional.is_empty() {
            return;
        }
        let method = self.method_name(op);
        let _ = writeln!(
            self.body,
            "/// Optional parameters for [`{ty}::{method}`].\n\
             #[derive(Clone, Debug, Default)]\n\
             pub struct {opt} {{",
            ty = manager_struct(op.manager.as_str()),
            opt = options_type(op.manager.as_str(), &method),
        );
        for param in &optional {
            let inner = unwrap_optionality(&param.ty);
            let _ = writeln!(
                self.body,
                "    pub {field}: Option<{ty}>,",
                field = field_ident(param.name.as_str()),
                ty = rust_type(self.program, inner),
            );
        }
        self.body.push_str("}\n\n");
    }

    fn operation(&mut self, op: &ir::Operation) {
        let method = self.method_name(op);
        let mut required: Vec<&ir::Param> = Vec::new();
        let mut optional: Vec<&ir::Param> = Vec::new();
        for param in &op.params {
            if matches!(param.ty, ir::Type::Optional(_)) {
                optional.push(param);
            } else {
                required.push(param);
            }
        }

        let options_ty = options_type(op.manager.as_str(), &method);
        // Signature.
        let mut params: Vec<String> = vec!["&self".to_string()];
        for param in &required {
            params.push(format!(
                "{}: {}",
                field_ident(param.name.as_str()),
                rust_type(self.program, &param.ty)
            ));
        }
        if let Some(body) = &op.request {
            params.push(format!(
                "body: {}",
                rust_type(self.program, unwrap_optionality(&body.ty))
            ));
        }
        if !optional.is_empty() {
            params.push(format!("opts: Option<{options_ty}>"));
        }
        let ret = self.return_type(op);

        self.body.push('\n');
        let sig = format!(
            "    pub async fn {method}({}) -> {ret} {{",
            params.join(", ")
        );
        if sig.len() <= 100 {
            let _ = writeln!(self.body, "{sig}");
        } else {
            let _ = writeln!(self.body, "    pub async fn {method}(");
            for param in &params {
                let line = format!("        {param},");
                if line.len() <= 100 {
                    let _ = writeln!(self.body, "{line}");
                } else if let Some((head, inner)) = param.split_once(": Option<") {
                    // rustfmt breaks an over-long `name: Option<Type>` param.
                    let inner = inner.strip_suffix('>').unwrap_or(inner);
                    let _ = writeln!(self.body, "        {head}: Option<");
                    let _ = writeln!(self.body, "            {inner},");
                    self.body.push_str("        >,\n");
                } else {
                    let _ = writeln!(self.body, "{line}");
                }
            }
            let _ = writeln!(self.body, "    ) -> {ret} {{");
        }

        self.url_and_request(op);
        let modifies = op
            .params
            .iter()
            .any(|p| p.location != ir::ParamLocation::Path)
            || op.request.is_some();
        let req_binding = if modifies { "let mut req" } else { "let req" };
        let _ = writeln!(
            self.body,
            "        {req_binding} = self.session.new_request({method_str:?}, &url);",
            method_str = http_method(op.method),
        );
        self.apply_params(&required, false);
        if !optional.is_empty() {
            self.body
                .push_str("        let opts = opts.unwrap_or_default();\n");
            self.apply_params(&optional, true);
        }
        self.request_body(op);
        self.fetch_and_decode(op);
        self.body.push_str("    }\n");
    }

    /// Build the URL from the D-106 base class + structured path segments.
    fn url_and_request(&mut self, op: &ir::Operation) {
        let base = base_class(op.base_url);
        if op.path.is_empty() {
            let _ = writeln!(
                self.body,
                "        let url = self.session.base_url({base:?});"
            );
            return;
        }
        let _ = writeln!(
            self.body,
            "        let mut url = self.session.base_url({base:?});"
        );
        for segment in &op.path {
            match segment {
                ir::PathSegment::Literal(text) => {
                    let _ = writeln!(self.body, "        url.push_str(\"/{text}\");");
                }
                ir::PathSegment::Parameter(name) => {
                    let value = self.path_value(op, name);
                    self.body.push_str("        url.push('/');\n");
                    self.emit_path_push(&value);
                }
                ir::PathSegment::Composite(parts) => {
                    self.body.push_str("        url.push('/');\n");
                    for part in parts {
                        match part {
                            ir::PathPart::Literal(text) => {
                                let _ = writeln!(self.body, "        url.push_str({text:?});");
                            }
                            ir::PathPart::Parameter(name) => {
                                let value = self.path_value(op, name);
                                self.emit_path_push(&value);
                            }
                        }
                    }
                }
            }
        }
    }

    /// Emit a percent-escaped path segment. The value binds to a local first so
    /// the nested `push_str(&path_escape(…))` call never trips rustfmt's
    /// call-width wrapping (unpredictable from line length alone).
    fn emit_path_push(&mut self, value: &str) {
        self.uses_path_escape = true;
        let _ = writeln!(self.body, "        let seg = path_escape(&{value});");
        self.body.push_str("        url.push_str(&seg);\n");
    }

    /// The Rust expression (a `String`/`&str`) for a path parameter's value.
    fn path_value(&self, op: &ir::Operation, name: &ir::Identifier) -> String {
        let param = op
            .params
            .iter()
            .find(|p| p.location == ir::ParamLocation::Path && p.name == *name)
            .expect("ingestion validated every path placeholder");
        self.string_value(&field_ident(param.name.as_str()), &param.ty)
    }

    /// Emit `with_query`/`with_header` calls. When `from_options`, values come
    /// from the moved-out options struct field.
    fn apply_params(&mut self, params: &[&ir::Param], from_options: bool) {
        for param in params {
            let call = match param.location {
                ir::ParamLocation::Query => "with_query",
                ir::ParamLocation::Header => "with_header",
                ir::ParamLocation::Path => continue,
            };
            let wire = format!("{:?}", param.wire_name);
            if from_options {
                let inner = unwrap_optionality(&param.ty);
                let value = self.string_value("value", inner);
                let _ = writeln!(
                    self.body,
                    "        if let Some(value) = opts.{field} {{",
                    field = field_ident(param.name.as_str()),
                );
                self.emit_with_call("            ", call, &wire, &value);
                self.body.push_str("        }\n");
            } else {
                let value = self.string_value(&field_ident(param.name.as_str()), &param.ty);
                self.emit_with_call("        ", call, &wire, &value);
            }
        }
    }

    /// Emit `req = runtime::<call>(req, <wire>, &<value>);`, binding the value
    /// to a local first when the inline form would overflow 100 columns.
    fn emit_with_call(&mut self, indent: &str, call: &str, wire: &str, value: &str) {
        let inline = format!("{indent}req = runtime::{call}(req, {wire}, &{value});");
        if inline.len() <= 100 {
            let _ = writeln!(self.body, "{inline}");
        } else {
            let _ = writeln!(self.body, "{indent}let arg = {value};");
            let _ = writeln!(
                self.body,
                "{indent}req = runtime::{call}(req, {wire}, &arg);"
            );
        }
    }

    fn request_body(&mut self, op: &ir::Operation) {
        let Some(body) = &op.request else {
            return;
        };
        match body.media {
            ir::RequestMedia::Json | ir::RequestMedia::JsonPatch => {
                self.body.push_str(
                    "        let payload = serde_json::to_vec(&body)?;\n\
                     \x20       req = runtime::with_json_body(req, &payload);\n",
                );
            }
            // Uploads are not yet fully streamed (D-149): the octet/multipart
            // file part is an empty placeholder — the same posture as the Go
            // backend's `nil` file — until the runtime slice wires real body
            // streaming. Multipart still sends the serialized attributes.
            ir::RequestMedia::OctetStream => {
                self.body.push_str(
                    "        let _ = &body;\n\
                     \x20       req = runtime::with_stream_body(req, runtime::Stream::empty(), \"application/octet-stream\");\n",
                );
            }
            ir::RequestMedia::Multipart => {
                self.body.push_str(
                    "        let attributes = serde_json::to_vec(&body)?;\n\
                     \x20       req = runtime::with_multipart_body(req, &attributes, \"file\", runtime::Stream::empty());\n",
                );
            }
            ir::RequestMedia::UrlEncoded => {
                self.body.push_str(
                    "        let payload = serde_json::to_vec(&body)?;\n\
                     \x20       req = runtime::with_form_body(req, &payload);\n",
                );
            }
        }
    }

    fn fetch_and_decode(&mut self, op: &ir::Operation) {
        match &op.response {
            ir::ResponseShape::None => {
                self.body
                    .push_str("        let _ = self.session.fetch(req).await?;\n        Ok(())\n");
            }
            ir::ResponseShape::Json(_) => {
                self.body.push_str(
                    "        let resp = self.session.fetch(req).await?;\n\
                     \x20       let data = runtime::response_bytes(&resp)?;\n\
                     \x20       Ok(serde_json::from_slice(&data)?)\n",
                );
            }
            ir::ResponseShape::Binary => {
                self.body.push_str(
                    "        let resp = self.session.fetch(req).await?;\n\
                     \x20       Ok(runtime::response_stream(&resp))\n",
                );
            }
            ir::ResponseShape::Text => {
                self.body.push_str(
                    "        let resp = self.session.fetch(req).await?;\n\
                     \x20       let data = runtime::response_bytes(&resp)?;\n\
                     \x20       Ok(String::from_utf8_lossy(&data).into_owned())\n",
                );
            }
            ir::ResponseShape::Redirect => {
                self.body.push_str(
                    "        let resp = self.session.fetch(req).await?;\n\
                     \x20       Ok(runtime::response_header(&resp, \"Location\"))\n",
                );
            }
        }
    }

    fn return_type(&self, op: &ir::Operation) -> String {
        let ok = match &op.response {
            ir::ResponseShape::None => "()".to_string(),
            ir::ResponseShape::Json(ty) => rust_type(self.program, unwrap_optionality(ty)),
            ir::ResponseShape::Binary => format!("{RUNTIME}::Stream"),
            ir::ResponseShape::Text | ir::ResponseShape::Redirect => "String".to_string(),
        };
        format!("Result<{ok}, Error>")
    }

    /// A Rust expression (typed `String` or `&str`) converting `expr` (already
    /// non-optional) into the string a query/header/path slot needs.
    fn string_value(&self, expr: &str, ty: &ir::Type) -> String {
        match ty {
            ir::Type::String | ir::Type::Date | ir::Type::DateTime => expr.to_string(),
            ir::Type::Bool | ir::Type::Int64 | ir::Type::Float64 => format!("{expr}.to_string()"),
            ir::Type::List(inner) if matches!(**inner, ir::Type::String) => {
                format!("{expr}.join(\",\")")
            }
            ir::Type::List(inner) if is_scalar(self.program, inner) => {
                // Routed through a helper so the call site stays a short chain
                // (rustfmt breaks any chain wider than `chain_width`).
                format!(
                    "crate::internal::join(&{expr}, |v| {})",
                    self.list_element(inner)
                )
            }
            ir::Type::Decl(id) => match &self.program.decl(*id).kind {
                ir::DeclKind::Enum(e) if matches!(e.extensibility, ir::Extensibility::Open) => {
                    format!("{expr}.0")
                }
                ir::DeclKind::Alias(inner) => {
                    let inner = inner.clone();
                    self.string_value(expr, &inner)
                }
                ir::DeclKind::Enum(_) | ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) => {
                    json_string(expr)
                }
            },
            ir::Type::List(_)
            | ir::Type::Map(_)
            | ir::Type::JsonValue
            | ir::Type::Binary
            | ir::Type::Optional(_)
            | ir::Type::Nullable(_) => json_string(expr),
        }
    }

    /// The per-element `String` expression for joining a scalar list, in terms
    /// of the iterator variable `v` (a `&Element`).
    fn list_element(&self, inner: &ir::Type) -> String {
        match inner {
            ir::Type::String | ir::Type::Date | ir::Type::DateTime => "v.clone()".to_string(),
            ir::Type::Bool | ir::Type::Int64 | ir::Type::Float64 => "v.to_string()".to_string(),
            ir::Type::Decl(id) => match &self.program.decl(*id).kind {
                ir::DeclKind::Enum(e) if matches!(e.extensibility, ir::Extensibility::Open) => {
                    "v.0.clone()".to_string()
                }
                ir::DeclKind::Alias(inner) => {
                    let inner = inner.clone();
                    self.list_element(&inner)
                }
                ir::DeclKind::Enum(_) | ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) => {
                    "serde_json::to_string(v).unwrap_or_default()".to_string()
                }
            },
            ir::Type::Binary
            | ir::Type::JsonValue
            | ir::Type::List(_)
            | ir::Type::Map(_)
            | ir::Type::Optional(_)
            | ir::Type::Nullable(_) => "serde_json::to_string(v).unwrap_or_default()".to_string(),
        }
    }

    fn method_name(&self, op: &ir::Operation) -> String {
        method_name(op, self.base_version.as_ref())
    }
}

/// The Rust method name for an operation (snake_case). Versioned/variation
/// operations get suffixed so base and versioned surfaces never collide
/// (FR-7.5).
fn method_name(op: &ir::Operation, base_version: Option<&ir::ApiVersion>) -> String {
    let mut name = snake(op.name.as_str());
    if let Some(variation) = &op.variation {
        name.push('_');
        name.push_str(&snake(variation.as_str()));
    }
    if op.api_version.as_ref() != base_version
        && let Some(version) = &op.api_version
    {
        name.push_str("_v");
        name.push_str(&version.0.replace(['.', '-'], "_"));
    }
    // Keyword-safe (raw identifier where needed).
    field_ident(&name)
}

/// The module-level options struct name for an operation (manager-qualified so
/// it stays unique across the `managers` module).
fn options_type(manager: &str, method: &str) -> String {
    format!("{}{}Options", pascal(manager), pascal(method))
}

/// A `String`-producing JSON encode for a complex query value (the Box
/// `mdfilters` convention). Infallible on generated models.
fn json_string(expr: &str) -> String {
    format!("serde_json::to_string(&{expr}).unwrap_or_default()")
}

fn is_scalar(program: &ir::Program, ty: &ir::Type) -> bool {
    match ty {
        ir::Type::String
        | ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::Date
        | ir::Type::DateTime => true,
        ir::Type::Decl(id) => match &program.decl(*id).kind {
            ir::DeclKind::Enum(_) => true,
            ir::DeclKind::Alias(inner) => is_scalar(program, inner),
            ir::DeclKind::Struct(_) | ir::DeclKind::Union(_) => false,
        },
        ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Optional(_)
        | ir::Type::Nullable(_) => false,
    }
}

/// The Rust type for a value at a manager boundary (param/body/return). Mirrors
/// the model layer: `Option<T>` optionality, `String` dates (interim), decls to
/// their `crate::models::…` path.
fn rust_type(program: &ir::Program, ty: &ir::Type) -> String {
    match ty {
        ir::Type::Bool => "bool".into(),
        ir::Type::Int64 => "i64".into(),
        ir::Type::Float64 => "f64".into(),
        ir::Type::String | ir::Type::Date | ir::Type::DateTime => "String".into(),
        ir::Type::Binary => "Vec<u8>".into(),
        ir::Type::JsonValue => "serde_json::Value".into(),
        ir::Type::List(inner) => format!("Vec<{}>", rust_type(program, inner)),
        ir::Type::Map(inner) => {
            format!(
                "std::collections::HashMap<String, {}>",
                rust_type(program, inner)
            )
        }
        ir::Type::Decl(id) => {
            let decl = program.decl(*id);
            format!(
                "crate::models::{}::{}",
                module_name(&decl.module),
                type_name(decl.name.as_str())
            )
        }
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => {
            format!("Option<{}>", rust_type(program, inner))
        }
    }
}

fn unwrap_optionality(ty: &ir::Type) -> &ir::Type {
    match ty {
        ir::Type::Optional(inner) | ir::Type::Nullable(inner) => unwrap_optionality(inner),
        ir::Type::Bool
        | ir::Type::Int64
        | ir::Type::Float64
        | ir::Type::String
        | ir::Type::Date
        | ir::Type::DateTime
        | ir::Type::Binary
        | ir::Type::JsonValue
        | ir::Type::List(_)
        | ir::Type::Map(_)
        | ir::Type::Decl(_) => ty,
    }
}

fn base_class(base: ir::BaseUrl) -> &'static str {
    match base {
        ir::BaseUrl::Api => "api",
        ir::BaseUrl::ApiRoot => "api_root",
        ir::BaseUrl::Upload => "upload",
        ir::BaseUrl::UploadSession => "upload_session",
        ir::BaseUrl::OAuthAuthorize => "oauth_authorize",
        ir::BaseUrl::Download => "download",
    }
}

fn http_method(method: ir::HttpMethod) -> &'static str {
    match method {
        ir::HttpMethod::Get => "GET",
        ir::HttpMethod::Put => "PUT",
        ir::HttpMethod::Post => "POST",
        ir::HttpMethod::Delete => "DELETE",
        ir::HttpMethod::Options => "OPTIONS",
        ir::HttpMethod::Head => "HEAD",
        ir::HttpMethod::Patch => "PATCH",
        ir::HttpMethod::Trace => "TRACE",
    }
}

/// A `snake_case` identifier for a parameter/field, keyword-safe.
fn field_ident(name: &str) -> String {
    let base = snake(name);
    let base = if base.is_empty() {
        "field".to_string()
    } else if base.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("n{base}")
    } else {
        base
    };
    if RUST_KEYWORDS.contains(&base.as_str()) {
        format!("r#{base}")
    } else if RAW_UNSAFE.contains(&base.as_str()) {
        format!("{base}_")
    } else {
        base
    }
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "dyn", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
    "await", "abstract", "become", "box", "do", "final", "macro", "override", "priv", "typeof",
    "unsized", "virtual", "yield", "try", "gen",
];

const RAW_UNSAFE: &[&str] = &["self", "crate", "super", "Self"];

/// Generation-side helpers embedded in the SDK (not part of the runtime
/// contract): RFC 3986 path-segment percent-encoding.
const INTERNAL: &str = "\
// Code generated by box-gantry. DO NOT EDIT.

/// Comma-join a slice into a query value, converting each element with `f`.
pub(crate) fn join<T>(items: &[T], f: impl Fn(&T) -> String) -> String {
    items.iter().map(f).collect::<Vec<_>>().join(\",\")
}

/// Percent-encode a path-segment value (unreserved chars pass through).
pub(crate) fn path_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for &byte in value.as_bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' => {
                out.push(byte as char);
            }
            _ => {
                out.push('%');
                out.push_str(&format!(\"{byte:02X}\"));
            }
        }
    }
    out
}
";

#[cfg(test)]
mod tests {
    use super::*;
    use gantry_ir::{
        BaseUrl, Decl, DeclId, DeclKind, Field, HttpMethod, Identifier, ModulePath, Operation,
        Param, ParamLocation, Program, ResponseShape, StructDecl, Type,
    };

    fn ident(s: &str) -> Identifier {
        Identifier::new(s).unwrap()
    }

    /// A program with a `File` struct and a `GET /files/{file_id}` operation in
    /// the `files` manager.
    fn program() -> Program {
        let mut p = Program::default();
        p.add(Decl {
            name: ident("File"),
            module: ModulePath(vec![ident("schemas")]),
            api_version: None,
            kind: DeclKind::Struct(StructDecl {
                fields: vec![Field {
                    name: ident("id"),
                    wire_name: "id".into(),
                    ty: Type::String,
                }],
            }),
        });
        p.operations.push(Operation {
            name: ident("get_by_id"),
            variation: None,
            manager: ident("files"),
            api_version: None,
            method: HttpMethod::Get,
            base_url: BaseUrl::Api,
            path: vec![
                ir::PathSegment::Literal("files".into()),
                ir::PathSegment::Parameter(ident("file_id")),
            ],
            params: vec![Param {
                name: ident("file_id"),
                wire_name: "file_id".into(),
                location: ParamLocation::Path,
                ty: Type::String,
            }],
            request: None,
            response: ResponseShape::Json(Type::Decl(DeclId(0))),
            deprecated: false,
        });
        p
    }

    fn render_manager(p: &Program) -> String {
        let mut printer = Printer {
            program: p,
            base_version: None,
            body: String::new(),
            uses_path_escape: false,
        };
        printer.manager("files", &[0]);
        printer.body
    }

    #[test]
    fn manager_method_is_async_and_routes_through_the_contract() {
        let p = program();
        let out = render_manager(&p);
        assert!(out.contains("pub struct FilesManager {"), "{out}");
        assert!(out.contains("session: std::sync::Arc<runtime::Client>"));
        // Async method, decl-typed return through the runtime error.
        assert!(out.contains(
            "pub async fn get_by_id(&self, file_id: String) \
             -> Result<crate::models::schemas::File, Error>"
        ));
        // URL from structured segments; path param percent-escaped.
        assert!(out.contains("let mut url = self.session.base_url(\"api\");"));
        assert!(out.contains("url.push_str(\"/files\");"));
        assert!(out.contains("let seg = path_escape(&file_id);"));
        // Fetch + decode via the contract only.
        assert!(out.contains("self.session.fetch(req).await?"));
        assert!(out.contains("runtime::response_bytes(&resp)?"));
        assert!(out.contains("Ok(serde_json::from_slice(&data)?)"));
    }

    #[test]
    fn client_wires_one_field_per_manager() {
        let out = client_file(&[(&"files".to_string(), &vec![0usize])]);
        assert!(
            out.contains("pub files: crate::managers::files::FilesManager,"),
            "{out}"
        );
        assert!(out.contains("crate::runtime::Client::new(auth)"));
        assert!(out.contains("FilesManager::new(session.clone())"));
    }
}
