//! VR-1.5: generate the full real spec's TypeScript model layer → `tsc
//! --noEmit` clean under `strict`. The primary TypeScript CI signal, the same
//! real-toolchain loop that anchors the Go/Rust backends.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_typescript::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_typescript::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let program = Box::leak(Box::new(lowering.program));
    let analysis = gantry_sema::analyze(program).unwrap();
    gantry_backend_typescript::generate(&analysis, &gantry_manifest::typescript(), &build)
}

fn write_all(dir: &Path, files: &[gantry_backend_typescript::GeneratedFile]) {
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, &file.content).unwrap();
    }
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated `.ts` file carries the do-not-edit header (FR-6.3).
    for file in &once {
        if file.path.ends_with(".ts") {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
        }
    }
    // The package scaffold + module tree.
    assert!(once.iter().any(|f| f.path == "package.json"));
    assert!(once.iter().any(|f| f.path == "tsconfig.json"));
    assert!(once.iter().any(|f| f.path == "src/index.ts"));
    assert!(once.iter().any(|f| f.path == "src/models/index.ts"));
    // The managers/client surface, calling only through the runtime contract.
    assert!(once.iter().any(|f| f.path == "src/client.ts"));
    assert!(once.iter().any(|f| f.path == "src/managers/index.ts"));
    assert!(once.iter().any(|f| f.path == "src/internal.ts"));
    let client = once.iter().find(|f| f.path == "src/client.ts").unwrap();
    assert!(client.content.contains("export class Client {"));
    assert!(
        client
            .content
            .contains("const session = new Session(auth);")
    );
    // Every manager method is `async` and reaches the network only via the
    // `this.session.fetch(...)` contract surface (FR-5.2).
    let managers: String = once
        .iter()
        .filter(|f| f.path.starts_with("src/managers/") && f.path.ends_with(".ts"))
        .map(|f| f.content.as_str())
        .collect();
    assert!(managers.contains("export class "), "no manager classes");
    assert!(managers.contains("): Promise<"), "no async manager methods");
    assert!(
        managers.contains("await this.session.fetch(req)"),
        "managers must fetch through the runtime session"
    );
    // The runtime-contract stubs (FR-5.3): managers type-check against these.
    let runtime = once.iter().find(|f| f.path == "src/runtime.ts").unwrap();
    assert!(
        runtime
            .content
            .contains("export class BoxApiError extends Error")
    );
    assert!(
        runtime
            .content
            .contains("async fetch(request: Request, signal?: AbortSignal): Promise<Response>")
    );

    let models: String = once
        .iter()
        .filter(|f| f.path.starts_with("src/models/") && f.path.ends_with(".ts"))
        .map(|f| f.content.as_str())
        .collect();
    // Structs → interfaces, with the tri-state as `field?: T` (TR-TS.2).
    assert!(
        models.contains("export interface "),
        "no interfaces emitted"
    );
    assert!(models.contains("?: "), "no optional (tri-state) fields");
    // `oneOf` → discriminated unions: each member pins its literal tag via an
    // intersection (so the union narrows even with open discriminator enums),
    // and open unions add a discriminator-bearing catch-all that retains an
    // unknown tag without swallowing `{}` (TR-TS.1).
    assert!(
        models.contains(" & { "),
        "union members don't pin the discriminator literal"
    );
    assert!(
        models.contains("; [key: string]: unknown }"),
        "no open-union catch-all member"
    );
    // Open enums → string-literal unions widened with `(string & {})` (TR-TS.1).
    assert!(
        models.contains(" | (string & {})"),
        "no widened open-enum union"
    );
    // Provenance (NF-7).
    let build = once.iter().find(|f| f.path == "src/buildinfo.ts").unwrap();
    assert!(build.content.contains("export const ENGINE ="));
    assert!(build.content.contains("export const SPEC_FINGERPRINT ="));

    // Reference docs (FR-7.7): the index, one page per manager, and the three
    // cross-cutting guides. Every `.md` carries the do-not-edit header too.
    for file in &once {
        if file.path.ends_with(".md") {
            assert!(
                file.content.starts_with("<!-- Generated by box-gantry"),
                "{} lacks the doc header",
                file.path
            );
        }
    }
    assert!(once.iter().any(|f| f.path == "docs/README.md"));
    assert!(once.iter().any(|f| f.path == "docs/auth.md"));
    assert!(once.iter().any(|f| f.path == "docs/pagination.md"));
    assert!(once.iter().any(|f| f.path == "docs/errors.md"));
    // One reference page per manager — the same count as the manager modules
    // (the barrel/index files aren't managers).
    let manager_modules = once
        .iter()
        .filter(|f| {
            f.path.starts_with("src/managers/")
                && f.path.ends_with(".ts")
                && f.path != "src/managers/index.ts"
        })
        .count();
    let manager_docs = once
        .iter()
        .filter(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md"))
        .count();
    assert_eq!(
        manager_docs, manager_modules,
        "one reference page per manager"
    );
    // The auth guide names all four Box flows (the conformance recognizer reads
    // these), and a manager page describes real methods (an `## ` heading and an
    // HTTP line generated from the IR).
    let auth = once.iter().find(|f| f.path == "docs/auth.md").unwrap();
    for flow in ["Developer Token", "Client Credentials", "JWT", "OAuth"] {
        assert!(auth.content.contains(flow), "auth guide omits {flow}");
    }
    let a_manager_page = once
        .iter()
        .find(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md"))
        .unwrap();
    assert!(
        a_manager_page.content.contains("\n## "),
        "no method heading"
    );
    assert!(
        a_manager_page.content.contains("**Returns:**"),
        "no return type documented"
    );
}

/// VR-1.5: the generated package type-checks clean under `strict` with the
/// TypeScript 7 native compiler (`tsc --noEmit`). CI runs this gate.
#[test]
fn the_real_spec_models_type_check() {
    if Command::new("tsc").arg("--version").output().is_err() {
        eprintln!("SKIPPED: tsc not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-ts-models-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    let check = Command::new("tsc")
        .args(["--noEmit", "-p", "tsconfig.json"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "tsc --noEmit failed under strict (VR-1.5):\n{}\n{}",
        String::from_utf8_lossy(&check.stdout),
        String::from_utf8_lossy(&check.stderr)
    );
}

/// FR-5.2/TR-TS.5: the generated SDK must type-check against the real
/// hand-written runtime, not only the stubs — proving the `fetch` runtime
/// exports the contract's names with matching signatures.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("tsc").arg("--version").output().is_err() {
        eprintln!("SKIPPED: tsc not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-ts-runtime-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    // Replace the compile-time stub with the real runtime: drop the generated
    // `src/runtime.ts` and copy every source file of the hand-written runtime
    // into `src/`. Its `runtime.ts` re-exports `auth`/`errors`, so the managers'
    // `../runtime.js` imports resolve to the real types and functions.
    let runtime_src = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../runtimes/typescript/gantryruntime/src")
        .canonicalize()
        .unwrap();
    std::fs::remove_file(dir.join("src/runtime.ts")).unwrap();
    for entry in std::fs::read_dir(&runtime_src).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().is_none_or(|e| e != "ts") {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        // The JWT flow is a Node-only leaf module (`node:crypto`), never
        // referenced by the generated SDK; skip it (and its ambient node type
        // decl) so this gate stays platform-neutral. The runtime's own tsc gate
        // covers it.
        if name == "jwt.ts" || name == "node-crypto.d.ts" {
            continue;
        }
        std::fs::copy(&path, dir.join("src").join(&name)).unwrap();
    }

    // A smoke module proving the public API composes: constructing the client
    // from a real auth flow forces the whole manager tree to type-check against
    // the real runtime.
    std::fs::write(
        dir.join("src/smoke.ts"),
        "import { Client, runtime } from './index.js';\n\
         export const client = new Client(runtime.developerToken('dev'));\n",
    )
    .unwrap();

    let check = Command::new("tsc")
        .args(["--noEmit", "-p", "tsconfig.json"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "generated SDK does not type-check against the real runtime (contract drift, FR-5.2):\n{}\n{}",
        String::from_utf8_lossy(&check.stdout),
        String::from_utf8_lossy(&check.stderr)
    );
}
