//! VR-1.1: generate the full real spec's models → `go build` + `go vet`
//! clean, gofmt-clean — the primary CI signal, from the backend's first
//! week (G-1: this loop found 11 bugs snapshot tests never could).

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_go::GeneratedFile> {
    let lowering = gantry_spec::lower(
        &SpecSet::load(&[
            fixture("openapi.json"),
            fixture("openapi-v2025.0.json"),
            fixture("openapi-v2026.0.json"),
        ])
        .unwrap(),
    )
    .unwrap();
    let program = Box::leak(Box::new(lowering.program));
    let analysis = gantry_sema::analyze(program).unwrap();
    gantry_backend_go::generate(&analysis)
        .expect("the go backend must express the verified program")
}

fn write_all(dir: &Path, files: &[gantry_backend_go::GeneratedFile]) {
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, &file.content).unwrap();
    }
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated file carries the do-not-edit header (FR-6.3).
    for file in &once {
        if file.path.ends_with(".go") {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
        }
    }
    // Pagination iterators are synthesized for the paged operations
    // (FR-7.3, TR-Go.4): 54 marker + 10 offset. Pinned so the count only
    // moves deliberately with the spec (VR-6 lineage).
    let paginators: usize = once
        .iter()
        .filter(|f| f.path.starts_with("managers/"))
        .map(|f| f.content.matches("Paginate(ctx ").count())
        .sum();
    assert_eq!(paginators, 64, "expected 64 pagination iterators");
    let offset_iters: usize = once
        .iter()
        .filter(|f| f.path.starts_with("managers/"))
        .map(|f| f.content.matches("var offset int64").count())
        .sum();
    assert_eq!(offset_iters, 10, "expected 10 offset iterators");
}

#[test]
fn the_real_spec_models_compile() {
    if Command::new("go").arg("version").output().is_err() {
        eprintln!("SKIPPED: go toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-go-models-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    let build = Command::new("go")
        .args(["build", "./..."])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        build.status.success(),
        "go build failed (VR-1.1):\n{}",
        String::from_utf8_lossy(&build.stderr)
    );

    let vet = Command::new("go")
        .args(["vet", "./..."])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        vet.status.success(),
        "go vet failed (VR-1.1):\n{}",
        String::from_utf8_lossy(&vet.stderr)
    );

    let fmt = Command::new("gofmt").arg("-l").arg(&dir).output().unwrap();
    assert!(
        fmt.status.success() && fmt.stdout.is_empty(),
        "gofmt wants changes (G-17) in:\n{}",
        String::from_utf8_lossy(&fmt.stdout)
    );
}
