//! Per-manager schema-file split (D-201): a declaration exclusively reached
//! by one manager's operations lands in that manager's own `schemas/*.go`
//! file; a declaration shared by two-or-more managers (or reached by none)
//! stays in the catch-all `schemas/schemas.go` — never lost, never
//! duplicated.

use gantry_backend_go::BuildInfo;
use gantry_ir as ir;

fn ident(name: &str) -> ir::Identifier {
    ir::Identifier::new(name).unwrap()
}

fn schemas() -> ir::ModulePath {
    ir::ModulePath(vec![ident("schemas")])
}

fn empty_struct(name: &str) -> ir::Decl {
    ir::Decl {
        name: ident(name),
        module: schemas(),
        api_version: None,
        kind: ir::DeclKind::Struct(ir::StructDecl {
            fields: vec![],
            extra: None,
        }),
    }
}

fn op(name: &str, manager: &str, response: ir::Type) -> ir::Operation {
    ir::Operation {
        name: ident(name),
        variation: None,
        manager: ident(manager),
        api_version: None,
        method: ir::HttpMethod::Get,
        base_url: ir::BaseUrl::Api,
        path: vec![],
        params: vec![],
        request: None,
        response: ir::ResponseShape::Json(response),
        deprecated: false,
    }
}

fn struct_decl(name: &str, fields: Vec<ir::Field>) -> ir::Decl {
    ir::Decl {
        name: ident(name),
        module: schemas(),
        api_version: None,
        kind: ir::DeclKind::Struct(ir::StructDecl {
            fields,
            extra: None,
        }),
    }
}

fn field(name: &str, ty: ir::Type) -> ir::Field {
    ir::Field {
        name: ident(name),
        wire_name: name.to_string(),
        ty,
    }
}

/// `Shared` is reached by both `files` and `folders`; `FileOnly` (with its
/// only-reachable-through-it `Nested`) by `files` alone; `FolderOnly` by
/// `folders` alone; `Orphan` by neither.
fn generate() -> Vec<gantry_backend_go::GeneratedFile> {
    let decls = vec![
        empty_struct("Shared"),                                        // 0
        struct_decl("Nested", vec![field("value", ir::Type::String)]), // 1
        struct_decl(
            "FileOnly",
            vec![
                field("nested", ir::Type::Decl(ir::DeclId(1))),
                field("when", ir::Type::Optional(Box::new(ir::Type::DateTime))),
            ],
        ), // 2
        empty_struct("FolderOnly"),                                    // 3
        empty_struct("Orphan"),                                        // 4
    ];
    let program = ir::Program {
        decls,
        operations: vec![
            op("getShared1", "files", ir::Type::Decl(ir::DeclId(0))),
            op("getShared2", "folders", ir::Type::Decl(ir::DeclId(0))),
            op("getFileOnly", "files", ir::Type::Decl(ir::DeclId(2))),
            op("getFolderOnly", "folders", ir::Type::Decl(ir::DeclId(3))),
        ],
    };
    let program = Box::leak(Box::new(program));
    let analysis = gantry_sema::analyze(program).expect("fixture program must analyze");
    let build = BuildInfo::new("fixtures");
    gantry_backend_go::generate_models(&analysis, &build)
}

fn file(files: &[gantry_backend_go::GeneratedFile], path: &str) -> String {
    files
        .iter()
        .find(|f| f.path == path)
        .unwrap_or_else(|| panic!("expected a generated file at {path:?}"))
        .content
        .clone()
}

#[test]
fn a_sole_owned_decl_lands_in_its_managers_file() {
    let files = generate();
    let owned = file(&files, "schemas/files.go");
    assert!(owned.contains("type FileOnly struct"), "{owned}");
    assert!(
        owned.contains("type Nested struct"),
        "Nested is only reachable through FileOnly, so it belongs to files too:\n{owned}"
    );
    assert!(!owned.contains("type Shared struct"), "{owned}");
}

#[test]
fn a_different_managers_decl_lands_in_its_own_file() {
    let files = generate();
    let owned = file(&files, "schemas/folders.go");
    assert!(owned.contains("type FolderOnly struct"), "{owned}");
    assert!(!owned.contains("type FileOnly"), "{owned}");
}

#[test]
fn shared_and_orphaned_decls_stay_in_the_catch_all() {
    let files = generate();
    let catch_all = file(&files, "schemas/schemas.go");
    assert!(catch_all.contains("type Shared struct"), "{catch_all}");
    assert!(catch_all.contains("type Orphan struct"), "{catch_all}");
    assert!(!catch_all.contains("type FileOnly"), "{catch_all}");
    assert!(!catch_all.contains("type FolderOnly"), "{catch_all}");
}

#[test]
fn every_split_file_has_the_generated_header_and_package() {
    let files = generate();
    for path in [
        "schemas/schemas.go",
        "schemas/files.go",
        "schemas/folders.go",
    ] {
        let content = file(&files, path);
        assert!(
            content.starts_with("// Code generated by box-gantry "),
            "{path} is missing the generated-file header:\n{content}"
        );
        assert!(
            content.contains("package schemas"),
            "{path} is missing its package clause:\n{content}"
        );
    }
}

/// The partition safety net: every declared type name appears in exactly one
/// `schemas/*.go` file — a bucketing bug that lost or duplicated a
/// declaration would fail this, not just look slightly off.
#[test]
fn every_decl_appears_in_exactly_one_file() {
    let files = generate();
    for name in ["Shared", "Nested", "FileOnly", "FolderOnly", "Orphan"] {
        let owners: Vec<&str> = files
            .iter()
            .filter(|f| f.path.starts_with("schemas/") && f.path.ends_with(".go"))
            .filter(|f| f.content.contains(&format!("type {name} struct")))
            .map(|f| f.path.as_str())
            .collect();
        assert_eq!(
            owners.len(),
            1,
            "{name} should appear in exactly one schemas/*.go file, found in {owners:?}"
        );
    }
}

/// Per-file imports stay minimal: `FileOnly`'s `time.Time` import belongs
/// only to `files.go`, not to every split file.
#[test]
fn per_file_imports_are_minimal() {
    let files = generate();
    let files_go = file(&files, "schemas/files.go");
    assert!(files_go.contains("import \"time\""), "{files_go}");
    let folders_go = file(&files, "schemas/folders.go");
    assert!(
        !folders_go.contains("import"),
        "folders.go references nothing external:\n{folders_go}"
    );
}
