//! VR-1.2: generate the full real spec's SDK (models + async managers/client +
//! runtime stubs) → `cargo fmt --check` + `cargo check` + `clippy -D warnings`
//! clean. The primary Rust CI signal (TR-Rust.4), the same real-toolchain loop
//! that anchored the Go backend.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_rust::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_rust::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let program = Box::leak(Box::new(lowering.program));
    let analysis = gantry_sema::analyze(program).unwrap();
    gantry_backend_rust::generate(&analysis, &gantry_manifest::rust(), &build)
}

fn write_all(dir: &Path, files: &[gantry_backend_rust::GeneratedFile]) {
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, &file.content).unwrap();
    }
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated Rust file carries the do-not-edit header (FR-6.3).
    for file in &once {
        if file.path.ends_with(".rs") {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
        }
    }
    // The module tree: one module file per IR module plus the mod root.
    assert!(once.iter().any(|f| f.path == "src/models/mod.rs"));
    assert!(once.iter().any(|f| f.path == "src/models/schemas.rs"));
    // The managers/client/runtime layer (M5 slice 3).
    assert!(once.iter().any(|f| f.path == "src/managers/mod.rs"));
    assert!(once.iter().any(|f| f.path == "src/client.rs"));
    assert!(once.iter().any(|f| f.path == "src/runtime.rs"));
    assert!(once.iter().any(|f| f.path == "src/internal.rs"));
    // Methods are async and route through the runtime contract, never direct
    // HTTP (FR-5.2).
    let files = once
        .iter()
        .find(|f| f.path == "src/managers/files.rs")
        .unwrap();
    assert!(files.content.contains("pub async fn "), "{}", files.path);
    assert!(files.content.contains("self.session.fetch(req).await?"));
    // The client wires one manager field per API area over a shared session.
    let client = once.iter().find(|f| f.path == "src/client.rs").unwrap();
    assert!(client.content.contains("pub struct Client {"));
    assert!(
        client
            .content
            .contains("std::sync::Arc::new(crate::runtime::Client::new(auth))")
    );
    // Date/time fields are typed via chrono (not strings), and the crate
    // manifest declares the lean chrono dependency.
    let models: String = once
        .iter()
        .filter(|f| f.path.starts_with("src/models/"))
        .map(|f| f.content.as_str())
        .collect();
    assert!(
        models.contains("chrono::NaiveDate"),
        "date fields should be chrono-typed"
    );
    assert!(
        models.contains("chrono::DateTime<chrono::Utc>"),
        "date-time fields should be chrono-typed"
    );
    let cargo = once.iter().find(|f| f.path == "Cargo.toml").unwrap();
    assert!(cargo.content.contains(
        "chrono = { version = \"0.4\", default-features = false, features = [\"serde\", \"alloc\"] }"
    ));
}

#[test]
fn the_real_spec_models_compile() {
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("SKIPPED: cargo toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-rust-models-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    // rustfmt-clean by construction (TR-Rust.4, G-17).
    let fmt = Command::new("cargo")
        .args(["fmt", "--check"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        fmt.status.success(),
        "cargo fmt --check wants changes (TR-Rust.4):\n{}\n{}",
        String::from_utf8_lossy(&fmt.stdout),
        String::from_utf8_lossy(&fmt.stderr)
    );

    let check = Command::new("cargo")
        .args(["check"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "cargo check failed (VR-1.2):\n{}",
        String::from_utf8_lossy(&check.stderr)
    );

    let clippy = Command::new("cargo")
        .args(["clippy", "--", "-D", "warnings"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        clippy.status.success(),
        "clippy failed (TR-Rust.4):\n{}",
        String::from_utf8_lossy(&clippy.stderr)
    );
}

/// FR-5.2/TR-Rust.5: the generated SDK must compile against the real
/// hand-written runtime, not only the stubs — proving the `reqwest`/`tokio`
/// runtime satisfies the contract signatures the managers call.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("SKIPPED: cargo toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-rust-runtime-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    // Point `crate::runtime` at the real crate instead of the compile-time
    // stub: a one-line re-export makes every `runtime::…` path the managers
    // call resolve to the hand-written runtime's types and functions.
    let runtime_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../runtimes/rust/gantryruntime")
        .canonicalize()
        .unwrap();
    std::fs::write(
        dir.join("src/runtime.rs"),
        "// Test shim: re-export the real runtime in place of the stub.\n\
         pub use gantryruntime::*;\n",
    )
    .unwrap();

    // Add the path dependency on the real runtime crate.
    let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
    let manifest = format!(
        "{manifest}gantryruntime = {{ path = {:?} }}\n",
        runtime_dir.to_str().unwrap()
    );
    std::fs::write(dir.join("Cargo.toml"), manifest).unwrap();

    // A smoke example proving the public API composes: construct the client
    // from an auth flow (which forces the whole manager tree to typecheck
    // against the real runtime).
    std::fs::create_dir_all(dir.join("examples")).unwrap();
    std::fs::write(
        dir.join("examples/smoke.rs"),
        "fn main() {\n\
         \x20   let _client =\n\
         \x20       box_sdk::client::Client::new(box_sdk::runtime::Auth::developer_token(\"dev\"));\n\
         }\n",
    )
    .unwrap();

    let check = Command::new("cargo")
        .args(["check", "--examples"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "generated SDK does not compile against the real runtime (contract drift, FR-5.2):\n{}",
        String::from_utf8_lossy(&check.stderr)
    );
}
