//! VR-1.2: generate the full real spec's SDK (models + async managers/client +
//! runtime stubs) → `cargo fmt --check` + `cargo check` + `clippy -D warnings`
//! clean. The primary Rust CI signal (TR-Rust.4), the same real-toolchain loop
//! that anchored the Go backend.

use std::path::{Path, PathBuf};
use std::process::Command;

use gantry_spec::SpecSet;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/specs")
        .join(name)
}

fn generate() -> Vec<gantry_backend_rust::GeneratedFile> {
    let set = SpecSet::load(&[
        fixture("openapi.json"),
        fixture("openapi-v2025.0.json"),
        fixture("openapi-v2026.0.json"),
    ])
    .unwrap();
    let build = gantry_backend_rust::BuildInfo::new(set.fingerprint());
    let lowering = gantry_spec::lower(&set).unwrap();
    let program = Box::leak(Box::new(lowering.program));
    let analysis = gantry_sema::analyze(program).unwrap();
    gantry_backend_rust::generate(&analysis, &gantry_manifest::rust(), &build)
}

fn write_all(dir: &Path, files: &[gantry_backend_rust::GeneratedFile]) {
    for file in files {
        let path = dir.join(&file.path);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, &file.content).unwrap();
    }
}

#[test]
fn generation_is_deterministic() {
    let once = generate();
    let twice = generate();
    assert_eq!(once.len(), twice.len());
    for (a, b) in once.iter().zip(&twice) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.content, b.content, "nondeterministic: {}", a.path);
    }
    // Every generated Rust file carries the do-not-edit header (FR-6.3).
    for file in &once {
        if file.path.ends_with(".rs") {
            assert!(
                file.content.starts_with("// Code generated by "),
                "{} lacks the header",
                file.path
            );
        }
    }
    // The module tree: one module file per IR module plus the mod root.
    assert!(once.iter().any(|f| f.path == "src/models/mod.rs"));
    assert!(once.iter().any(|f| f.path == "src/models/schemas.rs"));
    // The managers/client/runtime layer (M5 slice 3).
    assert!(once.iter().any(|f| f.path == "src/managers/mod.rs"));
    assert!(once.iter().any(|f| f.path == "src/client.rs"));
    // The runtime is vendored as a module tree, not the single-file stub (D-192).
    assert!(once.iter().any(|f| f.path == "src/runtime/mod.rs"));
    assert!(once.iter().any(|f| f.path == "src/internal.rs"));
    // Methods are async and route through the runtime contract, never direct
    // HTTP (FR-5.2).
    let files = once
        .iter()
        .find(|f| f.path == "src/managers/files.rs")
        .unwrap();
    assert!(files.content.contains("pub async fn "), "{}", files.path);
    assert!(files.content.contains("self.session.fetch(req).await?"));
    // Option A (FR-7.3): the public list method *is* the async paginator; the
    // single-page fetch it drives is the private `<method>_page`. No `_paginate`.
    let folders = once
        .iter()
        .find(|f| f.path == "src/managers/folders.rs")
        .unwrap();
    assert!(folders.content.contains("Paginator {"), "{}", folders.path);
    assert!(
        folders.content.contains("pub fn list_items(")
            && folders.content.contains(") -> FoldersListItemsPaginator {"),
        "{}",
        folders.path
    );
    assert!(
        folders.content.contains("async fn list_items_page(")
            && !folders.content.contains("pub async fn list_items_page("),
        "{}",
        folders.path
    );
    assert!(!folders.content.contains("_paginate("), "{}", folders.path);
    assert!(folders.content.contains("pub async fn next(&mut self)"));
    // Reference docs (FR-7.7): an index, one page per manager, and the three
    // cross-cutting guides — describing the real Rust surface.
    assert!(once.iter().any(|f| f.path == "docs/README.md"));
    assert!(
        once.iter()
            .any(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md")),
        "expected per-manager doc pages"
    );
    // Every method section carries a synthesized call snippet (FR-7.7): one
    // `**Example**` per `## <method>` heading, each a `rust` fence through the
    // client.
    for page in once
        .iter()
        .filter(|f| f.path.starts_with("docs/managers/") && f.path.ends_with(".md"))
    {
        let methods = page.content.matches("\n## ").count();
        let examples = page.content.matches("**Example**").count();
        assert_eq!(
            methods, examples,
            "{}: {methods} methods but {examples} example snippets",
            page.path
        );
        assert!(
            page.content.contains("```rust\n") && page.content.contains("client."),
            "{} example snippet is missing",
            page.path
        );
    }
    for guide in ["docs/auth.md", "docs/pagination.md", "docs/errors.md"] {
        assert!(once.iter().any(|f| f.path == guide), "missing {guide}");
    }
    // The auth guide documents every Box auth flow, and describes types with
    // the real Rust surface (chrono-typed, `Result`-returning).
    let auth = once.iter().find(|f| f.path == "docs/auth.md").unwrap();
    for flow in ["Developer Token", "Client Credentials", "JWT", "OAuth"] {
        assert!(auth.content.contains(flow), "auth guide missing {flow}");
    }

    // Generated round-trip / behavioral tests (FR-7.8, VR-4): the fixed
    // serialization tests plus one per-union round-trip test, run by the VR-1.2
    // gate's `cargo test`.
    assert!(once.iter().any(|f| f.path == "src/serialization_tests.rs"));
    let roundtrip = once
        .iter()
        .find(|f| f.path == "src/roundtrip_tests.rs")
        .unwrap();
    assert!(
        roundtrip.content.contains("_round_trip("),
        "expected generated per-union round-trip tests"
    );

    // The client wires one manager field per API area over a shared session.
    let client = once.iter().find(|f| f.path == "src/client.rs").unwrap();
    assert!(client.content.contains("pub struct Client {"));
    assert!(
        client
            .content
            .contains("std::sync::Arc::new(crate::runtime::Client::new(auth))")
    );
    // Date/time fields are typed via chrono (not strings), and the crate
    // manifest declares the lean chrono dependency.
    let models: String = once
        .iter()
        .filter(|f| f.path.starts_with("src/models/"))
        .map(|f| f.content.as_str())
        .collect();
    assert!(
        models.contains("chrono::NaiveDate"),
        "date fields should be chrono-typed"
    );
    assert!(
        models.contains("chrono::DateTime<chrono::Utc>"),
        "date-time fields should be chrono-typed"
    );
    let cargo = once.iter().find(|f| f.path == "Cargo.toml").unwrap();
    assert!(cargo.content.contains(
        "chrono = { version = \"0.4\", default-features = false, features = [\"serde\", \"alloc\"] }"
    ));
    // NF-8: publish-ready manifest metadata + a shipped README.
    for meta in ["description = ", "license = ", "repository = ", "readme = "] {
        assert!(cargo.content.contains(meta), "Cargo.toml missing {meta}");
    }
    assert!(once.iter().any(|f| f.path == "README.md"));
}

#[test]
fn the_real_spec_models_compile() {
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("SKIPPED: cargo toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-rust-models-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    // rustfmt-clean by construction (TR-Rust.4, G-17).
    let fmt = Command::new("cargo")
        .args(["fmt", "--check"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        fmt.status.success(),
        "cargo fmt --check wants changes (TR-Rust.4):\n{}\n{}",
        String::from_utf8_lossy(&fmt.stdout),
        String::from_utf8_lossy(&fmt.stderr)
    );

    let check = Command::new("cargo")
        .args(["check"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "cargo check failed (VR-1.2):\n{}",
        String::from_utf8_lossy(&check.stderr)
    );

    let clippy = Command::new("cargo")
        .args(["clippy", "--all-targets", "--", "-D", "warnings"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        clippy.status.success(),
        "clippy failed (TR-Rust.4):\n{}",
        String::from_utf8_lossy(&clippy.stderr)
    );

    // The generated round-trip / behavioral tests compile *and pass* (FR-7.8,
    // VR-4): the tri-state, typed date/time, and union discriminator dispatch.
    let test = Command::new("cargo")
        .args(["test"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        test.status.success(),
        "generated tests failed (FR-7.8, VR-4):\n{}\n{}",
        String::from_utf8_lossy(&test.stdout),
        String::from_utf8_lossy(&test.stderr)
    );
}

/// FR-5.2/TR-Rust.5: the generated SDK must compile against the real
/// hand-written runtime, not only the stubs — proving the `reqwest`/`tokio`
/// runtime satisfies the contract signatures the managers call.
#[test]
fn the_generated_sdk_compiles_against_the_real_runtime() {
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("SKIPPED: cargo toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-rust-runtime-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    // A smoke example proving the public API composes: construct the client
    // from an auth flow (which forces the whole manager tree to typecheck
    // against the real runtime).
    std::fs::create_dir_all(dir.join("examples")).unwrap();
    std::fs::write(
        dir.join("examples/smoke.rs"),
        "fn main() {\n\
         \x20   let _client =\n\
         \x20       box_open_sdk::client::Client::new(box_open_sdk::runtime::Auth::developer_token(\"dev\"));\n\
         }\n",
    )
    .unwrap();

    let check = Command::new("cargo")
        .args(["check", "--examples"])
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        check.status.success(),
        "generated SDK does not compile against the real runtime (contract drift, FR-5.2):\n{}",
        String::from_utf8_lossy(&check.stderr)
    );
}

/// NF-8: the ship artifact is a **self-contained, publishable crate**. Assemble
/// it the way the release pipeline does — vendor the real runtime into the crate
/// as a `runtime` module (as Go/TS vendor their runtimes; a `{ path, version }`
/// dep can't `cargo publish` while `gantryruntime` is unpublished) — and prove
/// `cargo publish --dry-run` is clean. Needs the cargo toolchain + the crates.io
/// index; skips when cargo is absent (like the swap gate). CI runs this gate.
#[test]
fn the_generated_sdk_packages_for_publish() {
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("SKIPPED: cargo toolchain not available; CI runs this gate");
        return;
    }
    let dir = std::env::temp_dir().join(format!("gantry-rust-pack-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    write_all(&dir, &generate());

    let mut cmd = Command::new("cargo");
    cmd.args(["publish", "--dry-run", "--allow-dirty"])
        .current_dir(&dir)
        // Force plain, deterministic output: CI sets `CARGO_TERM_COLOR=always`,
        // whose ANSI escapes split the "Uploading box-open-sdk" success line the
        // assertion below matches on (`Uploading\x1b[0m box-sdk`).
        .env("CARGO_TERM_COLOR", "never");
    // The crate is assembled in a temp dir *outside* the repo, so the workspace
    // `rust-toolchain.toml` pin (NF-6) doesn't reach it — the verify build would
    // otherwise use whatever cargo the host defaults to. Force the pinned
    // toolchain so this gate is reproducible and matches the rest of CI.
    if let Some(channel) = pinned_toolchain() {
        cmd.env("RUSTUP_TOOLCHAIN", channel);
    }
    let publish = cmd.output().unwrap();
    let log = format!(
        "{}{}",
        String::from_utf8_lossy(&publish.stdout),
        String::from_utf8_lossy(&publish.stderr)
    );
    let _ = std::fs::remove_dir_all(&dir);
    // Reaching the (intentionally aborted) upload is the real acceptance signal:
    // cargo prints "Uploading <crate>" only after packaging *and* the verify
    // build both succeed — a bad manifest, a verify-build error, or an
    // unpublishable dep aborts earlier, before this line. The dry-run then
    // aborts the upload itself; some cargo versions signal that abort with a
    // non-zero exit even though the crate is fully publish-ready, so the exit
    // code is not a reliable pass/fail signal here — the log is.
    assert!(
        log.contains("Uploading box-open-sdk"),
        "cargo publish --dry-run did not complete packaging + verify (NF-8):\n{log}"
    );
}

/// The workspace's pinned toolchain channel from `rust-toolchain.toml` (NF-6),
/// e.g. `"1.94.1"` — `None` if the file or the `channel = "…"` line is absent.
fn pinned_toolchain() -> Option<String> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../rust-toolchain.toml");
    let text = std::fs::read_to_string(path).ok()?;
    text.lines()
        .find_map(|l| l.trim().strip_prefix("channel"))
        .and_then(|rest| rest.trim().strip_prefix('='))
        .map(|rhs| rhs.trim().trim_matches('"').to_string())
        .filter(|c| !c.is_empty())
}

/// D-192: the shipped tree must carry the real runtime, never the
/// compile-only contract stub. Every other gate here proves the output
/// *compiles* — which the stub does, while panicking on every call. This is
/// the one that proves it *works*.
#[test]
fn no_generated_file_ships_the_runtime_stub() {
    let files = generate();
    let findings = gantry_verify::shipping::stub_findings(
        files.iter().map(|f| (f.path.as_str(), f.content.as_str())),
    );
    assert!(
        findings.is_empty(),
        "generated SDK ships runtime stubs instead of the vendored runtime: {findings:#?}"
    );
    // The runtime is actually present, so an empty result can't mean
    // "nothing was emitted".
    assert!(
        files.iter().any(|f| f.path == "src/runtime/mod.rs"),
        "expected the vendored runtime at src/runtime/mod.rs"
    );
}
